### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ivan-hc**

### CODE REVIEW

**Comment by ivan-hc** [comment]
@zen0bit just found an issue here, `-c` removes all the modules without checking if they already exist. Why?

Istantanea_2024-04-21_10-44-05

**Comment by ivan-hc** [comment]
@zenobit You have changed something because clean.am cannot recognizes if a module is hosted or not, so it removes all of them with no differences

**Comment by ivan-hc** [comment]
I've temporarilly disabled the function in clean.am for tests https://github.com/ivan-hc/AM/pull/451

**Comment by ivan-hc** [comment]
Here I begin on Sunday, the Lord's Day, to blaspheme him in every way

**Comment by ivan-hc** [comment]
This happens because the function is looking for *.am references in the main CLI, and you've removed it. Now I have to revrite the function. No way to be in peace here... dammit.

**Comment by zen0bit** [comment]
What don't removed anything. Just changed everything 😳

**Comment by ivan-hc** [comment]
I've fixed it by adding again the extension .am where is needed in tha main CLI, anso changed a brief line in clean.am

All this after trying not to change what you've changed.

Don't worry, I've only loose one hour of my life.

**Comment by ivan-hc** [comment]
@zen0bit well done anyway

**Comment by zen0bit** [comment]
You are welcome

**Comment by ivan-hc** [comment]
> You are welcome
> 
> May I continue then?

If you don't put me in the position of having to headbutt the wall myself, yes

**Pull request merged**
