### PR TITLE
Improve option "--rollback" to downgrade the apps

### PR DESCRIPTION
**Pull request by ivan-hc**
Still a work in progress.

### CODE REVIEW

**Comment by Samueru-sama** [comment]
I noticed you added the `echo "$d" > ./version` instead of using the full path to the `version` file. 

I'm assuming this is because the script `cd` into the directory where `version` is located. Saying it just in case lol.

**Comment by ivan-hc** [comment]
Anyway, we have too many kind of AM-updater scripts, its quite diffucult to use them as AM-updater... also it would be the best way to downgrade an app.

**Comment by Samueru-sama** [comment]
> Anyway, we have too many kind of AM-updater scripts, its quite diffucult to use them as AM-updater... also it would be the best way to downgrade an app.

Im going to sleep rn but will continue this tomorrow as I have questions about what you said here.

**Comment by ivan-hc** [comment]
I've said wrong. I mean AM-rollback, not AM-updater. There are too many now, its difficult to have one way to convert the AM-updater into an AM-rollback script.

**Comment by ivan-hc** [comment]
I solved it by temporarily adding the .old extension to the .zsync files.

It was easier than I thought.

**Comment by ivan-hc** [comment]
Now I need to importa all `grep` references from the AM-updater to the command
```
printf "%s\n" "$(curl -Ls $HeaderAuthWithGITPAT https://api.github.com/repos/$REPO/releases?per_page=100 \
				| grep browser_download_url | cut -d '"' -f 4)" | tr ' ' '\n' | grep -i "$extension$" >> "$AMCACHEDIR/rollback-args"
```
so we can have a shorter list, not to include unwanted result.

Can you continue if you wake up earlier? I think I'll go too right now.

**Comment by Samueru-sama** [comment]
> I've said wrong. I mean AM-rollback, not AM-updater. There are too many now, its difficult to have one way to convert the AM-updater into an AM-rollback script.

I still don't understand what does rollback have to do with the `AM-updater` and also what is a `AM-rollback` script?

I'm assuming this is how the rollback function works, which also is only available for github? that's odd because this way it should work on every versioned appimage: 

* rollback checks the line that contains `version=$(FUNCTION)` in the `AM-updater` and copies what is inside the parenthesis and replaces the `head -1` for a `head -100`

* Now that function with the `head -100` will give you a list of all the available appimages, provided the appimage isn't a continuous release.

* The user selects one url from the list, and that gets downloaded, replaces the old file and the url gets redirected to the `version` file. 

* Optionally if we don't want the `AM-updater` to update the appimage again, all that has to be done is insert an `exit 0` at the beginning of the script, that way the AM-updater gets disabled. You can also rename the `AM-updater` to I don't know `disabled.AM-updater` and that way it doesn't get run by AM.

**Comment by ivan-hc** [comment]
> `head -100`

@Samueru-sama you're a genious!! :rocket:

**Comment by Samueru-sama** [comment]
> > `head -100`
> 
> @Samueru-sama you're a genious!! 🚀

Wasn't head -100 being used already?

**Comment by ivan-hc** [comment]
> Wasn't head -100 being used already?

nope

however, I'm testing this command:

Now I use this command
```
			entries_list=$(cat ./AM-updater | grep "^version=" | sed '1,${ s/version=$(//g; s/head -1)/head -100/g; s#releases/latest#releases#g; s#releases #releases?per_page=200 #g; }')
			printf "%s\n" "$(echo "$entries_list" | bash)" | tr ' ' '\n' | grep -i "$extension$" >> "$AMCACHEDIR/rollback-args"
```

and this is the result, for firefox-nightly-appimage

```
ivan@debian:~$ am --rollback firefox-nightly-appimage 
-----------------------------------------------------------------------
You have chosen to roll back firefox-nightly-appimage.
Rollback will be done from https://github.com/srevinsaju/Firefox-Appimage
-----------------------------------------------------------------------
Select a URL from this menu (read carefully) or press CTRL+C to abort:
-----------------------------------------------------------------------
 1) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly/firefox-nightly-129.0.r20240610213024-x86_64.AppImage
 2) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v129.0.r20240610213024/firefox-nightly-129.0.r20240610213024-x86_64.AppImage
 3) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240609205151/firefox-nightly-128.0.r20240609205151-x86_64.AppImage
 4) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240609094452/firefox-nightly-128.0.r20240609094452-x86_64.AppImage
 5) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240608210527/firefox-nightly-128.0.r20240608210527-x86_64.AppImage
 6) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240608092932/firefox-nightly-128.0.r20240608092932-x86_64.AppImage
 7) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240607213727/firefox-nightly-128.0.r20240607213727-x86_64.AppImage
 8) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240606154042/firefox-nightly-128.0.r20240606154042-x86_64.AppImage
 9) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240606092816/firefox-nightly-128.0.r20240606092816-x86_64.AppImage
10) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240605162721/firefox-nightly-128.0.r20240605162721-x86_64.AppImage
11) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240604210423/firefox-nightly-128.0.r20240604210423-x86_64.AppImage
12) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240603160728/firefox-nightly-128.0.r20240603160728-x86_64.AppImage
13) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240602210803/firefox-nightly-128.0.r20240602210803-x86_64.AppImage
14) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240602092157/firefox-nightly-128.0.r20240602092157-x86_64.AppImage
15) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240601213828/firefox-nightly-128.0.r20240601213828-x86_64.AppImage
16) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240601093340/firefox-nightly-128.0.r20240601093340-x86_64.AppImage
17) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240531093001/firefox-nightly-128.0.r20240531093001-x86_64.AppImage
18) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240530213713/firefox-nightly-128.0.r20240530213713-x86_64.AppImage
19) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240530040816/firefox-nightly-128.0.r20240530040816-x86_64.AppImage
20) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240529214854/firefox-nightly-128.0.r20240529214854-x86_64.AppImage
21) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240529013712/firefox-nightly-128.0.r20240529013712-x86_64.AppImage
22) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240528214532/firefox-nightly-128.0.r20240528214532-x86_64.AppImage
23) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240528001238/firefox-nightly-128.0.r20240528001238-x86_64.AppImage
24) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240527214906/firefox-nightly-128.0.r20240527214906-x86_64.AppImage
25) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240527092611/firefox-nightly-128.0.r20240527092611-x86_64.AppImage
26) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240526212755/firefox-nightly-128.0.r20240526212755-x86_64.AppImage
27) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240526090739/firefox-nightly-128.0.r20240526090739-x86_64.AppImage
28) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240525201917/firefox-nightly-128.0.r20240525201917-x86_64.AppImage
29) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240525094144/firefox-nightly-128.0.r20240525094144-x86_64.AppImage
30) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240524214745/firefox-nightly-128.0.r20240524214745-x86_64.AppImage
31) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240523205926/firefox-nightly-128.0.r20240523205926-x86_64.AppImage
32) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240523041055/firefox-nightly-128.0.r20240523041055-x86_64.AppImage
33) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240522214846/firefox-nightly-128.0.r20240522214846-x86_64.AppImage
34) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240522091937/firefox-nightly-128.0.r20240522091937-x86_64.AppImage
35) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240521213834/firefox-nightly-128.0.r20240521213834-x86_64.AppImage
36) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240521094553/firefox-nightly-128.0.r20240521094553-x86_64.AppImage
37) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240520093945/firefox-nightly-128.0.r20240520093945-x86_64.AppImage
38) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240519213431/firefox-nightly-128.0.r20240519213431-x86_64.AppImage
39) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240519092129/firefox-nightly-128.0.r20240519092129-x86_64.AppImage
40) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240518212749/firefox-nightly-128.0.r20240518212749-x86_64.AppImage
41) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240518092535/firefox-nightly-128.0.r20240518092535-x86_64.AppImage
42) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240517215359/firefox-nightly-128.0.r20240517215359-x86_64.AppImage
43) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240517092152/firefox-nightly-128.0.r20240517092152-x86_64.AppImage
44) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240516214828/firefox-nightly-128.0.r20240516214828-x86_64.AppImage
45) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240516091652/firefox-nightly-128.0.r20240516091652-x86_64.AppImage
46) https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-nightly-v128.0.r20240515202418/firefox-nightly-128.0.r20240515202418-x86_64.AppImage
#?
```
"only" 46 entries

while for brave-appimage
```
ivan@debian:~$ am --rollback brave-appimage 
-----------------------------------------------------------------------
You have chosen to roll back brave-appimage.
Rollback will be done from https://github.com/srevinsaju/Brave-AppImage
-----------------------------------------------------------------------
Select a URL from this menu (read carefully) or press CTRL+C to abort:
-----------------------------------------------------------------------
1) https://github.com/srevinsaju/Brave-AppImage/releases/download/v1.67.112/Brave-stable-v1.67.112-x86_64.AppImage
2) https://github.com/srevinsaju/Brave-AppImage/releases/download/v1.67.109/Brave-stable-v1.67.109-x86_64.AppImage
#?
```
just two.

But this is normal, github actions of these repositories are always releasing something... IIRC a new one each hour

**Comment by ivan-hc** [comment]
```
entries_list=$(cat ./AM-updater | grep "^version=" | sed '1,${ s/version=$(//g; s/head -1)/head -100/g; s#$REPO#'"$REPO"'#g; s#releases/latest#releases#g; s#releases #releases?per_page=100 #g; }')
printf "%s\n" "$(eval "$entries_list")" | tr ' ' '\n' | grep -i "$extension$" >> "$AMCACHEDIR/rollback-args"
```

**Comment by Samueru-sama** [comment]
> ```
> entries_list=$(cat ./AM-updater | grep "^version=" | sed '1,${ s/version=$(//g; s/head -1)/head -100/g; s#$REPO#'"$REPO"'#g; s#releases/latest#releases#g; s#releases #releases?per_page=100 #g; }')
> printf "%s\n" "$(eval "$entries_list")" | tr ' ' '\n' | grep -i "$extension$" >> "$AMCACHEDIR/rollback-args"
> ```

Small optimization, change `cat ./AM-updater | grep "^version=" ` for `grep "^version=" ./AM-updater `

**Comment by ivan-hc** [comment]
Now we are sure that anyone understand what --rollback does

**Pull request merged**
