### PR TITLE
Add Neovide install script

### PR DESCRIPTION
**Pull request by TKK13909**
This is my first time contributing code to an open-source project! I looked at a few other PRs so I think this should be good. Please don't hesitate to tell me if I did anything wrong.

### CODE REVIEW

**Comment by ivan-hc** [comment]
> This is my first time contributing code to an open-source project! I looked at a few other PRs so I think this should be good. Please don't hesitate to tell me if I did anything wrong.

you did well, congratulations! Just checked the script and the list, and its all OK.

Happy firts contributing then!

**Comment by TKK13909** [comment]
Thanks so much man!

**Comment by Samueru-sama** [comment]
@TKK13909 Thanks for the PR

Just in case, since you mentioned you looked at other PRs, you can use the `am -t nameofapp` to generated the script, which for appimages hosted on github it is as simple as pasting the url of the github repo.

**Comment by TKK13909** [comment]
> Just in case, since you mentioned you looked at other PRs, you can use the `am -t nameofapp` to generated the script, which for appimages hosted on github it is as simple as pasting the url of the github repo.

I used that method but I did make sure to read other PRs to make sure I wasn't missing anything.

**Pull request merged**
