### PR TITLE
Small improvement, ready to merge

### PR DESCRIPTION
**Pull request by Samueru-sama**
This way I don't have to be repeating code if the appimage contains a symlink to another symlink. 

However it means that it is possible for the script to get stuck in a loop if the appimage for some reason has a symlink loop ( I don't think that is possible but be aware of that if a install script ever hangs and uses a lot of cpu lol).

### CODE REVIEW

**Comment by Samueru-sama** [comment]
Wait don't merge I have a better idea to prevent it from getting stuck in a loop

**Comment by Samueru-sama** [comment]
Done, this way the script automatically tries to resolve the symlinks up to ten times or when `./"$APP".desktop` and `./DirIcon` are no longer symlinks. 

This way it won't get stuck in a loop.

**Comment by Samueru-sama** [comment]
Alright, here are some scripts that were auto generated (I didn't touch them). here is the template it made for the htop appimage: 

```
#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 
set -u
APP=htop
SITE="Samueru-sama/htop-AppImage"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
echo "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
echo "rm -f /usr/share/applications/AM-$APP.desktop" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/Samueru-sama/htop-AppImage/releases | jq '.' | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
wget "$version" || exit 1
wget "$version.zsync" 2> /dev/null
echo "$version" > /opt/$APP/version
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
rm -R -f ./tmp || exit 1
chmod a+x "/opt/$APP/$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
set -u
APP=htop
SITE="Samueru-sama/htop-AppImage"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/Samueru-sama/htop-AppImage/releases | jq '.' | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ] || test -f /opt/"$APP"/*.zsync; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
	zsync "/opt/$APP/$APP.zsync" 2>/dev/null
	chmod a+x "/opt/$APP/$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
	exit 0
fi
echo "Update not needed!"
EOF
chmod a+x "/opt/$APP/AM-updater"

# LAUNCHER & ICON
cd "/opt/$APP" || exit 1
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./"$APP".desktop ]; then
		LINKPATH=$(readlink ./"$APP".desktop)
		./"$APP" --appimage-extract "$LINKPATH" && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
	fi
	if [ -L ./DirIcon ]; then
		LINKPATH=$(readlink ./DirIcon)
		./"$APP" --appimage-extract "$LINKPATH" && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/share/applications/AM-"$APP".desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root
```

Works perfectly, the updater and everything.

And here is the script it made for CPU-X: 

```
#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 
set -u
APP=cpu-x
SITE="TheTumultuousUnicornOfDarkness/CPU-X"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
echo "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
echo "rm -f /usr/share/applications/AM-$APP.desktop" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/TheTumultuousUnicornOfDarkness/CPU-X/releases | jq '.' | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
wget "$version" || exit 1
wget "$version.zsync" 2> /dev/null
echo "$version" > /opt/$APP/version
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
rm -R -f ./tmp || exit 1
chmod a+x "/opt/$APP/$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
set -u
APP=cpu-x
SITE="TheTumultuousUnicornOfDarkness/CPU-X"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/TheTumultuousUnicornOfDarkness/CPU-X/releases | jq '.' | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ] || test -f /opt/"$APP"/*.zsync; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
	zsync "/opt/$APP/$APP.zsync" 2>/dev/null
	chmod a+x "/opt/$APP/$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
	exit 0
fi
echo "Update not needed!"
EOF
chmod a+x "/opt/$APP/AM-updater"

# LAUNCHER & ICON
cd "/opt/$APP" || exit 1
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./"$APP".desktop ]; then
		LINKPATH=$(readlink ./"$APP".desktop)
		./"$APP" --appimage-extract "$LINKPATH" && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
	fi
	if [ -L ./DirIcon ]; then
		LINKPATH=$(readlink ./DirIcon)
		./"$APP" --appimage-extract "$LINKPATH" && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/share/applications/AM-"$APP".desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root
```

Once again it works perfectly. The only issue is that zsync update is broken but because zsync itself can't update the program

-------------------------------------------------------

Hopefully I can figure out a way to fix the zsync issue before contacting the cpu-x dev.

**Comment by ivan-hc** [comment]
@Samueru-sama I was thinking... what if instead the exit message is consulted in the background when zsync is used for the first time? In case of error, delete the zsync file and allow update by comparison. What do you think?

You may test this with a converted AppImage converted to Type3 from Type2

**Comment by Samueru-sama** [comment]
> @Samueru-sama I was thinking... what if instead the exit message is consulted in the background when zsync is used for the first time? In case of error, delete the zsync file and allow update by comparison. What do you think?
> 
> You may test this with a converted AppImage converted to Type3 from Type2

The problem is that some appimages have a fixed url, meaning that only way to update them is with the zsync file. 

I already opened an issue at cpu-x btw. 

But yeah the updater needs to be changed to something like this: 

`[ -e "/opt/"$APP"/*.zsync" ] zsync "/opt/$APP/$APP.zsync" || notify-send -u critical "zsync failed to update $APP"`

That way at least you know what zsync failed. And if the file doesn't exist it doesn't try to launch zsync.

**Comment by ivan-hc** [comment]
However, the .zsync file to work needs to have tha same name of the AppImage, so
- if Bottles-51.11-2-Type3-x86_64.AppImage, then Bottles-51.11-2-Type3-x86_64.AppImage.zsync
- if bottles, then bottles.zsync

PS: I do not know how to create updatable AppImages, so take this just as an example... I had this repo opened under my eyes and posted the name of the file here

**Pull request merged**
