### PR TITLE
Fixed installation scripts by introducing patches from install.am

### PR DESCRIPTION
**Pull request by ivan-hc**
In this PR I'll upload all installation scripts for x86_64 with the following changes:
- all the ones containing the keyword "api.github.com" will include the command `jq '.'`;
- all versions/urls will be checked using `curl -Ls $URL` instead of `wget -q $URL -O -`
- al references to `rm ./` and `rm /` will be silenced by adding a `-f`
- all references to `mv $(./$APP --appimage-extract \*.png)` and `mv $(./$APP --appimage-extract \*.svg)` are been changed with `./$APP --appimage-extract *.png 2>&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* ./icons/$APP 2>/dev/null` and
`./$APP --appimage-extract *.svg 2>&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* ./icons/$APP 2>/dev/null`

in this way the common patch in install.am changes from
```
					function _install_common_patch(){
						if ! grep -q -- "--debug" $AMPATH/.cache/install-args; then
							# Add "jq" to manage github APIs
							if grep -q "api.github.com" ./$arg; then
								if [ "$arg" != jq ]; then
									sed -i "s#-O -#-O - | jq '.'#g" ./$arg
								fi
							fi
							# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
							if wget --version | head -1 | grep -q ' 1.'; then
								sed -i "s#wget #wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #g" ./$arg
								sed -i 's#$(wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #$(wget -q #g' ./$arg
								sed -i "s# -q -q # -q #g" ./$arg
							fi
							# Silence "rm" errors by adding "-f"
							sed -i 's#^rm /#rm -f /#g' ./$arg; sed -i 's#^rm ./#rm -f ./#g' ./$arg
							# Silence "mv", "sed" errors and "squashfs-root" messages
							sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./$arg
							sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i 's#mv $(./$APP --appimage-extract \*.png) #./$APP --appimage-extract \*.png 2>\&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* #g' ./$arg
							sed -i 's#mv $(./$APP --appimage-extract \*.svg) #./$APP --appimage-extract \*.svg 2>\&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* #g' ./$arg
							sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
						fi
						sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
					}
```
to
```
					function _install_common_patch(){
						if ! grep -q -- "--debug" $AMPATH/.cache/install-args; then
							# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
							if wget --version | head -1 | grep -q ' 1.'; then
								sed -i "s#wget #wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #g" ./$arg
							fi
							# Silence "mv", "sed" errors and "squashfs-root" messages
							sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./$arg
							sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
						fi
						sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
					}
```

### CODE REVIEW

**Comment by ivan-hc** [comment]
@zen0bit before I go, thake care of changes in template.am for https://github.com/ivan-hc/AM/pull/538 , see https://github.com/ivan-hc/AM/pull/548/commits/1c9e2f3f735afe8f2fa8fc418b2bd31ebadcb864

I leave this opened in case @nazdridoy and @Samueru-sama want to see it. Nothing is changed in this PR.

Maybe @Samueru-sama should take care of templates including these changes

See you later

**Comment by ivan-hc** [comment]
Now that all patches that can be already implemented are in place, let me explain the ones left in the function
```
					function _install_common_patch(){
						if ! grep -q -- "--debug" $AMPATH/.cache/install-args; then
							# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
							if wget --version | head -1 | grep -q ' 1.'; then
								sed -i "s#wget #wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #g" ./$arg
							fi
							# Silence "mv", "sed" errors and "squashfs-root" messages
							sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./$arg
							sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
						fi
						sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
					}
```

as you can see, there is a group between `if` and `fi` and the last command, the one left alone, is an idea of @nazdridoy to improve performances when a script points to an application that come from github and uses its APIs to check the download URL, i.e.
```
sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
```
this is needed as an external patch because you may have/have not a github key.

***And now, let we see the group of patches between `if` and `fi`, and this can be disabled if you run the command `am -i --debug $APP` to see the real messages without these patches:***

1. this function recognizes if the version of "wget" is the 1.x or not
```
if wget --version | head -1 | grep -q ' 1.'; then
	sed -i "s#wget #wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #g" ./$arg
fi
```
if wget 1.x, then we can have the nice animation with dots (`--show-progress --progress=dot`) and each dot is 500KB (`-e dotbytes=500K`). While these options are not included in "wget2", causing the breackage of the download and all the errors seen at https://github.com/ivan-hc/AM/issues/496, the other two are instead a common one between wget and wget2 (`-q --no-verbose`) and they act differently, in wget no output is shown, in wget2 its shown only the progress bar, as we run `wget -q --no-verbose --show-progress`.

If we remove this patch we have this result with wget 1.x

https://github.com/ivan-hc/AM/assets/88724353/e7564e20-89ca-4faa-be10-2be69f61a562

while in wget2 we have only the progress bar and some indicators.

Its safe to remove this, but its a ugly output to see (in wget 1.x at least);

2. this is the command I call the "Samuel's", because created for @Samueru-sama and its new templates
```
sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./$arg
```
all it does is to replace the references of `&& mv` (only available in its scripts) with ` | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv`. The `&&` is replaced with a `;` and before the latter we have a command that we will see below, needed to silence some unwanted outputs.

I can remove this, but @Samueru-sama said that is not correct to write the scripts without the `&&`.

The lines of the new scripts affected by this patch are (from [AM-SAMPLE-AppImage](https://github.com/ivan-hc/AM/blob/main/templates/AM-SAMPLE-AppImage))
```
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
```
@Samueru-sama if you want to keep them, I suggest to write them like this
```
./"$APP" --appimage-extract .DirIcon 1>/dev/null &&
mv ./squashfs-root/.DirIcon ./DirIcon
./"$APP" --appimage-extract *.desktop 1>/dev/null &&
mv ./squashfs-root/*.desktop ./"$APP".desktop
```
anyway, as you can see, this ptch exists since you created these scripts, so your command does not act as you have ment to.

3. the following two commands are ment to patch all lines starting with `mv` and `sed` to prevent unwanted outputs
```
sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
```
these errors are due to the function used in the installation script to move/patch elements extracted from an AppImage and that are not found in some of the common places where they may be stored.

The new template of @Samueru-sama solves this issue, but the scripts with this line are hundreds. The best practice would be to convert all of them to the new function of @Samueru-sama 

4. the other two commands are needed to silence the output of `--appimage-extract` that are hardcoded (and hard to kill)
```
sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
```
sometime they may be placed in front of an already existing `2>/dev/null` and one of them has been already mentioned in the point 2.

----------------------------------

# Conclusions

That said, this PR is a fix to all installation scripts that I've wrote in the past and that I had not the opportunity to patch, due to issues that @zen0bit now knows (`git push` does not work on my system at all).

I thank @zen0bit to take care of this push for me. For us. The `sed` command is a slow one, thanks to this we have get rid of the following commands
```
if grep -q "api.github.com" ./$arg; then
	if [ "$arg" != jq ]; then
		sed -i "s#-O -#-O - | jq '.'#g" ./$arg
	fi
fi
sed -i 's#$(wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #$(wget -q #g' ./$arg
sed -i "s# -q -q # -q #g" ./$arg
sed -i 's#^rm /#rm -f /#g' ./$arg; sed -i 's#^rm ./#rm -f ./#g' ./$arg
sed -i 's#mv $(./$APP --appimage-extract \*.png) #./$APP --appimage-extract \*.png 2>\&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* #g' ./$arg
sed -i 's#mv $(./$APP --appimage-extract \*.svg) #./$APP --appimage-extract \*.svg 2>\&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* #g' ./$arg
```

and this is what this PR does.

I've also placed the new command to check urls from api.github.com in template.am, so if we want to create new installation scripts using the new templates for AppImages and archives, we have the same configuration of the installaton scripts in this PR.

The ones that are not patched are the ones for i686 and aarch64... but they are a few and I'm suer they are not much used. We can patch them later without problems.


Is this PR any good?

Do you agree if I merge it to main?

**Comment by zen0bit** [comment]
Mot tested, but if you sure...

MERGE

**Comment by ivan-hc** [comment]
@Samueru-sama ?

**Comment by ivan-hc** [comment]
@Samueru-sama in case, given the above, you decide to make improvements to the new scripts and templates (see point 2)... I would be happy to see some of your proposals to reduce patches, lighten the burden of responsibility of the install.am module on installation script and then make the installation interface as natural as possible.

"wget" is implemented in different ways in the installation scripts, so eradicating it completely would be impossible, and even applying a patch like the one I explained in point one would be painless, it would only change the aesthetics between "wget" and "wget2 ".

Thank you.

**Comment by zen0bit** [comment]
> @Samueru-sama in case, given the above, you decide to make improvements to the new scripts and templates (see point 2)... I would be happy to see some of your proposals to reduce patches, lighten the burden of responsibility of the install.am module on installation script and then make the installation interface as natural as possible.
> 
> "wget" is implemented in different ways in the installation scripts, so eradicating it completely would be impossible, and even applying a patch like the one I explained in point one would be painless, it would only change the aesthetics between "wget" and "wget2 ".
> 
> Thank you.

& @ivan-hc 
I suggest not touch app scripts if is not needed (fix)

I want simplify all of them...
### Let's keep installation scripts and app templates separated

**Comment by ivan-hc** [comment]
PS: maybe its time to update the existing installation scripts for aarch64 and i686 (sometime I use AM on the latter)

**Comment by ivan-hc** [comment]
> & @ivan-hc I suggest not touch app scripts if is not needed (fix)
> 
> I want simplify all of them...
> ### Let's keep installation scripts and app templates separated

sure, now its time for you to work

**Comment by zen0bit** [comment]
> PS: maybe its time to update the existing installation scripts for aarch64 and i686 (sometime I use AM on the latter)

Change to `curl` is fine...

go on

**Comment by Samueru-sama** [comment]
The install scripts need work @zen0bit even the current template could be more efficient. I will see what you come up with. 

However @ivan-hc not allowing `&&` in the install scripts is just a hack lol. And yes right now it doesn't matter much because `--appimage-extract` does not exit with error status when it doesn't find anything, so you can just replace those specific `&&` for `;` but do not do so anywhere else if a script needs that. 

In fact this could be a function: 

```
if [ -L ./DirIcon ]; then
	LINKPATH=$(readlink ./DirIcon)
	./"$APP" --appimage-extract "$LINKPATH" && mv ./squashfs-root/"$LINKPATH" ./DirIcon
fi
```

As there is the small possibility for DirIcon to be a symlink to another symlink like it happened with lime3ds.

**Comment by zen0bit** [comment]
I wanna end with something like this:
Just example from void-packages
```
# Template file for 'gum'
pkgname=gum
version=0.14.0
revision=1
build_style=go
build_helper=qemu
go_import_path="github.com/charmbracelet/gum"
go_ldflags="-X main.Version=${version}"
short_desc="Tool for glamorous shell scripts"
maintainer="zenobit <zenobit@disroot.org>"
license="MIT"
homepage="https://github.com/charmbracelet/gum"
changelog="https://github.com/charmbracelet/gum/releases"
distfiles="https://github.com/charmbracelet/gum/archive/refs/tags/v${version}.tar.gz"
checksum=3174a1c8ff706d57c93da33fdf477b26620ad0f7096d97e21a005132fa74756a

post_install() {
	vlicense LICENSE

	for shell in bash fish zsh; do
		vtargetrun ${DESTDIR}/usr/bin/gum completion $shell > gum.${shell}
		vcompletion gum.${shell} $shell
	done
	vtargetrun ${DESTDIR}/usr/bin/gum man > gum.1
	vman gum.1
}
```
(Template from void linux for gum...)

**Comment by ivan-hc** [comment]
@zen0bit nice... but I hope you can add a dynamic command to check for the latest version, or you will have to manually update the scripts periodically... or daily. It depends on how frequent application releases are.

**Comment by zen0bit** [comment]
> @zen0bit nice... but I hope you can add a dynamic command to check for the latest version, or you will have to manually update the scripts periodically... or daily. It depends on how frequent application releases are.

You already said about right solution...

Everything will be done in CI (Maybe some exceptions... will see)

**Comment by zen0bit** [comment]
from my clean_launcher branch...

**Comment by ivan-hc** [comment]
could definitely be useful, "core.am" would be... but it would be huge and not modular. Do you agree that it is the right choice?

**Comment by ivan-hc** [comment]
also -d would be includes

**Comment by ivan-hc** [comment]
sandboxes, nolibfuse, no-updates... maybe sandboxes... its definitelly a big step back to the monolitic form

**Comment by zen0bit** [comment]
Sorry bad imperpretation

all modules which change anything in app scripts

**Comment by zen0bit** [comment]
Is just step not destination...

But it will make refactoring easier

After that will be easy make modules which we will need...

just move functions to new module and call new module...

**Comment by zen0bit** [comment]
But let's continue this conversation in my open PR... #538

**Pull request merged**
