### PR TITLE
help

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by ivan-hc** [comment]
you removed some options (i.e. `apikey` and `dev`), also th view in my terminal is confusing.

**Comment by zen0bit** [comment]
apikey and dev are there. Just strange diff on github, as on my side?

th view in my terminal is confusing??

**Comment by zen0bit** [comment]
I am using it in termux like appman | fold -s -w $(tput cols)

Looks nicer (except logo and thank you "image")

**Comment by ivan-hc** [comment]
> Looks nicer (except logo and thank you "image")

The logo is still there, the message you talket [here](https://github.com/ivan-hc/AM/issues/121) as been removed

https://github.com/ivan-hc/AM/commit/6d05a8278ab03db90df1f038f4efc116923d049e

Now all remains is to adapt it to a small screen... are lines 
```
__________________________________________________________________________
```
and
```
 ##########################################################################
```
a problem for you?

**Comment by zen0bit** [comment]
https://github.com/ivan-hc/AM/assets/6384793/c75b0194-3f8c-4cfc-b301-0f029f13b27d

**Comment by ivan-hc** [comment]
OK, I'm just working on this

**Comment by zen0bit** [comment]
You could leave your previous help message for manpage? It's nice on bigger screen. Don't throw it away yet..

**Comment by ivan-hc** [comment]
> You could leave your previous help message for manpage? It's nice on bigger screen. Don't throw it away yet..

don't worry, the new one will be enough.

SPOILER: will look like `-f`

**Comment by ivan-hc** [comment]
@zen0bit I can't do better than this, I divided the "help" message in three parts:
- _help_head (brand/logo)
- _help_body (all options)
- _help_footer (sites and urls)

This is the function:
```
 function _help_on_device(){
 	if command -v termux-setup-storage; then
 		_help_body | sed 's/_____//g' | tr 'SYNOPSIS:	' 'SYNOPSIS:\n' | sed 's/	//g' | sed 's/____/------------------------------------------------/g'| sed 's/###########################################//g' | sed 's/^[ \t]*//' | column
 		_help_footer
 	else
 		function _help_normal(){
 			_help_head
 			_help_body
 			_help_footer
 		}
 		_help_normal | less
 	fi
 }
```
In brief, this function will check for `termux-setup-storage`, if exists, then only the body and footer will be shown, and the body will be patched to be adapted to a smaller screen. I've also aded some separators of max 48 characters.

This is the final result:

https://github.com/ivan-hc/AM/assets/88724353/280e2462-9569-4a5f-9ad5-24d89e096e87

I hope you like it.

**Pull request closed without merging**
