### PR TITLE
replace `grep -P` for posix alternative

### PR DESCRIPTION
**Pull request by Samueru-sama**
test carefully. 

Haven't found issues: 

image

image

@xplshn @leo-arch If you have a better idea for the `_find_no_order` func let me know.

### CODE REVIEW

**Comment by Samueru-sama** [comment]
@xplshn Had a better idea that works, I get the same word count as before and all of that.

**Comment by ivan-hc** [comment]
by mistake I used the flag `--appimage` instead of the real one, `--appimages` (with filan "s"), this is what's happened

Istantanea_2024-12-11_13-32-28

I had to CTRL+C to close this

**Comment by Samueru-sama** [comment]
fixed, it was the grep interpreting the flag. 

This shows that `grep -q` is not always the same as `grep 2>/dev/null` lol

**Comment by xplshn** [comment]
> fixed, it was the grep interpreting the flag.
> 
> This shows that `grep -q` is not always the same as `grep 2>/dev/null` lol

You can use `--` to tell programs to stop interpreting anything that comes after `--` as a flag.

I'm not sure if this behavior is truly POSIX, but it is respected in Busybox, GNU coreutils and Toybox, I've never had to use `--` in BSD-land before so I'm not sure about it

**Comment by Samueru-sama** [comment]
Yeah we have had to use `--` before, we do that already in other places with AM.

**Pull request merged**
