### PR TITLE
Use "Next Generation AppImage" instead of "Type3"

### PR DESCRIPTION
**Pull request by ivan-hc**
Change of wording, at the request of the creator of AppImage @probonopd

This is a continuation of what has already been changed in "files.am", see https://github.com/ivan-hc/AM/commit/368f2fa97a7b1a09cde92ea450ee4345ede2ee39

### CODE REVIEW

**Comment by probonopd** [comment]
Technically, these are [Type 0](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-0-image-format), as you can see from the AppImageSpec:

> Reserved for not fully standards-compliant AppImages (e.g., portable binaries that look and behave like AppImages on a user level, but do not conform to a standard on a programming level).

Also, please be aware that there are many different implementations, so the only reliable source on what can be assumed is AppImageSpec:

* https://github.com/linux-packaging-rs/appimage-type2-runtime-rs
* https://github.com/orivej/static-appimage
* https://github.com/tim-janik/appimage-runtime
* https://github.com/mensinda/libRuntime
* https://github.com/AppImageCrafters/appimage-runtime
* https://github.com/haampie/appimage_runtime
* https://github.com/CalebQ42/appimage-runtime
* and probably more

**Comment by ivan-hc** [comment]
> Technically, these are [Type 0](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-0-image-format), as you can see from the AppImageSpec:

sorry to disappoint you, but if this is "zero", is the best "zero" I have ever seen!

Also better than 1 and 2!

Congratulations :)

PS: I'm still waiting for this PR have been merged https://github.com/AppImage/appimagetool/issues/9

once it is ready, big things will come, for this project and several others... if not for all other projects that choose AppImage.

I trust in your work :+1:

**Comment by probonopd** [comment]
As per the AppImageSpec (did you read it?) Type 0 just means "everything else but type 1 and type 2".

**Comment by probonopd** [comment]
> PS: I'm still waiting for this PR to be merged https://github.com/AppImage/appimagetool/issues/9

Waiting on @TheAssassin.

**Pull request merged**
