### PR TITLE
Fixed installation scripts by introducing patches from install.am

### PR DESCRIPTION
**Pull request by ivan-hc**
In this PR I'll upload all installation scripts for x86_64 with the following changes:
- all the ones containing the keyword "api.github.com" will include the command `jq '.'`;
- all versions/urls will be checked using `curl -Ls $URL` instead of `wget -q $URL -O -`
- al references to `rm ./` and `rm /` will be silenced by adding a `-f`
- all references to `mv $(./$APP --appimage-extract \*.png)` and `mv $(./$APP --appimage-extract \*.svg)` are been changed with `./$APP --appimage-extract *.png 2>&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* ./icons/$APP 2>/dev/null` and
`./$APP --appimage-extract *.svg 2>&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* ./icons/$APP 2>/dev/null`

in this way the common patch in install.am changes from
```
					function _install_common_patch(){
						if ! grep -q -- "--debug" $AMPATH/.cache/install-args; then
							# Add "jq" to manage github APIs
							if grep -q "api.github.com" ./$arg; then
								if [ "$arg" != jq ]; then
									sed -i "s#-O -#-O - | jq '.'#g" ./$arg
								fi
							fi
							# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
							if wget --version | head -1 | grep -q ' 1.'; then
								sed -i "s#wget #wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #g" ./$arg
								sed -i 's#$(wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #$(wget -q #g' ./$arg
								sed -i "s# -q -q # -q #g" ./$arg
							fi
							# Silence "rm" errors by adding "-f"
							sed -i 's#^rm /#rm -f /#g' ./$arg; sed -i 's#^rm ./#rm -f ./#g' ./$arg
							# Silence "mv", "sed" errors and "squashfs-root" messages
							sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./$arg
							sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i 's#mv $(./$APP --appimage-extract \*.png) #./$APP --appimage-extract \*.png 2>\&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* #g' ./$arg
							sed -i 's#mv $(./$APP --appimage-extract \*.svg) #./$APP --appimage-extract \*.svg 2>\&1 | grep -v "squashfs-root"; mv ./squashfs-root/*$app* #g' ./$arg
							sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
						fi
						sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
					}
```
to
```
					function _install_common_patch(){
						if ! grep -q -- "--debug" $AMPATH/.cache/install-args; then
							# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
							if wget --version | head -1 | grep -q ' 1.'; then
								sed -i "s#wget #wget -q --no-verbose --show-progress --progress=dot -e dotbytes=500K #g" ./$arg
							fi
							# Silence "mv", "sed" errors and "squashfs-root" messages
							sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./$arg
							sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
							sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./$arg
						fi
						sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
					}
```

### CODE REVIEW

**Comment by ivan-hc** [comment]
@zen0bit @nazdridoy @Samueru-sama I need someone of you puching the content of the x86_64 directory in this .zip file to the database branch https://github.com/ivan-hc/AM/tree/database

[x86_64.zip](https://github.com/ivan-hc/AM/files/15206140/x86_64.zip)

If you want to know why I don't use GIT myself, it's because any attempt I make I'm denied access, whether I use a GITPAT access key or manually configure the SSL key... basically my GIT doesn't want to push in any way. I've tried so many times, even in the past months... that I've lost the will to commit to solving it. You have to believe me.

Here some of all error messages I get whe I try to push
```
The requested URL returned error: 403
...
Permission denied (publickey).
fatal: Impossibile leggere dal repository remoto.

Assicurati di disporre dei privilegi d'accesso corretti
e che il repository esista.
```
I checked the whole web looking for some solution... and finally I even tried using "gitkraken", as a last resort... and that also refuses to connect.

In the end, I tried to upload the files again as I always did, 100 at a time... and even github gives me an error.

So I have no alternative but you. Please help.

**Comment by zen0bit** [comment]
> @zen0bit @nazdridoy @Samueru-sama I need someone of you puching the content of the x86_64 directory in this .zip file to the database branch https://github.com/ivan-hc/AM/tree/database
> 
> [x86_64.zip](https://github.com/ivan-hc/AM/files/15206140/x86_64.zip)
> 
> If you want to know why I don't use GIT myself, it's because any attempt I make I'm denied access, whether I use a GITPAT access key or manually configure the SSL key... basically my GIT doesn't want to push in any way. I've tried so many times, even in the past months... that I've lost the will to commit to solving it. You have to believe me.
> 
> Here some of all error messages I get whe I try to push
> 
> ```
> The requested URL returned error: 403
> ...
> Permission denied (publickey).
> fatal: Impossibile leggere dal repository remoto.
> 
> Assicurati di disporre dei privilegi d'accesso corretti
> e che il repository esista.
> ```
> 
> I checked the whole web looking for some solution... and finally I even tried using "gitkraken", as a last resort... and that also refuses to connect.
> 
> In the end, I tried to upload the files again as I always did, 100 at a time... and even github gives me an error.
> 
> So I have no alternative but you. Please help.

Are you using SSH right?
https access for pushing was disabled while ago...

**Comment by ivan-hc** [comment]
yes, ssh

**Comment by zen0bit** [comment]
ed25519?

Never heard about anyone who can use it...
verry strange

**Comment by ivan-hc** [comment]
ssh-keygen -t ed25519 -C 

and didn't worked

**Comment by zen0bit** [comment]
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
This should work

Never have problem with that...

**Comment by ivan-hc** [comment]
yes, but I've tried also this and didn't worked.

Believe me, I spent half an hour/three quarters of an hour patching the scripts and testing 30 of them, checking them again and even updating some of them... then from midnight to around 3:30 I tried and tried again with `git push`. Really, I can't take it anymore.

**Comment by zen0bit** [comment]
ssh-keygen -t ed25519 -C <same mail as registered with github account>

**Comment by ivan-hc** [comment]
> ssh-keygen -t ed25519 -C `<same mail as registered with github account>`

I've done so. Doesn't work.

**Comment by zen0bit** [comment]
Even second one? ssh-keygen -t rsa -b 4096 -C "your_email@example.com"

**Comment by ivan-hc** [comment]
but I use Debian Testing, it isn't a legacy system

**Comment by zen0bit** [comment]
> but I use Debian Testing, it isn't a legacy system

As I said strange
First time heard about such problem

**Comment by zen0bit** [comment]
For me worked everytime...

**Comment by ivan-hc** [comment]
Yesterday I told you that I was bored doing it, but in reality I have tried many times, even in the past. Today I pushed myself to the point of exhaustion.

> For me worked everytime...

lucky you. I try to do things. Before 2021 I never used GIT to push. Out of nervousness I also deleted the GITPAT key I had just created for the occasion. I followed all the directions and copied/pasted all the error messages looking for a solution.

**Comment by zen0bit** [comment]
It should just work
I never have problem with pushing (just on github when changed that https)

**Comment by zen0bit** [comment]
can you generate pair for me? will try your generated..

**Comment by ivan-hc** [comment]
> can you generate pair for me? will try your generated..

?

**Comment by zen0bit** [comment]
key pair

**Comment by ivan-hc** [comment]
GITPAT? Isn't it private?

**Comment by zen0bit** [comment]
throw me cat of both to discord
Don't know what's GITPAT
 I am talking about ssh key to access your github

**Comment by ivan-hc** [comment]
GITPAT - key access token... or something

**Comment by zen0bit** [comment]
nope thats just for apps

**Comment by zen0bit** [comment]
you have to use ssh key par added to github for this its other thing

**Comment by ivan-hc** [comment]
discord

**Comment by nazdridoy** [comment]
> throw me cat of both to discord Don't know what's GITPAT I am talking about ssh key to access your github I think it isn't GITPAT

👀 @zen0bit i'm not sure  you should ask for his private info.

**Comment by ivan-hc** [comment]
him haven't, don't worry

**Comment by nazdridoy** [comment]
oh its ok then. 

ssh private key is something that should never be public. no one should ever ask for it and one should never provide it with out fully understanding the consequences.  

threat everyone (including me) as a potential external threat.

**Pull request closed without merging**
