### PR TITLE
💪

### PR DESCRIPTION
**Pull request by Samueru-sama**
This first change is needed to make it easier to transition AM to use no sudo later on. 

Haven't tested if this causes an issue with appman. (appman doesn't need to have its cache moved since it is always at a user owned location). 

Also I did not remove the sudo and ownership checks here, As that will be on a different pr.

### CODE REVIEW

**Comment by Samueru-sama** [comment]
Btw @ivan-hc is the `$XDG_DATA_HOME` check needed inside launcher.am? If the script is always called by APP-MANAGER/appman which pass the '$DATADIR' variable then I don't think it is needed.

**Comment by ivan-hc** [comment]
@Samueru-sama why `mkdir -p "$AMPATH"/modules "$CACHEDIR"/am`? What is `"$CACHEDIR"/am`?

**Comment by ivan-hc** [comment]
OK, I got it... user's $HOME ~/.cache directory

**Comment by Samueru-sama** [comment]
> @Samueru-sama why `mkdir -p "$AMPATH"/modules "$CACHEDIR"/am`? What is `"$CACHEDIR"/am`?

`$CACHEDIR/am` replaces `$AMPATH/.cache` and it uses XDG_DATA_HOME as the location. That location is never owned by root, so the regular user will have no problems running AM do to basic functions even if it isn't owned by them. 

(And also it follows the XDG_Base_Dir specification, which I know you aren't a fan of following rules lol).

**Comment by Samueru-sama** [comment]
> > Btw @ivan-hc is the `$XDG_DATA_HOME` check needed inside launcher.am? If the script is always called by APP-MANAGER/appman which pass the '$DATADIR' variable then I don't think it is needed.
> 
> I think that this was what remains of fisrts times you did this change... I don't remember but I think were you adding this

Yeah I would swear that I removed them from the modules as well lol. (I'm removing it now).

**Comment by Samueru-sama** [comment]
Hey you merged this right before I removed the xdg check in `launcher.am` 😅

**Comment by ivan-hc** [comment]
@Samueru-sama I added also the new variable "$AMBRANCH" for our tests

just replace at line 227 of APP-MANAGER
```
			AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
```
with
```
			AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/dev" # Consolidating variable assignments for clarity and brevity
```
and we can update/sync from "dev"

**Comment by ivan-hc** [comment]
Now let improve the INSTALL script

and if you can, upload the changes in the installation scripts

**Comment by Samueru-sama** [comment]
> Now let improve the INSTALL script
> 
> and if you can, upload the changes in the installation scripts

iirc the only change I did to INSTALL was remove the chown, which cannot be do right now as APP-MANAGER still needs sudo to update itself. 

I also didn't add the `$SUDOCOMMAND ./AM-updater` to the module that needs it to update the apps without sudo.

**Comment by ivan-hc** [comment]
would you prefer that I add an AM-updater or just an "updater" script (not to be managed by -u) in the INSTALL script?

**Comment by Samueru-sama** [comment]
> would you prefer that I add an AM-updater or just an "updater" script (not to be managed by -u) in the INSTALL script?

An AM-updater that does update APP-MANAGER and its modules would be great indeed.

**Comment by ivan-hc** [comment]
@Samueru-sama however, you said that it was enough to add $SUDOCOMMAND, isnt it?

**Comment by ivan-hc** [comment]
> @Samueru-sama however, you said that it was enough to add $SUDOCOMMAND, isnt it?

ah, I forgot.... no sudo command

**Comment by Samueru-sama** [comment]
> > @Samueru-sama however, you said that it was enough to add $SUDOCOMMAND, isnt it?
> 
> ah, I forgot.... no sudo command

`$SUDOCOMMAND` is enough if the single sudoers rule is added and AM has an AM-updater for itself. 

However you didn't like the idea of having to edit sudoers so I mentioned the other way with groups. (which once again I haven't taken a look at how they work, I know they do because other apps use them).

**Comment by ivan-hc** [comment]
@Samueru-sama on your fork, uploads are disabled, so download/extract this https://github.com/ivan-hc/AM/archive/refs/heads/dev.zip and add the content of "modules" in your branch

**Comment by Samueru-sama** [comment]
> @Samueru-sama on your fork, uploads are disabled, so download/extract this https://github.com/ivan-hc/AM/archive/refs/heads/dev.zip and add the content of "modules" in your branch

Btw I just hit the jackpot: 

```
echo "username ALL=NOPASSWD: /opt/*/AM-updater" | sudo tee -a /etc/sudoers

```

That does the sudoers change without having to use visudo. Of course username needs to be replaced by the actual name of the user first. 

This can be a function in AM that uses sudo to allow the user to update without password!

**Comment by Samueru-sama** [comment]
> @Samueru-sama on your fork, uploads are disabled, so download/extract this https://github.com/ivan-hc/AM/archive/refs/heads/dev.zip and add the content of "modules" in your branch

Oh fuck I misread this and uploaded the entire zip lol.

**Comment by Samueru-sama** [comment]
> @Samueru-sama on your fork, uploads are disabled, so download/extract this https://github.com/ivan-hc/AM/archive/refs/heads/dev.zip and add the content of "modules" in your branch

Done.

**Comment by ivan-hc** [comment]
@Samueru-sama what about
```
# ALLOW PERMISSIONS ONLY TO THE CORE FILES AND DIRECTORIES OF "AM", FOR ALL USERS OF "SUDO" GROUP
find /opt/am -exec chmod 775 {} \; 2> /dev/null
find /opt/am -exec chown -R :sudo {} \; 2> /dev/null
```
?

it seems to work in INSTALL

**Comment by ivan-hc** [comment]
sync also worked

**Comment by Samueru-sama** [comment]
> @Samueru-sama what about
> 
> ```
> # ALLOW PERMISSIONS ONLY TO THE CORE FILES AND DIRECTORIES OF "AM", FOR ALL USERS OF "SUDO" GROUP
> find /opt/am -exec chmod 775 {} \; 2> /dev/null
> find /opt/am -exec chown -R :sudo {} \; 2> /dev/null
> ```
> 
> ?
> 
> it seems to work in INSTALL

If it works and you don't have some weird shenanigans changing the ownership of /opt/am between users. And AM updates itself without password after adding `echo "username ALL=NOPASSWD: /opt/*/AM-updater" | sudo tee -a /etc/sudoers` then it is good.

**Comment by ivan-hc** [comment]
I've finished tests on main user, now I'm going test this on other two

**Comment by ivan-hc** [comment]
I've finished the tests on non privileged user, its all ok, him cannot update anything nor can remove anything

**Comment by Samueru-sama** [comment]
> I've finished the tests on non privileged user, its all ok, him cannot update anything nor can remove anything

By non privileged you mean not in wheel group? 

I did not test if the NOPASSWD works for users not in the wheel group but that are still added to sudoers.

**Comment by ivan-hc** [comment]
Updating AM and modules with the second administrator, I get these errors:

Istantanea_2024-04-26_00-03-38

**Comment by Samueru-sama** [comment]
> Updating AM and modules with the second administrator, I get these errors:
> 
> Istantanea_2024-04-26_00-03-38



> Updating AM and modules with the second administrator, I get these errors:
> 
> Istantanea_2024-04-26_00-03-38

Yeah I had the same error in the video I posted here. 

Adding `$SUDOCOMMAND $AMCLIPATH -s` to update.am fixed it for me

**Comment by ivan-hc** [comment]
> > I've finished the tests on non privileged user, its all ok, him cannot update anything nor can remove anything
> 
> By non privileged you mean not in wheel group?
> 
> I did not test if the NOPASSWD works for users not in the wheel group but that are still added to sudoers.

for non privileged users I only get some errors when trying to dovload a list with -l and I think its the same with -a (not tested yet), the AM-updater of an app is recognized, I get notification... but can't update.

We need to prevent non-sudo users having these messages.

Now there is only one issue: updating AM and modules using another admin

**Comment by ivan-hc** [comment]
Apart this, its all quite ready.

**Comment by ivan-hc** [comment]
@Samueru-sama any news?

**Comment by Samueru-sama** [comment]
> @Samueru-sama any news?

My appman issue is gone now, I think I still had the outdated modules in my home user lol.

Were you able to fix the missing option error?

**Comment by ivan-hc** [comment]
done

**Comment by ivan-hc** [comment]
just added a fix for all am -l messages in non-privileged account https://github.com/ivan-hc/AM/commit/1222f62f545bad0848c5771aecdd4e92fbeaee44

**Comment by Samueru-sama** [comment]
> just added a fix for all am -l messages in non-privileged account [1222f62](https://github.com/ivan-hc/AM/commit/1222f62f545bad0848c5771aecdd4e92fbeaee44)

Btw use this better for adding to the NOPASSWD list: 

`echo "$(whoami) ALL=NOPASSWD: /opt/*/AM-updater" | sudo tee -a /etc/sudoers`

There needs to be a check that the first echo isn't root, because otherwise whoami will not be the right user.

**Comment by ivan-hc** [comment]
@Samueru-sama Updating apps is not a problem for all admins.

The only issue is related to APP-MANAGER and modules.

Basically, once updated a module, it also changes owner/group.

**Comment by Samueru-sama** [comment]
This also works btw: 

`echo "$(whoami) ALL=NOPASSWD: /opt/*/AM-updater" | sudo EDITOR="tee -a" visudo`

>Updating apps is not a problem for all admins.

Yeah I mean letting the user update without password. 

>The only issue is related to APP-MANAGER and modules.

>Basically, once updated a module, it also changes owner/group.

And it doesn't happen with the other applications right?

**Comment by ivan-hc** [comment]
> And it doesn't happen with the other applications right?

Nope, until now... I'm playng ping-pong between an account and another, I've not faced issues (only the non-privileged user gets notification without updating anything)

**Comment by Samueru-sama** [comment]
> > And it doesn't happen with the other applications right?
> 
> Nope, until now... I'm playng ping-pong between an account and another, I've not faced issues (only the non-privileged user gets notification without updating anything)

That's weird. 

Something that comes to mind is making APP-MANAGER an appimage with the modules built in 👀 and `AM-updater` pulls a newer version of it instead.

Hopefully you can figure out a solution before I try that though lol.

**Comment by ivan-hc** [comment]
However, Ive done a test on a local file... now that we have another directory in cache, I'll test another approach

**Comment by Samueru-sama** [comment]
> However, Ive done a test on a local file... now that we have another directory in cache, I'll test another approach

Any updates?

**Comment by ivan-hc** [comment]
I've managed to update APP-MANAGER by downloading it in $CACHEDIR/am, set owner and group and then move

**Comment by Samueru-sama** [comment]
> I've managed to update APP-MANAGER by downloading it in $CACHEDIR/am, set owner and group and then move

Damn that was a fast response 👀

**Comment by ivan-hc** [comment]
@Samueru-sama see here https://github.com/ivan-hc/AM/commit/318b2c7d6d63cd5f15dd10566206d2e232da0d91

**Comment by ivan-hc** [comment]
please, remember me that I must switch this later https://github.com/ivan-hc/AM/commit/03b82971ce355c3a6e4d2b48accd3a7c8c85bedb

**Comment by ivan-hc** [comment]
now lets go testing... in my zone is 2:30 A.M., I think your zone is about 22:00/10:00 P.M., so keep testing if I fall asleep

**Comment by Samueru-sama** [comment]
> now lets go testing... in my zone is 2:30 A.M., I think your zone is about 22:00/10:00 P.M., so keep testing if I fall asleep

I get this error when doing `am -u` 

`chown: invalid group: ‘:sudo’ 6.6.2-2...`

Also I cannot do `sudo am -u` as it has the function that prevents that.

**Comment by ivan-hc** [comment]
this is what happens if sync is called by a non-privileged user

Istantanea_2024-04-26_02-37-49

I think it will be better to prevent normal users using update and sync

**Comment by ivan-hc** [comment]
> > now lets go testing... in my zone is 2:30 A.M., I think your zone is about 22:00/10:00 P.M., so keep testing if I fall asleep
> 
> I get this error when doing `am -u`
> 
> `chown: invalid group: ‘:sudo’ 6.6.2-2...`
> 
> Also I cannot do `sudo am -u` as it has the function that prevents that.

you must remove AM
```
am -R am
```
and then download the installer from dev
```
wget https://raw.githubusercontent.com/ivan-hc/AM/dev/INSTALL && chmod a+x ./INSTALL
```
open the file with a text editor and on top change the URL from main to dev, save and run
```
sudo ./INSTALL
```

**Comment by ivan-hc** [comment]
The update is gone well using the other admin

Istantanea_2024-04-26_02-44-53

**Comment by Samueru-sama** [comment]
> > > now lets go testing... in my zone is 2:30 A.M., I think your zone is about 22:00/10:00 P.M., so keep testing if I fall asleep
> > 
> > 
> > I get this error when doing `am -u`
> > `chown: invalid group: ‘:sudo’ 6.6.2-2...`
> > Also I cannot do `sudo am -u` as it has the function that prevents that.
> 
> you must remove AM
> 
> ```
> am -R am
> ```
> 
> and then download the installer from dev
> 
> ```
> wget https://raw.githubusercontent.com/ivan-hc/AM/dev/INSTALL && chmod a+x ./INSTALL
> ```
> 
> open the file with a text editor and on top change the URL from main to dev, save and run
> 
> ```
> sudo ./INSTALL
> ```

Ok but this made am be owned by me instead of root?

**Comment by ivan-hc** [comment]
And back to me again, other admin

Istantanea_2024-04-26_02-47-52

no issue here

**Comment by ivan-hc** [comment]
> Ok but this made am be owned by me instead of root?

The first owner should be root, and in my tests I've updated and I become the owner, then I re-updated with another admin and him become the owner... and back again, updated by my user and I become owner again

for all the abow, the group "sudo" is always RW

**Comment by ivan-hc** [comment]
Now we need to add a filter to update and sync, that are useless for non-sudo users. Would you like to provide one?

**Comment by Samueru-sama** [comment]
> Now we need to add a filter to update and sync, that are useless for non-sudo users.
> 
> Would you like to provide one (in APP-MANAGER)?

You better do it because I'm a little confused now. lol. 

Will the `echo "$(whoami) ALL=NOPASSWD: /opt/*/AM-updater" | sudo EDITOR="tee -a" visudo` to update without password be needed?

**Comment by ivan-hc** [comment]
@Samueru-sama is this ok as a message to prevent unprivileged users of using some options?

```
guest is not in the sudoers file. This incident will be reported.
```

**Comment by Samueru-sama** [comment]
> @Samueru-sama is this ok as a message to prevent unprivileged users of using some options?
> 
> ```
> guest is not in the sudoers file. This incident will be reported.
> ```

It's ok. 

>nope

It's a shame because with the trick above even guest should be able to update AM even when it is owned by root.

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/commit/3ab26c6e9ff2e8f9999508f18de4b3b46b33a850

> It's a shame because with the trick above even guest should be able to update AM even when it is owned by root.

Nope... and I'm still looking the english version of the agent Smith in the first Matrix saying that humans should not do the job of a machine, in the first shene

**Comment by ivan-hc** [comment]
> It's a shame because with the trick above even guest should be able to update AM even when it is owned by root.

oh-no

ways better

**Comment by ivan-hc** [comment]
@Samueru-sama is this OK? Should I merge to main?

**Comment by Samueru-sama** [comment]
> @Samueru-sama is this OK? Should I merge to main?

If it works and fixes the issues that the users were having recently, then yeah. 

(I haven't had issues on my end if you wonder)

**Comment by ivan-hc** [comment]
@Samueru-sama hey, I'm here, tell me. What should I do?

**Comment by Samueru-sama** [comment]
> @Samueru-sama hey, I'm here, tell me. What should I do?

RIGHT NOW, would be to add this to `./INSTALL`

`sudo usermod -aG root $(who | awk '{print $1}')`

That adds the user to the root group. 

Later on we to need make a better group for this, like in the case of gamemode where you can see that it makes a gamemode group, `am` can make a am group.

**Comment by ivan-hc** [comment]
Would you like to PR?

**Comment by Samueru-sama** [comment]
> Would you like to PR?

done

**Comment by ivan-hc** [comment]
> > Would you like to PR?
> 
> done

OK, good night :sleeping: :zzz:

**Pull request merged**
