### PR TITLE
functions: APP-MANAGER how to

### PR DESCRIPTION
**Pull request by zen0bit**
## This PR will hopefully teach you a bit about functions.
Look at each commits how they goes..
Then you will maybe know bit more what I have in my mind...

Feel free to do anything with it.
If will be merged in this state or modified, or not merged is up to you.

PS: I wanna push changes that add, improve features. But i have to know what I am dealing with. This structure will make script more readable for anyone. And once you get familiar with it, for you also..
You will no more repeat yourself!

You will just reuse same functions again and again
AM will be more robust and modular.

And any future change will be easier to implement.
For that you just have to:
1. copy old function
2. rename it
3. do desired changes
4. Test
5. You can go back anytime... (just rename calling string back to previous one)
6. And leave not yet working function in script for later improvement. Just don't call it.

# Let's make AM awesome

### CODE REVIEW

**Comment by zen0bit** [comment]
This will explain to you: how and why I am doing it

Any improvement/change yiu want. I can make, just tell me and will be improved as you like...

**Comment by Samueru-sama** [comment]
Oh no this is going to conflict with the changes I made to APP-MANAGER

**Comment by zen0bit** [comment]
> Oh no this is going to conflict with the changes I made to APP-MANAGER

rebase shouldn't be big deal
work on changes against dev as now
I can help with rebase if needed

Will see if this will be merged...

**Comment by Samueru-sama** [comment]
> work on changes against dev as now

I intentionally used main as base because of the changes Ivan did the last two days regarding the user permissions to dev.

**Comment by ivan-hc** [comment]
@zen0bit your writing is good, but you don't take into account that some variables (like the one you modified, _online_check) are also used in the modules, even if I previously grouped them into a single function. You worry about the drafting but without testing the changes on your machine, and I already told you this months ago.

You want too much to make this CLI compatible with the work of the Elite developers, without taking into consideration that the one who tests it over and over again, with every change that you all make (without giving me a break, by the way) is me, the creator , who wrote this CLI as a hobby and without such a technical background as yours.

I use it on my PC, personally, both as AM and as AppMan, and it pisses me off when something doesn't work because you decided to change something not to make it work but "to give it a touch of style". This is the story of when I told you that I was a bricklayer and mixed lime and cement. Yours is a beautiful castle, but it's a house of cards. I don't care about towers, dungeons and prisons if you break the front door like this!

We ended up changing the style 4-5 times in a few days, because you want to play a tug of war with me. You took this project so seriously that you made it yours, literally, not to mention that this project is called ivan-hc/AM, not zenobit/AM, and if something doesn't work (especially in this period when I'm contacting publishers left and right for some review) the responsibility falls on me, and I make a fool of myself because of your "uncalculated" changes.

I would like to write new code, as a "hobby", but I can't if you, @zenobit, continue to provide me with material to test on my virtual machines. I can not make it. My hands are tied. We are two coaches who tell the team two different things, and it is more than right that this remains a series B or C project. Do you want to advance? I only see relegations with your way of working and thinking.

One above all, I put the _no_sudo function at the top just because I tested it, and it finally works as it should on "AM" and AppMan. I got there after months or years... and you move it again, less than 12 hours after my changes.

How do you think I can carry out a project in this state? Should I permanently leave github at this point? No, because I'm thinking about doing it now. You're not giving me a break, @zenobit, and I want to understand that you initially pushed for me to add awesome features, and I thank you... but I would never have been able to do that if my tools had been moved elsewhere than back to where I left them.

**Pull request closed without merging**
