### PR TITLE
😇

### PR DESCRIPTION
**Pull request by Samueru-sama**
There is no silencing anymore, it is up to the function now. 

(I don't know why I get conflicts).

### CODE REVIEW

**Comment by ivan-hc** [comment]
now youve no more them

**Comment by Samueru-sama** [comment]
> now youve no more them

Weren't you asleep kek

**Comment by ivan-hc** [comment]
are you using git to made the changes? me not

**Comment by Samueru-sama** [comment]
> are you using git to made the changes? me not

Used github interface, bro the other day I tried to use git to merge the patches from a fork of zenity into my own and it went horrid 💀

I ended up having to download the fork and manually patch and upload each fle.

Thanks for merging this one because otherwise I would have needed to delete and create the fork again lol.

**Comment by ivan-hc** [comment]
now go testing my module and let me know if you face problems, see you later

SPOILER: no issue here

Istantanea_2024-04-22_01-49-44

**Comment by ivan-hc** [comment]
ciao

**Pull request merged**
