### PR TITLE
Unified deadbeef, updates some apps and added more applications, changed the template

### PR DESCRIPTION
**Pull request by Samueru-sama**
That was tricky but it worked out well.

### CODE REVIEW

**Comment by Samueru-sama** [comment]
I updated the archive because I discovered that there is a 3rd possibility for the mv. 

* The first is that if it is a lone directory.

* The second is if it is a lone file.

* The 3rd one (this one) is when there is multiple files without directory, that causes `if [ -d ./tmp/* ]` to fail with a too many arguments error!. 

I changed the else condition to this, which takes into account that there can be multiple files without directory in tmp: 

`./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./`

**Comment by Samueru-sama** [comment]
Closes #701

**Comment by Samueru-sama** [comment]
@ivan-hc I actually removed the old [deadbeef](https://github.com/ivan-hc/AM/pull/702/commits/4b540e23440a445d865e37872fe7f4d0ee3dfe33) but looks like I copied the wrong list when adding the other apps that caused them to be back.

**Comment by ivan-hc** [comment]
@Samueru-sama don't worry, I've solved :+1:

**Pull request merged**
