### PR TITLE
Update pulseview entry

### PR DESCRIPTION
**Pull request by nazdridoy**

### CODE REVIEW

**Comment by ivan-hc** [comment]
Hi @nazdridoy why updating the description? The rule of 80 characters has been broken from months.

**Comment by nazdridoy** [comment]
previous description was way too verbose and didn't serve any purpose
.

**Comment by ivan-hc** [comment]
its ok, don't worry... the more we have keywords, the more it can appear in other categories of the catalogue

Istantanea_2024-12-15_06-50-22

we have more than 20 pages of categories on the catalogue https://portable-linux-apps.github.io

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/82c178a80bf3e8250ebe99124ab8fe111f6205c7

**Comment by nazdridoy** [comment]
i don't think those words(removed) are relevant keyword. if you want to keep these i can close this PR.

**Comment by ivan-hc** [comment]
I'm not merging the request yet because I'm permanently on the "dev" branch lately, and to update the list I would have to resync with "main" which would be a forward commit. Too complicated to explain.

I'll merge your PR when I release version 9.4, if you really want... but I repeat, I'm fine with the first description you wrote. It's nicer. Just don't add "for Windows, Mac and Linux", or you'll find it plastered on the "WINE" or "Games" category... and I don't think that's the case :laughing: 

Thank you for your contribution.

**Comment by nazdridoy** [comment]
its not that important. i think first description can work just fine.

**Pull request closed without merging**
