### PR TITLE
Add android-tools-appimage. 

### PR DESCRIPTION
**Pull request by Samueru-sama**
I was able to turn the released binaries for android platform tools into an appimage, and it works, (AppRun determines which binary to use since platform tools contains several). https://github.com/Samueru-sama/android-tools-AppImage

test: 
test

~~I set the desktop entry to hidden, because for some reason on my end it opens and then closes unlike other CLI appimages where the desktop entry does work. I don't know why~~

edit: Fixed that issue.

### CODE REVIEW

**Comment by ivan-hc** [comment]
Great, I like it!

Please, add also a entry in the x86_64-list file (if you can, try to fit in 80 characters or the message will me truncated)

**Comment by ivan-hc** [comment]
also, if you prefer, try to give it a shorter name (maybe without "-appimage", just "android-tools", so you add "AppImage" only in the description)

**Comment by ivan-hc** [comment]
For example:
```
◆ android-tools : AppImage for the Android Debug Bridge tools (adb, fastboot...)
```

**Comment by ivan-hc** [comment]
Just noticed fro your `am -f` that my Steam AppImage is still Type2, I'm going updating it. Thanks.

**Comment by Samueru-sama** [comment]
Alright that is done, I was able to modify the appimage to pull the installer from the android-udev-rules repo if the android-udev rules are missing and it also works. 

image

**Comment by ivan-hc** [comment]
since you've changed the name in the list, you should do the same in the list. I did it for you https://github.com/ivan-hc/AM/commit/bd257f2e2232cdbe5d6262a2e5bde8c9beaf12ca

**Comment by Samueru-sama** [comment]
> since you've changed the name in the list, you should do the same in the list. I did it for you [bd257f2](https://github.com/ivan-hc/AM/commit/bd257f2e2232cdbe5d6262a2e5bde8c9beaf12ca)

Yeah I noticed that, but I also noticed that adb shows up in the list of searchable apps as a package that points to platform-tools so I didn't think it was a problem.

**Comment by ivan-hc** [comment]
> > since you've changed the name in the list, you should do the same in the list. I did it for you [bd257f2](https://github.com/ivan-hc/AM/commit/bd257f2e2232cdbe5d6262a2e5bde8c9beaf12ca)
> 
> Yeah I noticed that, but I also noticed that adb shows up in the list of searchable apps as a package that points to platform-tools so I didn't think it was a problem.

Yes, I've some meta-scripts that can redirect to other main scripts

for example, "kdegames" has about 40 metascripts (kpat, palapeli, bomber, knights... all kde games)

**Comment by ivan-hc** [comment]
> > > since you've changed the name in the list, you should do the same in the list. I did it for you [bd257f2](https://github.com/ivan-hc/AM/commit/bd257f2e2232cdbe5d6262a2e5bde8c9beaf12ca)
> > 
> > 
> > Yeah I noticed that, but I also noticed that adb shows up in the list of searchable apps as a package that points to platform-tools so I didn't think it was a problem.
> 
> Yes, I've some meta-scripts that can redirect to other main scripts
> 
> for example, "kdegames" has about 40 metascripts (kpat, palapeli, bomber, knights... all kde games)

@Samueru-sama Since each KDE application requires hundreds of MB of KDE core files to run, it was not cost effective to create individual apps. A Kpat AppImage can range from 150MB and up, so it's best to combine the entire suite of games into a single AppImage.

The same is for platform-tools, nodejs and kdeutils

**Comment by ivan-hc** [comment]
KDE is a strange animal, I can merge the entire DE into one big AppImage.

**Comment by zen0bit** [comment]
Why not do that? Can be done with other DEs, WMs?

**Comment by ivan-hc** [comment]
> Why not do that? Can be done with other DEs, WMs?

Of course, an AppImage can be also used to load a whole DE to be loaded at login.

I just get bored of doing it.

**Comment by zen0bit** [comment]
Can you package hyprland + nwg if you get bored?

[nwg-iso](https://github.com/nwg-piotr/nwg-iso)
It's standart Arch based (Just to show nwg on sway or hyprland)

**Comment by ivan-hc** [comment]
> Can you package hyprland + nwg if you get bored?
> 
> [nwg-iso](https://github.com/nwg-piotr/nwg-iso) It's standart Arch based (Just to show nwg on sway or hyprland) 😇

@zen0bit I would gladly do it for you, but in reality I don't even know what it is. At most I can help you in using [Archimage](https://github.com/ivan-hc/ArchImage). Contact me privately too, I'll give you some guidance if you have any questions, and I'll see what to do.

**Pull request merged**
