### PR TITLE
amtui

### PR DESCRIPTION
**Pull request by zen0bit**
I created TUI for appman/am, but not yet show progress

Preview version

Still lot to do, but TUI is working

Do you like it?

require gum installed!

### CODE REVIEW

**Comment by ivan-hc** [comment]
Can you sent a video? I've not GUM installed.

**Comment by zen0bit** [comment]
Later..

Script will try to install gum on different distros, or build with go from source..

**Comment by ivan-hc** [comment]
It seems not the best approach.

Why not to bundle GUM into an AppImage?

**Comment by zen0bit** [comment]
> It seems not the best approach.
> 
> Why not to bundle GUM into an AppImage?

why not?

You are AppImage master here..:

**Comment by ivan-hc** [comment]
> You are AppImage master here..

ahahahah... no -_-

I only use workarounds.

Maybe if you publish this on AUR, I can try to build an Archimage.

**Comment by zen0bit** [comment]
Short preview video but is to big to upload here...
so [youtube](https://youtu.be/82JquMgpT3w)

Recorded on steamdeck

**Pull request closed without merging**
