### PR TITLE
Update installation scripts: part 1

### PR DESCRIPTION
**Pull request by ivan-hc**
The first commit is about all portable apps from github, that were the ones we need to test the more.

NOTE, only portable apps, next commits are all about AppImages, that are the easier to update like this.

### CODE REVIEW

**Comment by ivan-hc** [comment]
1457 installation scripts left

**Comment by ivan-hc** [comment]
1409 left

**Comment by ivan-hc** [comment]
my work here is slowed down by reaching the Github API call limit

left 1355

**Comment by ivan-hc** [comment]
1300

**Comment by Samueru-sama** [comment]
Omg

**Comment by ivan-hc** [comment]
1249

**Comment by ivan-hc** [comment]
1198

**Pull request merged**
