### PR TITLE
New appimage template

### PR DESCRIPTION
**Pull request by Samueru-sama**
Continuation of #639

### CODE REVIEW

**Comment by Samueru-sama** [comment]
>For example, "libreoffice" does not have this type of support, also because its URL is uniform, has no version numbers and never changes... and all "wine" are already Type3. They therefore do not need this change.

Yeah I was changing the libreoffice script to use the new updater method with the unified zsync + version and I noticed that it wouldn't work because libreoffice has a fixed url lol 

>As for me, I'll have to settle for keeping Libreoffice Type2, with all its additional 30MB 😞

I live in a shithole and I get symmetrical [gigabit ](https://www.speedtest.net/result/16359152384.png) speeds. Don't tell me your internet is worse lol

However I will have to also keep libreoffice type2 since it is impossible to update it manually.

**Comment by ivan-hc** [comment]
> I live in a shithole and I get symmetrical [gigabit ](https://www.speedtest.net/result/16359152384.png) speeds. Don't tell me your internet is worse lol
> 
> However I will have to also keep libreoffice type2 since it is impossible to update it manually.

I'd like to contact the packagers of Libreoffice and Kdenlive for this. Any idea?

**Comment by Samueru-sama** [comment]
> > I live in a shithole and I get symmetrical [gigabit ](https://www.speedtest.net/result/16359152384.png) speeds. Don't tell me your internet is worse lol
> > However I will have to also keep libreoffice type2 since it is impossible to update it manually.
> 
> I'd like to contact the packagers of Libreoffice and Kdenlive for this. Any idea?

What happened with librewolf btw?

If you will contact libreoffice and kde I assume it is to tell them to update to the new appimagetool.

**Comment by ivan-hc** [comment]
> What happened with librewolf btw?

Do you believe me if I tell you that I have strong amnesia about it? I don't remember at what point I contacted him, asking him to provide a direct link to "AM". It's been a long time, and I've talked to tons of developers since then. I absolutely don't remember where we spoke from. Maybe on Reddit.

**Comment by ivan-hc** [comment]
Found it https://www.reddit.com/r/LibreWolf/comments/pkm4lc/tag_latest_for_the_appimage_releases/ using my old account

**Comment by Samueru-sama** [comment]
> Found it https://www.reddit.com/r/LibreWolf/comments/pkm4lc/tag_latest_for_the_appimage_releases/ using my old account

That account hasn't been active in 2 years 😕

**Comment by Samueru-sama** [comment]
@ivan-hc Changed template.am again. Is it ok now?

**Comment by ivan-hc** [comment]
> @ivan-hc Changed template.am again. Is it ok now?

Yes, but since you are changing "AM-SAMPLE-appimage", you need to know to what height you moved the line to be changed. If you put it on line 15, then this change you made is fine.

**Comment by Samueru-sama** [comment]
> > @ivan-hc Changed template.am again. Is it ok now?
> 
> Yes, but since you are changing "AM-SAMPLE-appimage", you need to know to what height you moved the line to be changed. If you put it on line 15, then this change you made is fine.

Yes it is on line 15.

**Comment by ivan-hc** [comment]
Can I merge now? Is there something left?

**Comment by Samueru-sama** [comment]
> Can I merge now? Is there something left?

I have to yet test the template being generated with `template.am`. Which uh I don't know how to do since template.am will pull from the main repo 😞

Also zsync hasn't been tested, _but zsync was broken_ before as the wildcards where inside quotes anyway. can't get worse 😅

**Comment by Samueru-sama** [comment]
> I merge in "dev", so you can test it using `appman --devmode-enable` or `am --devmode-enable`

Just tested making a cpu-x appimage. Which has a zsync file. It works! (sort of).

cpu-x is another of those rare appimages where .DirIcon is a symlink to another symlink lol. So it just needed a small fix of repeating the last check. 

* **However there is a bigger problem**

The zsync in cpu-x is broken. And the problem isn't the template. It is also broken if I use the current template that it has: 

image

I think zsync doesn't like that the name of cpu-x was changed? 

Once again this is with the current old cpu-x script. Nothing to do with this recent change. I think I need to contact the dev of cpu-x at this point.

**Pull request merged**
