### PR TITLE
Fix superfile

### PR DESCRIPTION
**Pull request by Samueru-sama**
This is one of those rare apps where the application after being extracted is inside two directories.

### CODE REVIEW

**Comment by ivan-hc** [comment]
you can't imagine how many times I've had problems with Mercury/Thorium, for the exact same reason... but that's because the developer doesn't have a linear method for doing things

**Comment by Samueru-sama** [comment]
With this you can merge the updated apps to main. (What I did was update the version 3 apps to version 3.5 + add the sed trick to all of them)

The only other app that was version 3 template that had a `/*/*/*` was freshfetch, but that one already has the correct mv, this superfile slipped thru.

**Comment by Samueru-sama** [comment]
btw I tested removing the entire silencing part and testing the version 3.5 scripts to see if there is something: 

image

I tested `polybar` (appimage) and `zramen` (archive) and both are silent. 

image


So I think something can be put that if the script contains the word "VERSION 3.5" it skips the silencing part.

**Comment by ivan-hc** [comment]
like this?
```
# Patch to apply to installation scripts
function _install_common_patch() {
	if ! grep -q -- "--debug" "$AMCACHEDIR"/install-args; then
		# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
		if wget --version | head -1 | grep -q ' 1.'; then
			sed -i "s#wget #wget -q --no-verbose --show-progress --progress=bar #g" ./"$arg"
		fi
		# Silence "mv", "sed" errors and "squashfs-root" messages
		if ! grep -q "VERSION 3.5" ./"$arg"; then
			sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./"$arg"
			sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
			sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
			sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
			sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
		fi
	fi
	sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./"$arg"
}
```

**Comment by Samueru-sama** [comment]
> like this?
> 
> ```
> # Patch to apply to installation scripts
> function _install_common_patch() {
> 	if ! grep -q -- "--debug" "$AMCACHEDIR"/install-args; then
> 		# Patch "wget" (version 1.x) to have a progress bar and fix errors when applying patches
> 		if wget --version | head -1 | grep -q ' 1.'; then
> 			sed -i "s#wget #wget -q --no-verbose --show-progress --progress=bar #g" ./"$arg"
> 		fi
> 		# Silence "mv", "sed" errors and "squashfs-root" messages
> 		if ! grep -q "VERSION 3.5" ./"$arg"; then
> 			sed -i 's/ \&& mv/ | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv/g' ./"$arg"
> 			sed -i '/appimage-extract/ s/$/ 2>\&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
> 			sed -i '/^mv / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
> 			sed -i '/^sed / s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
> 			sed -i '/squashfs-root/ s/$/ 2>\/dev\/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"/' ./"$arg"
> 		fi
> 	fi
> 	sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./"$arg"
> }
> ```

wait nvm: 

image

polybar doesn't get its .desktop extracted because it doesnt get used lol. 

Tomorrow I will very likely update all the 3.5 scripts to fix that small issue, it should just be appending a `1>/dev/null` after each `--appimage-extract`

**Comment by ivan-hc** [comment]
:man_facepalming:

**Comment by Samueru-sama** [comment]
> 🤦‍♂️

It isn't a big deal lol. 

image

It's just sed all instances of `--appimage-extract "$LINKPATH"` to `--appimage-extract "$LINKPATH" 1>/dev/null` and it's done.

**Comment by Samueru-sama** [comment]
> 🤦‍♂️

btw discord, I have some off topic news.

**Pull request merged**
