### PR TITLE
Update nvim, add nvim-nightly, update cpu-x

### LINKED ISSUE #654: trouble with AppImages on *ubuntu and a stability concern
- FYI, I'm on the lastest Kubuntu, and AppImages using bwrap are defeated by apparmor. But an apparmor rule is not the fix .. instead: https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces.  Anyhow, it seems likely this will trip up many others; to help, perhaps mentioning in the AppImage troubleshooting section?
- I want the latest stable/released nvim (v10), but AM gave me: NVIM v0.11.0-dev-211+g37bf4c572.  Seriously, I almost never want to be on the "night build" of any project.  So, I ran "--force-latest nvim", it said, "UPDATING NVIM", then "◆ NVIM is updated, 120 seconds elapsed!".   I'm not sure I'm that patient of a person to go thru this on every such app (or wish to remember to always check).   Is there a "I want latest stable always" setting instead of repairing (every?) similar install?

This looks like a great project and I'll continue to kick the tires, but philosophical differences on stability may prevent me from sticking with it for the long haul.  Cheers.

### PR DESCRIPTION
**Pull request by Samueru-sama**
**Partially** fixes #654

Btw nvim only releases an appimage but they don't indicate that it is `x86_64` so this will likely break in the future if they ever add a nvim appimage for other architecture. 

EDIT: 

I also added the nightly build. However the description goes over the 80 character limit, If this is a problem let me know.

### CODE REVIEW

**Comment by Samueru-sama** [comment]
Also updated cpu-x to use the versioned releases instead of the continuous one. That way the updates without zsync work.

**Comment by ivan-hc** [comment]
> Btw nvim only releases an appimage but they don't indicate that it is `x86_64` so this will likely break in the future if they ever add a nvim appimage for other architecture.

If so, provide a list of what NOT to include in the search, as in the old script:
```
version=$(curl -Ls https://api.github.com/repos/neovim/neovim/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*releases.*nvim.*mage$' | grep -v "nightly\|arm64\|aarch64\|i686\|i386" | head -1)
```

**Comment by ivan-hc** [comment]
To download the nyghtly one instead
```
version=$(curl -Ls https://api.github.com/repos/neovim/neovim/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*releases.*nvim.*mage$' | grep -v "arm64\|aarch64\|i686\|i386" | grep -i nightly | head -1)
```
add "-i" to `grep`, and `grep -v "arm64\|aarch64\|i686\|i386"` to prevent detecting future non x86_64/amd64 builds

**Comment by ivan-hc** [comment]
PS: coud you share your .md files created with the apps? It sawes me time when I must update the website

**Comment by Samueru-sama** [comment]
> Are you using git? I'm on Firefox.

I'm on brave. I was testing the changes before adding them: 

image

**Comment by Samueru-sama** [comment]
> PS: coud you share your .md files created with the apps? It sawes me time when I must update the website

[cpu-x.md](https://github.com/user-attachments/files/15795814/cpu-x.md)
[nvim.md](https://github.com/user-attachments/files/15795815/nvim.md)

I don't have one for nvim nightly 🤔

**Comment by ivan-hc** [comment]
I'll copy the one for nvim and rename it by adding that its the nightly :+1:

**Comment by ivan-hc** [comment]
@Samueru-sama just noticed that the source of cpu-x is changed https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/b31e7ed10c69d9c1f710f4e99a5dc4738056397c

**Comment by Samueru-sama** [comment]
> @Samueru-sama just noticed that the source of cpu-x is changed [Portable-Linux-Apps/Portable-Linux-Apps.github.io@b31e7ed](https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/b31e7ed10c69d9c1f710f4e99a5dc4738056397c)

That's weird, however if you try to go to https://github.com/X0rg/CPU-X it redirect to the current one. 

I really don't if they changed their username or cpu-x was started by someone else. 

But the unicorn guy has actually contributed a lot to appimages, they created linuxdeploy-gtk3 iirc. 

I mentioned about updating cpu-x to the new Go appimagetool at the issue I opened recently, and they either didn't read that or just ignore it 😞

**Pull request merged**
