### PR TITLE
fix(dbgate): download the incorrect appimage file and code improvements

### PR DESCRIPTION
**Pull request by Wesley-AlvesRolim**
## Refactors
- I change the way that extract icons to more readeable code using for loops, in this case my eyes don't get so tired. Maybe this change can be used in another scripts.
- Because of my preference, the script will ignore the beta versions.
- I removed the old lines 75 and 76, because is unnecessary for this case.

## Fixes
- The appimage name in [DbGate repository](https://github.com/dbgate/dbgate/releases/) uses the underscore (_). The problem is that the `-w` flag in the `version` variable will match arm64, for example, and download it.
- In lines 103-107, I am using the icon extension, because in my system menu the icon not appear.

### CODE REVIEW

**Comment by ivan-hc** [comment]
You should test this on AppMan too before uploading changes.

The installation scripts are ment to be patched if the CLI is used as AppMan, and not AM.

For example, the .desktop file is still in my local directory and has not been patched. This is why the "$CHANGEXEC" variable.

PS: try to create it again usint the -t option and the new template that instead uses a different approach.

**Comment by ivan-hc** [comment]
To have a latest version for x86_64 its enough to specify "x86_64" as a keyword to be included and to add manually "/latest" not to download a beta release
```
version=$(curl -Ls https://api.github.com/repos/dbgate/dbgate/releases/latest | jq '.' | grep browser_download_url | grep -i x86_64  | grep -i appimage | cut -d '"' -f 4 | head -1)
```

@Wesley-AlvesRolim this is the script based on the new template, compatible with both AM and AppMan

```
#!/bin/sh

APP=dbgate
SITE="dbgate/dbgate"

# CREATE DIRECTORIES
if [ -z "$APP" ]; then exit 1; fi
mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1

# ADD THE REMOVER
echo "#!/bin/sh
rm -f /usr/share/applications/AM-$APP.desktop /usr/local/bin/$APP
rm -R -f /opt/$APP" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP
# $version is also used for updates

version=$(curl -Ls https://api.github.com/repos/dbgate/dbgate/releases/latest | jq '.' | grep browser_download_url | grep -i x86_64  | grep -i appimage | cut -d '"' -f 4 | head -1)
wget "$version"
wget "$version.zsync" 2> /dev/null
echo "$version" >> /opt/$APP/version
# Use tar fx ./*tar* for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
mv ./tmp/*.zsync ./"$APP".zsync 2> /dev/null
chmod a+x "/opt/$APP/$APP"
rm -R -f ./tmp

# LINK
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
APP=dbgate
SITE="dbgate/dbgate"
if [ -z "$APP" ]; then exit 1; fi
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/dbgate/dbgate/releases/latest | jq '.' | grep browser_download_url | grep -i x86_64  | grep -i appimage | cut -d '"' -f 4 | head -1)
if test -f "/opt/$APP/*.zsync"; then
	mkdir "/opt/$APP/tmp"
	cd "/opt/$APP/tmp" || exit 1
	wget "$version.zsync" 2> /dev/null
	cd ..
	mv ./tmp/*.zsync ./"$APP".zsync
	rm -R -f ./tmp
	zsync "/opt/$APP/$APP.zsync"
	rm -R -f "/opt/$APP/*zs-old" "/opt/$APP/*.part"
	chmod a+x /opt/$APP/$APP
	if [ "$version" != "$version0" ]; then
		rm -f /opt/$APP/version
		echo "$version" >> /opt/$APP/version
	fi
else
	if [ "$version" = "$version0" ]; then
		echo "Update not needed!" && exit 0
	else
		notify-send "A new version of $APP is available, please wait"
		mkdir "/opt/$APP/tmp"
		cd "/opt/$APP/tmp" || exit 1
		wget $version
		if ls . | grep mage; then
			
			cd ..
			
	  		if test -f ./tmp/*mage; then rm ./version
	  		fi
	  		echo "$version" >> ./version
	  		mv --backup=t ./tmp/* ./"$APP"
	  		chmod a+x "/opt/$APP/$APP"
	  		rm -R -f ./tmp ./*~
		fi
		notify-send "$APP is updated!"
	fi
fi
EOF
chmod a+x "/opt/$APP/AM-updater"

# LAUNCHER & ICON
cd "/opt/$APP" || exit 1
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract share/applications/*.desktop 1>/dev/null && mv ./squashfs-root/share/applications/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract usr/share/applications/*.desktop 1>/dev/null && mv ./squashfs-root/usr/share/applications/*.desktop ./"$APP".desktop
if [ -L ./DirIcon ]; then
	LINKPATH=$(readlink ./DirIcon)
	./"$APP" --appimage-extract "$LINKPATH" && mv ./squashfs-root/"$LINKPATH" ./DirIcon
fi
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/share/applications/AM-"$APP".desktop && mv ./DirIcon ./icons/"$APP" 2>/dev/null
rm -R -f ./squashfs-root
```

**Comment by ivan-hc** [comment]
give it a try

**Comment by Wesley-AlvesRolim** [comment]
:open_mouth:
I missed so many changes :sweat_smile: 
But i will study this code

**Pull request merged**
