### PR TITLE
Refactor APP-Manager script (1 / many) 

### PR DESCRIPTION
**Pull request by nazdridoy**
This pull request refactors the _appman function to improve its readability and maintainability. The changes include breaking down the function into smaller helper functions, adding comments for clarity, and improving variable naming. These changes make the code easier to understand and maintain in the future.

Fix: syntax error

### CODE REVIEW

**Comment by ivan-hc** [comment]
I'm testing your changes... and no command works anymore.

https://github.com/ivan-hc/AM/assets/88724353/fc994a32-3815-4b75-970d-8fdc7163a1bc

**Comment by ivan-hc** [comment]
also `-s` does not work anymore, so I can't restore my script again (I've to do it manually).

**Comment by ivan-hc** [comment]
good

**Comment by ivan-hc** [comment]
@nazdridoy the next time, use TABs, not Spaces, like this https://github.com/ivan-hc/AM/commit/f1da18ca00099dc41f3dbd95dbd8b095ac388a60

**Comment by ivan-hc** [comment]
@nazdridoy just another thing... the fact that the path autocomplete itself is AMazing! Thank you!

**Comment by nazdridoy** [comment]
>  next time, use TABs, not Spaces

tab is bad. breaks so many things for me... besides tab=4space is kindof a standerd...

**Comment by ivan-hc** [comment]
Because it's a standardized space, it aligns with everything else. I have very lunchy functions in the script, with TAB I'm sure, for example, where an `if`/`fi` function ends up.

**Comment by nazdridoy** [comment]
> Because it's a standardized space, it aligns with everything else. I have very long functions in the script, with TAB I'm sure, for example, where an `if`/`fi` function ends up.

Wouldn't it be better if we replaced tabs with 4 spaces? To me, tabs are the devil. In fact, I believe using spaces instead of tabs will  make formatting less likely to break...

**Comment by nazdridoy** [comment]
> > Because it's a standardized space, it aligns with everything else. I have very long functions in the script, with TAB I'm sure, for example, where an `if`/`fi` function ends up.
> 
> Wouldn't it be better if we replaced tabs with 4 spaces? To me, tabs are the devil. In fact, I believe using spaces instead of tabs will make formatting less likely to break...

many IDEs let you set tab=4spaces

**Comment by nazdridoy** [comment]
> @nazdridoy the next time, use TABs, not Spaces, like this [f1da18c](https://github.com/ivan-hc/AM/commit/f1da18ca00099dc41f3dbd95dbd8b095ac388a60)

now that i think about it, maybe you are talking about indentation?

**Comment by ivan-hc** [comment]
I'm talking about speed, practicality... I don't have to think about making 4 spaces at a time, just one button is enough.

**Pull request merged**
