### PR TITLE
Optimizations to the files module (and display total size as well).

### PR DESCRIPTION
**Pull request by Samueru-sama**
I know the title sends chills down your spine @ivan-hc 😆 but I did test this it with **appman** and it works: 

image

-------------------------------

**However** I'm not sure if the spaces that I added for `Total size` is the right way of doing this, as I don't know if when using a different font this messes the order.

### CODE REVIEW

**Comment by ivan-hc** [comment]
> You can also make it display the total size in the first paragraph instead if you think that way is better.

Nope, its OK at the footer. Thanks

**Comment by ivan-hc** [comment]
Why have you converted it in SHELL?

**Comment by Samueru-sama** [comment]
> Why have you converted it in SHELL?

What do you mean? That I changed `bash` for `sh`? That's something that I hope all of am could eventually be converted to.

I normally only use bash when there is a feature that can only be used in bash, like array filtering, since that wasn't being used here I changed it to sh. 

When I tested the script I also tested that change and made sure that dash is indeed my sh.

**Comment by ivan-hc** [comment]
This is amazing, thank you.

What if I change
```
echo "--------------------------------------------------------------------------------"
echo "- Total Size:							      $(du -sh "$APPSPATH" | awk '{print $1}' | sed 's/.$/   &/; s/$/iB/')"
echo ""
```
with
```
echo -e "\n TOTAL SIZE: $(du -sh "$APPSPATH" | awk '{print $1}' | sed 's/.$/ &/; s/$/iB/') of disk space in use\n"
```
to have

Istantanea_2024-06-08_23-03-21


?

**Comment by ivan-hc** [comment]
Don't worry, I'll do it. Since it's your idea, I just wanted to propose this change of style.

**Pull request merged**
