### PR TITLE
add use_functions for aguments + small style fix

### PR DESCRIPTION
**Pull request by zen0bit**
I am not sure what's your default editor config (using spaces somewhere but mostly tabs)
Maybe we can set in scripts?

something like `# vim:tabstop=4:shiftwidth=4:expandtab`?

It should go on last line of script

### CODE REVIEW

**Comment by zen0bit** [comment]
How you debug your script?

I can't use `bash -x` on it...

**Comment by ivan-hc** [comment]
nothing works, apart the single options

Istantanea_2024-04-18_11-16-31

**Comment by ivan-hc** [comment]
> How you debug your script?
> 
> I can't use `bash -x` on it...

by testing the options one by one, on my PC

**Comment by zen0bit** [comment]
if i want use bash -x am -h

no matter what
ask me to create new config for appman
I think AppMan/am should be totaly included. I see only difference in path and sudo
Both could be taked care in installation procces of apps itself
so am will run without sudo until sudo is rezlly needed than ask for it if not in appman mode

**Comment by Samueru-sama** [comment]
Why does DATADIR have two tab spaces instead of just one?

image

**Comment by zen0bit** [comment]
I forgot pass the arguments :stuck_out_tongue_winking_eye:

**Comment by zen0bit** [comment]
Or you have different configuration? tell us...

**Comment by zen0bit** [comment]
Program behavior has not changed

**Comment by ivan-hc** [comment]
@zen0bit all works well, apart two things:
- your beloved `-f` now has options, so add a "$@" to made them work;
- this is a refactoring, you don't need to change the version, at least not with a "dot" (max 6.6-1)

The way I intend new versions:
- `N` is a release with radical and deep changes (as they were AM and AppMan merged in one, v5, and modularization, v6);
- `N.N` brings with it new option or an essential feature that has been improved (for example, last 6.6 is because updates are in parallel);
- `N.N.N` iprovements to the single options.

The three above can be annunced as "releases".

In this case your PR is nothing but a simple refactoring, so `N.N-N` its enough.

**Comment by ivan-hc** [comment]
@zen0bit I'll fix the above for you, don't worry

**Comment by zen0bit** [comment]
> @zen0bit I'll fix the above for you, don't worry

Ialso found, but you are quicker :+1:

**Pull request merged**
