### PR TITLE
Improve "--sandbox"

### PR DESCRIPTION
**Pull request by ivan-hc**
This is the continuation of https://github.com/ivan-hc/AM/pull/674

@Samueru-sama I'm trying to refine:
- I fixed the "echo" messages in the script to "$PATH" by adding "-e"
- I added "$SUDOCOMMAND" to allow "sed" to work with apps installed via "AM"

Now only one thing is missing: if I allow an app to see a directory... it doesn't see it.

I'm testing this on a Fedora 40 VM and Kdenlive doesn't see the directories I've selected.

Positive note: Anydesk now works!

### CODE REVIEW

**Comment by ivan-hc** [comment]
I've found the issue: Videos is "Video" in italian. The script should use the correct directory using my language:
- Desktop = Scrivania
- Videos = Video
- Downloads = Scaricati

and so on...

**Comment by Samueru-sama** [comment]
> I've found the issue: Videos is "Video" in italian. The script should use the correct directory using my language:
> 
> * Desktop = Scrivania
> * Videos = Video
> * Downloads = Scaricati
> 
> and so on...

That would be an issue with aisap, because aisap uses `xdg-download` `xdg-music` and so on. 

Btw this module uses `#!bin/sh` so you don't need to add the `-e` flag to echo

**Comment by ivan-hc** [comment]
> Btw this module uses `#!bin/sh` so you don't need to add the `-e` flag to echo

I know that -e is not recognized, being this a Shell script... but all "\n" and similar are not working for me, I use Bash.

I'm not sure why this happens, I only know that all pessages are working only if I add -e, so now I can see spaces and colors.

**Comment by Samueru-sama** [comment]
I tested kdenlive anyway:

image

I will later ask the aisap dev if they could add something that actually uses `xdg-user-dirs` that picks the right name of the home user directories for other languages.

**Comment by Samueru-sama** [comment]
Btw I opened this other PR adding something that I found suyu needs: 

https://github.com/ivan-hc/AM/pull/676

**Comment by ivan-hc** [comment]
This is exacty what I was searching for.

Sorry if I ask you this, I've seen that all options are redirected against a path, but not the `--rm-file` ones.

What happens if we add
```
$XDG_DESKTOP_DIR
$XDG_DOWNLOAD_DIR
$XDG_TEMPLATES_DIR
$XDG_PUBLICSHARE_DIR
$XDG_DOCUMENTS_DIR
$XDG_MUSIC_DIR
$XDG_PICTURES_DIR
$XDG_VIDEOS_DIR
```
??

**Comment by Samueru-sama** [comment]
> This is exacty what I was searching for.
> 
> Sorry if I ask you this, I've seen that all options are redirected against a path, but not the `--rm-file` ones.
> 
> What happens if we add
> 
> ```
> $XDG_DESKTOP_DIR
> $XDG_DOWNLOAD_DIR
> $XDG_TEMPLATES_DIR
> $XDG_PUBLICSHARE_DIR
> $XDG_DOCUMENTS_DIR
> $XDG_MUSIC_DIR
> $XDG_PICTURES_DIR
> $XDG_VIDEOS_DIR
> ```
> 
> ??

The problem is that aisap already has an internal database that gives access to for example `xdg-downloads` to web browsers. 

By asking the user if they want to allow `$XDG_DOWNLOAD_DIR` and they say no, aisap might still allow it due to having `xdg-downloads` in its internal dabase. 

Instead when it is `--rm-file xdg-download` aisap will not overwrite that. 

But yeah, if the aisap dev doesn't want to fix, we will have to come up with a solution for this.

**Comment by ivan-hc** [comment]
I was experimentin now with symlinks... but the sandbox is ard to.. punch.

PS: congratulations for this improvemente! :+1: :1st_place_medal:

**Review by Samueru-sama — COMMENTED** [review]
I had a feeling I was missing something lol

**Comment by Samueru-sama** [comment]
I think I fixed the issue of user dirs btw, do not merge!

**Comment by ivan-hc** [comment]
Just tested with AppMan: perfect!  :+1: 

Istantanea_2024-06-19_18-17-36 png

**Comment by ivan-hc** [comment]
This is what changes with the last commit:

#### Enable sandbox
Istantanea_2024-06-19_19-36-01 png

#### Disable sandbox
Istantanea_2024-06-19_19-36-29 png

so as not to clutter the terminal in case of CTRL+C

**Comment by ivan-hc** [comment]
@Samueru-sama I await your considerations before merging this PR

**Comment by ivan-hc** [comment]
In case of CTRL+C, a new attempt may break the created script.

This is the reason of the last commit.

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/assets/88724353/e7ce78ac-2847-4570-8baf-eda5061d77be

**Comment by ivan-hc** [comment]
Fun fact, I've discovered that one of my AppImages is not in the database

https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/releases/tag/mate-system-monitor

**Comment by Samueru-sama** [comment]
Alright I fix the issue with the posibility of one of the xdg user directories being defined as `$HOME`.

I noticed you changed the order of operations to `chmod a+x "$AMCACHEDIR/sandbox-scripts/$2"` that way sudo is only needed to move the script.

But I can change this so that the script only gets moved after several yes/no questions regarding access to each xdg user directory. What do you think? 

This way sudo is needed only once to move the script to path.

I only have to make sure that we remove the exec permission **after** the wrapper script is put on place.

**Comment by ivan-hc** [comment]
OK, if you want to add the password after the questions, its ok for me.

I did it because normally each action I need to use "sudo" is done after a password (see enable/disable completion, remove and install).

However, if you prefer to do this after the questions, I've not problems.

**Comment by Samueru-sama** [comment]
> OK, if you want to add the password after the questions, its ok for me.
> 
> I did it because normally each action I need to use "sudo" is done after a password (see enable/disable completion, remove and install).
> 
> However, if you prefer to do this after the questions, I've not problems.

I see, if you want change it back, but the `ln -sf` has to be the very very last step.

Also I added a message for each step, that way if something goes wrong we know where the script fails to restore.

**Comment by ivan-hc** [comment]
> I see, if you want change it back go ahead, but the `ln -sf` has to be the very very last step.
> 
> Also I added a message for each step, that way if something goes wrong we know where the script fails to restore.

Do wath you think is best, I trust you now.

PS: about the issue I had before, the environment variable was
```
XDG_VIDEOS_DIR="$HOME/"
```
with a final slash, instead of
```
XDG_VIDEOS_DIR="$HOME/Video"
```
I don't know why thi happened, in Fedora 40

**Comment by ivan-hc** [comment]
> PS: about the issue I had before, the environment variable was
> 
> ```
> XDG_VIDEOS_DIR="$HOME/"
> ```
> 
> with a final slash, instead of
> 
> ```
> XDG_VIDEOS_DIR="$HOME/Video"
> ```
> 
> I don't know why thi happened, in Fedora 40

so now that I've repeated the test, I had `/home/ivan/` as suggested directory.

**Comment by Samueru-sama** [comment]
> > I see, if you want change it back go ahead, but the `ln -sf` has to be the very very last step.
> > Also I added a message for each step, that way if something goes wrong we know where the script fails to restore.
> 
> Do wath you think is best, I trust you now.
> 
> PS: about the issue I had before, the environment variable was
> 
> ```
> XDG_VIDEOS_DIR="$HOME/"
> ```
> 
> with a final slash, instead of
> 
> ```
> XDG_VIDEOS_DIR="$HOME/Video"
> ```
> 
> I don't know why thi happened, in Fedora 40

Yeah that left me baffled as well. 

>so now that I've repeated the test, I had /home/ivan/ as suggested directory.

Maybe that is because it got defined as `"$HOME/"` instead of `"$HOME"`? The script is only checking againts `$HOME`

**Comment by Samueru-sama** [comment]
This should fix the issue if the problem is the trailing slash: 


```
if [ "$XDG_DOWNLOAD_DIR" = "$HOME" ] || [ "$XDG_DOWNLOAD_DIR" = "$HOME/" ]; then XDG_DOWNLOAD_DIR=""; fi
if [ "$XDG_MUSIC_DIR" = "$HOME" ] || [ "$XDG_DOWNLOAD_DIR" = "$HOME/" ]; then XDG_MUSIC_DIR=""; fi
if [ "$XDG_PICTURES_DIR" = "$HOME" ] || [ "$XDG_DOWNLOAD_DIR" = "$HOME/" ]; then XDG_PICTURES_DIR=""; fi
if [ "$XDG_VIDEOS_DIR" = "$HOME" ] || [ "$XDG_DOWNLOAD_DIR" = "$HOME/" ]; then XDG_VIDEOS_DIR=""; fi
if [ "$XDG_DOCUMENTS_DIR" = "$HOME" ] || [ "$XDG_DOWNLOAD_DIR" = "$HOME/" ]; then XDG_DOCUMENTS_DIR=""; fi
```

**Comment by Samueru-sama** [comment]
What's crazy is that flatpak also uses these variables for their sandboxing, hopefully they have their check against this issue, because otherwise that's a major security risk lol.

**Comment by ivan-hc** [comment]
We eat Flatpaks

**Comment by ivan-hc** [comment]
@Samueru-sama is it ok if I reduce this message
```
The sandboxed app home will be in \"${SANDBOXDIR:-$HOME/.local/am-sandboxes}\" once launched
```
to
```
The app will be sandboxed in \"${SANDBOXDIR:-$HOME/.local/am-sandboxes}\"
```
?

**Comment by Samueru-sama** [comment]
It's ok, but I would rather keep the `once launched` message, because the directory will no exist until the application is launched.

**Comment by ivan-hc** [comment]
Like this?
```
The app will be sandboxed in \"${SANDBOXDIR:-$HOME/.local/am-sandboxes}\" once launched
```

**Comment by ivan-hc** [comment]
6.12.1

**Comment by ivan-hc** [comment]
I've just updated my Debian Testing and noticed that APT is changed

Istantanea_2024-06-20_02-01-31 png

**Comment by ivan-hc** [comment]
are them trying to copy us?

**Comment by ivan-hc** [comment]
Just finished updating the README. Ready to go!

**Comment by Samueru-sama** [comment]
I haven't used a debian based distro in years. 

The only people I know that use debian as their daily driver are all over 40yo 👀

**Comment by ivan-hc** [comment]
I'm 38, now you know a younger one

**Comment by Samueru-sama** [comment]
> I'm 38, now you know a younger one

Wasn't too far off anyway 😆

**Pull request merged**
