### PR TITLE
Added apps

### PR DESCRIPTION
**Pull request by Sush-ruta**
[afetch.md](https://github.com/user-attachments/files/17103612/afetch.md)
[amfora.md](https://github.com/user-attachments/files/17103613/amfora.md)
[ani-cli.md](https://github.com/user-attachments/files/17103614/ani-cli.md)
[appinstall.md](https://github.com/user-attachments/files/17103616/appinstall.md)
[bandwhich.md](https://github.com/user-attachments/files/17103618/bandwhich.md)
[beaver-notes.md](https://github.com/user-attachments/files/17103620/beaver-notes.md)
[binclock.md](https://github.com/user-attachments/files/17103621/binclock.md)
[blimp.md](https://github.com/user-attachments/files/17103622/blimp.md)
[carbonyl.md](https://github.com/user-attachments/files/17103623/carbonyl.md)
[cherry-studio.md](https://github.com/user-attachments/files/17103624/cherry-studio.md)
[crock.md](https://github.com/user-attachments/files/17103626/crock.md)
[diskonaut.md](https://github.com/user-attachments/files/17103627/diskonaut.md)
[domterm.md](https://github.com/user-attachments/files/17103629/domterm.md)
[dotto.md](https://github.com/user-attachments/files/17103630/dotto.md)
[dstask.md](https://github.com/user-attachments/files/17103631/dstask.md)
[filen-cli.md](https://github.com/user-attachments/files/17103632/filen-cli.md)
[fishterm.md](https://github.com/user-attachments/files/17103633/fishterm.md)
[frontimer.md](https://github.com/user-attachments/files/17103634/frontimer.md)
[funterm.md](https://github.com/user-attachments/files/17103635/funterm.md)
[ghdl.md](https://github.com/user-attachments/files/17103636/ghdl.md)
[ghrel.md](https://github.com/user-attachments/files/17103638/ghrel.md)
[gitui.md](https://github.com/user-attachments/files/17103640/gitui.md)
[go-spotify-cli.md](https://github.com/user-attachments/files/17103641/go-spotify-cli.md)
[grabscr.md](https://github.com/user-attachments/files/17103643/grabscr.md)
[imgcat.md](https://github.com/user-attachments/files/17103644/imgcat.md)
[innerbreeze.md](https://github.com/user-attachments/files/17103645/innerbreeze.md)
[katvan.md](https://github.com/user-attachments/files/17103647/katvan.md)
[matm.md](https://github.com/user-attachments/files/17103648/matm.md)
[mcfly.md](https://github.com/user-attachments/files/17103649/mcfly.md)
[memospot.md](https://github.com/user-attachments/files/17103650/memospot.md)
[mrcode.md](https://github.com/user-attachments/files/17103651/mrcode.md)
[nix-bucks.md](https://github.com/user-attachments/files/17103652/nix-bucks.md)
[open-typer.md](https://github.com/user-attachments/files/17103653/open-typer.md)
[permastead.md](https://github.com/user-attachments/files/17103655/permastead.md)
[picterm.md](https://github.com/user-attachments/files/17103656/picterm.md)
[revealgo.md](https://github.com/user-attachments/files/17103657/revealgo.md)
[simplest-file-renamer.md](https://github.com/user-attachments/files/17103658/simplest-file-renamer.md)
[storadit.md](https://github.com/user-attachments/files/17103659/storadit.md)
[surrealist.md](https://github.com/user-attachments/files/17103660/surrealist.md)
[sysz.md](https://github.com/user-attachments/files/17103661/sysz.md)
[unveil.md](https://github.com/user-attachments/files/17103662/unveil.md)
[wethr.md](https://github.com/user-attachments/files/17103663/wethr.md)
[wives.md](https://github.com/user-attachments/files/17103664/wives.md)
[wthrr.md](https://github.com/user-attachments/files/17103665/wthrr.md)
[xilinota.md](https://github.com/user-attachments/files/17103666/xilinota.md)
[yaka.md](https://github.com/user-attachments/files/17103667/yaka.md)
[youtubeanddownloader.md](https://github.com/user-attachments/files/17103668/youtubeanddownloader.md)
[ytermusic.md](https://github.com/user-attachments/files/17103669/ytermusic.md)

```
❯ cat list
◆ filen-cli : Filen CLI for Windows, macOS and Linux
◆ wethr : 🌤️ Command line weather tool.
◆ gitui : Blazing 💥 fast terminal-ui for git written in rust 🦀
◆ dstask : Git powered terminal-based todo/note manager --  markdown note page per task. Single binary!
◆ ytermusic : An in terminal youtube music client with focus on privacy, simplicity and performance
◆ ani-cli : A cli tool to browse and play anime
◆ matm : watch anime, movies, tv shows and read manga from comfort of the cli
◆ appinstall : AppImage Installer is an easy to use and install tool to create app shrotcuts and integrate AppImage binaries to a linux desktop environment (Launcher) 
◆ ghdl : A much more convenient way to download GitHub release binaries on the command line, works on Win & Unix-like systems
◆ ghrel : Download and verify GitHub release
◆ go-spotify-cli : Control Spotify with CLI commands
◆ mcfly : Fly through your shell history. Great Scott!
◆ wives : A beautiful, modern & feature-rich Terminal Emulator
◆ amfora : A fancy terminal browser for the Gemini protocol.
◆ sysz : An fzf  terminal UI for systemctl
◆ afetch : A CLI system information tool written in Rust.
◆ binclock : binary clock in terminal
◆ crock : crock is rock clock 🪨
◆ diskonaut : Terminal disk space navigator 🔭
◆ wthrr : 🌞 🦀 🌙 Weather companion for the terminal. Rust app. 
◆ blimp : Customizable terminal UI for monitoring weather information, application status, network latency, and more
◆ bandwhich : Terminal bandwidth utilization tool
◆ unveil : Unveil Rs is a tool to create presentations from markdown inspired by reveal.js, mdbook and zola.
◆ revealgo : Markdown driven presentation tool written in Go!
◆ imgcat : Display images and gifs in your terminal.
◆ picterm : TUI image viewer
◆ simplest-file-renamer : Simplest file renamer - rename your files quickly and easily
◆ funterm : "description": null,
◆ fishterm : A open-soruce Terminal remote access
  Secure boilerplate for Electron app based on Vite. TypeScript + Vue/React/Angular/Svelte/Vanilla
◆ domterm : DOM/JavaScript-based terminal-emulator/console
◆ cherry-studio : 🍒 Cherry Studio is a desktop client that supports for multiple LLM providers
◆ permastead : Desktop software for managing a homestead using permaculture design.
◆ frontimer : Desktop timer application always displayed in the forefront of the screen
◆ mrcode : An opinionated editor based on VSCodium / VSCode
◆ memospot : Memospot is a self-contained desktop version of Memos -a privacy-first, lightweight note-taking service.
◆ beaver-notes : Build your knowledge one log at a time
◆ storadit : Minimalistic Todo list/notes taking app
◆ xilinota : Xilinota, an open-source multi-platform note-taking application boasting instant syncing among devices and direct keeping of markdown files. The application runs on Linux, MacOS, Windows, Android and iOS.
◆ yaka : no fuss todo-list manager with full keyboard navigation
◆ katvan : A bare-bones editor for Typst files, with a bias for Right-to-Left editing
◆ nix-bucks :  A money tracker: Your income and expenses at your control
◆ youtubeanddownloader : an app to use youtube and download videos as mp3s or mp4s 
◆ carbonyl : Chromium running inside your terminal
◆ dotto : A portable and modern pixelart editor, written from scratch.
◆ grabscr : Yet another screenshot maker
◆ surrealist : Surrealist is the ultimate way to visually manage your SurrealDB database
◆ open-typer : A free and open source typing tutor program
◆ innerbreeze : Guided breathing meditation app based on the Wim Hof breathing method.
```

### CODE REVIEW

**Comment by ivan-hc** [comment]
I removed gmon.out because it is not a script but something else

**Comment by Sush-ruta** [comment]
> gmon.out

I tested all the scripts in the `am-scripts/x86_64` folder. Most likely a config file or some artifact from running one of the cli programs.

I apologise @ivan-hc – should've been more careful.

**Comment by ivan-hc** [comment]
I like the way you upload these pull requests, I can check line-by-line the list and file-by-file all pages in .md format. Its easier for me to check them. Your way to upload the apps is an example I suggest to anyone. Thank you

**Comment by ivan-hc** [comment]
Your work is amazing, thank you again!

Istantanea_2024-09-24_01-03-12 png

**Comment by Sush-ruta** [comment]
Many thanks @ivan-hc , the appreciation means a lot. 🙏

**Pull request merged**
