### PR TITLE
mkdir -p

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by ivan-hc** [comment]
I have tested this and doesn't work https://github.com/ivan-hc/AM/pull/135#issuecomment-1942167507

**Comment by zen0bit** [comment]
Again

Don't close PR until is discussed, closed by me or merged.

You will have cluttered PRs with almost duplicate entries...

**Comment by ivan-hc** [comment]
What I say is, leave this script as is. I'm performing tests from your brances, non  works. For me it is a waste of time.

The INSTALL script is for sure the only thing thad does not gives troubles here, why we have to change it?

**Comment by zen0bit** [comment]
Are you sure?

I never used uninstalling

I never uninstalled and updated and install several times

Considered that?

**Comment by ivan-hc** [comment]
This does not work for me. I've tested it several times. To uninstall AM just `am -R am`.

**Comment by zen0bit** [comment]
-----------------------------------------------------------------------

 💀 ERROR, the following programs you want to remove are NOT in
    /home/zen/AppImages :

 - am

 INVALID "APPNAME"!

-----------------------------------------------------------------------

 ◆ INSTALLED PROGRAMS/VALID ARGUMENTS (SEE THE "APPNAME" COLUMN):
/opt/am/APP-MANAGER: line 1015: /opt/am/appman: No such file or directory
-----------------------------------------------------------------------

**Comment by ivan-hc** [comment]
This is the problem, you're using only AppMan.

**Comment by zen0bit** [comment]
> This does not work for me. I've tested it several times. To uninstall AM just `am -R am`.

What exactly don't work for you?

**Comment by ivan-hc** [comment]
Are you using AM in AppMan mode or what?

**Comment by zen0bit** [comment]
As I tried/install everything

AppMan and AM during past few months

I am not sure

**Comment by ivan-hc** [comment]
Reinstall both using your changes and tell me if something is wrong.

**Pull request merged**
