### PR TITLE
Optimize database

### PR DESCRIPTION
**Pull request by Samueru-sama**
List of changes, I only tested them on appman btw:

* Changed the sheabang to `/bin/sh`

Even though local is technically not in the POSIX spec, it is supported by every other shell, including dash so it isn't a big deal: https://www.shellcheck.net/wiki/SC3043

**But also I'm not sure why local is needed in those variables.** the variables for `_download_markdown` and `_generate_3rd_party` can have different names if there is a possible conflict in them?

* Some basic optimizations.

You don't need to have 5 seds in a row, as you can chain several different operations in sed by using the `;` as separator. 

Also `sed -E` allows you to match several expressions that way you don't have to type them for several actions.

And now the most important change

* **FIXED THE SEARCH SO NOW IT WORKS!**

image

The original way the command was written made no sense.

The first `grep -i -E "$2" "$AMPATH/$arch-apps"` means that grep will only match the `$2` search. And whatever searches follow would find nothing as grep is now passing the first match to them. 

Instead what I did was filter `$@` to remove `$1` and then I replace every `space` for a `|` that way grep -E looks like this if the search is brave cemu deadbeef suyu

`grep -i -E  "brave|cemu|deadbeef|suyu" "$AMPATH/$arch-apps"`

Where as before only the first search result would have match. Meaning that nothing would have been returned when multiple search args were passed: 

image

Also the original case had an error, as it had this: 

`ARGS=$(echo "$@" | sed 's/-q //')` 

The problem with that is that `$1` can also be `query` and in that case `$1` is not being filtered. So I fixed it the same way that I fixed the grep for the database.

### CODE REVIEW

**Comment by ivan-hc** [comment]
That `local` was introduced by nazdridoi, that part belongs to him

**Comment by Samueru-sama** [comment]
> That `local` was introduced by nazdridoi, that part belongs to him

Well in that case it doesn't really matter, it wasn't a problem before when it didn't exist. And now it will always be used, even though it technically isn't part of POSIX.

**Comment by ivan-hc** [comment]
Nice edit... but if I write "web browser", this is what it shows
```
ivan@debian:~$ am -q web browser

 SEARCH RESULTS FOR "WEB BROWSER":

◆ agregore : A minimal browser for the distributed web (Desktop version).
◆ altus : Client for WhatsApp Web with themes & multiple account support.
◆ android-messages-desktop : Messages for web, as a desktop app.
◆ bauh : GUI for managing AppImage, Arch/AUR, DEBs, Flatpak, Snap and webapps.
◆ beaker-ng : An experimental peer-to-peer Web browser.
◆ brave-appimage : Unofficial AppImage (Web Browser, Stable).
◆ brave : A privacy oriented Web Browser based on Chromium (Stable).
◆ brave-beta-appimage : Unofficial AppImage (Web Browser, Beta Edition).
◆ brave-beta : A privacy oriented Web Browser (Beta Edition).
◆ brave-nightly-appimage : Unofficial AppImage (Web Browser, Nightly Edition).
◆ brave-nightly : A privacy oriented Web Browser (Nightly Edition).
◆ brs-emu-app : BrightScript Emulator, runs on browsers and Electron apps.
◆ bscanfftwebcam : FDOCT tool.
◆ bypass-cors : Unlock browser’s full potential!
◆ catalyst : Catalyst web browser.
◆ chatgpt-next-web : A cross-platform ChatGPT/Gemini UI.
◆ chromium-latest : Web Browser (official unstable build).
◆ chromium : Web Browser. Open source base of Google Chrome, Edge and Brave.
◆ cloud-browser : Access to files located in various cloud services.
◆ coal-launcher : A client to view and play games from the AB Coal website.
◆ code : Visual Studio (VSCode), Original Editor to build/debug web/cloud apps.
◆ delir : Web Technology driven VFX Application.
◆ deskreen : Turns any device with a web browser into a secondary screen.
◆ dezor : The web browser including VPN and Adblocker.
◆ elk : Native version of Elk, a nimble Mastodon web.
◆ elzabrowser : Elza incognito web browser.
◆ erscaffold : A code generator for websites.
◆ eximchain-wallet : Eximchain Wallet web and electron app.
◆ ffwa-facebook : WebApp & Firefox Profile for Facebook.
◆ ffwa-github : WebApp & Firefox Profile for GitHub.
◆ ffwa-gmail : WebApp & Firefox Profile for Gmail.
◆ ffwa-netflix : WebApp & Firefox Profile for Netflix.
◆ ffwa-reddit : WebApp & Firefox Profile for Reddit.
◆ ffwa-twitter : WebApp & Firefox Profile for Twitter.
◆ ffwa-whatsapp : WebApp & Firefox Profile for WhatsApp.
◆ ffwa-wikipedia : WebApp & Firefox Profile for Wikipedia.
◆ ffwa-youtube : WebApp & Firefox Profile for YouTube.
◆ fiery-maui : Web browser with integrated ad-blocker and split views.
◆ fifo : A modern web browser, built on top of modern web technologies.
◆ figma-linux : First interface design tool based in the browser (graphics).
◆ firedragon : Web Browser fork of Librewolf (Firefox) from Garuda Linux.
◆ firefox-appimage : Unofficial AppImage of the Web Browser (Stable).
◆ firefox-beta-appimage : Unofficial AppImage of the Web Browser (Beta).
◆ firefox-beta : Fast, powerful and extensible Web Browser (Beta Edition).
◆ firefox-devedition-appimage : Unofficial AppImage of the Web Browser (Dev).
◆ firefox-dev : Fast, powerful and extensible Web Browser (Developer Edition).
◆ firefox-esr-appimage : Unofficial AppImage of the Web Browser (ESR).
◆ firefox-esr : Fast, powerful and extensible Web Browser (ESR Edition).
◆ firefox : Fast, powerful and extensible Web Browser (Stable).
◆ firefox-nightly-appimage : Unofficial AppImage of the Web Browser (Nightly).
◆ firefox-nightly : Fast, powerful and extensible Web Browser (Nightly Edition)
◆ floorp : Floorp Browser, the most Advanced and Fastest Firefox derivative.
◆ galacteek : IPFS Multi-platform browser for the distributed web.
◆ geeqie : Claiming to be the best image viewer / photo collection browser.
◆ gemalaya : A keyboard-driven Gemini browser written in QML.
◆ google-chrome-beta : Web Browser (Beta version, Unofficial AppImage).
◆ google-chrome-dev : Web Browser (Unstable version, Unofficial AppImage).
◆ google-chrome : Web Browser (Stable version, Unofficial AppImage).
◆ grx : Fastest Web Gerber Renderer.
◆ hyper : A terminal built on web technologies.
◆ insomnia : API client for GraphQL, REST, WebSockets and gRPC.
◆ isolate : Lightweight image browser.
◆ jimud : MUD client for ShadowMUD.com, based on webclient.
◆ join-desktop : A companion app for the Join website.
◆ kanon : Maturita GPJP designed for use with kanon web app.
◆ keeweb : Free cross-platform password manager compatible with KeePass.
◆ keyrier-json : A CLI/library/webapp to perfom SQL queries on JSON & CSV.
◆ knowledge : Save/search/access/explore all your favorite websites and files.
◆ lbry-desktop : A browser and wallet for LBRY.
◆ levior : Converts web pages on-the-fly to the gemtext format.
◆ librewolf : Firefox-based Web Browser focused on privacy, security, freedom.
◆ local-browser : Share your localhost in a unique way.
◆ martian : Websocket testing tool.
◆ marvin : Open Source record and playback test automation for the web.
◆ microsoft-edge-beta : Web Browser provided by Microsoft (Beta Edition).
◆ microsoft-edge-dev : Web Browser provided by Microsoft (Developer Edition).
◆ microsoft-edge : Web Browser provided by Microsoft (Stable Edition).
◆ mini-qml : Minimal Qt deployment for Linux, Windows, macOS and WebAssembly.
◆ mqttx-appimage : MQTT 5.0 Desktop, CLI, and WebSocket client tools.
◆ muffon : Music streaming browser,retrieves audio, video and metadata.
◆ musicalypse : Audio/Music player and server built with Web technologies.
◆ mycrypto : MyCrypto web and electron app.
◆ ncsa-mosaic : One of the first graphical web browsers.
◆ nest-desktop : A web-based GUI application for NEST Simulator.
◆ onshape : Onshape desktop app (web application shell).
◆ open-ai-translator : Browser extension for translation based on ChatGPT API.
◆ opera-beta : Fast and secure web browser (Beta version).
◆ opera-dev : Fast and secure web browser (Developer version).
◆ opera : Fast and secure web browser (Stable version).
◆ painel-web : Novo SGA panel.
◆ palemoon : Web browser, a Firefox fork with a classic UI and modern APIs.
◆ pennywise : Open any website or media in a floating window.
◆ perl-executing-browser : HTML5 user interface for Perl 5 desktop apps.
◆ picturama : Digital image organizer powered by the web.
◆ pinokio : AI Browser.
◆ pocket-browser : A FOSS browser made for privacy and going towards security.
◆ poi-appimage : Scalable KanColle browser and tool.
◆ polar-bookshelf : Personal knowledge repository for PDF and web content.
◆ polypane : Browser for web developers.
◆ postybirb : Multimedia crossposter for multimedia websites.
◆ postybirb-plus : Helps artists post art to multiple websites more quickly.
◆ promethium : Extensible and innovative web browser with built-in AdBlock.
◆ publii : A desktop-based CMS that makes creating static websites fast.
◆ qtchan : 4chan browser in qt5.
◆ quark-player : An Electron based Web Video Services Player.
◆ rclone-browser : Simple cross platform GUI for rclone.
◆ responsively : A browser for developing responsive web apps.
◆ rssguard : Feed reader which supports RSS/ATOM/JSON (no-webengine version).
◆ runjs : JavaScript playground. Write code with Node.js & browser APIs access.
◆ selenium-ide : Open Source record and playback test automation for the web.
◆ simplenote-electron : Simplenote for Web, Windows, and Linux.
◆ singlebox : AppView template for WebCatalog.
◆ skrifa : A simple word processor built with web technologies.
◆ spark-wallet : A wallet GUI for c-lightning, accessible over web/mobile/pc.
◆ sqlitebrowser : DB Browser is a light GUI editor for SQLite databases.
◆ station : A single place for all of your web applications.
◆ streamlink-twitch-gui : A multi platform Twitch.tv browser for Streamlink.
◆ swiftnessx : Electron application boilerplate based on React/Webpack.
◆ teslacam-browser : A minimal TeslaCam Browser.
◆ theweb : Web Browser.
◆ thorium-avx2 : AVX2 Linux builds of Thorium Browser.
◆ thorium-sse3 : Web Browser, Chromium fork with Widevine and FFmpeg support.
◆ thorium : Web Browser, a Chromium fork including Widevine and FFmpeg support.
◆ tidal-hifi-appimage : The web version of listen.tidal.com running in electron
◆ tor-browser : Privacy-oriented Web Browser for sites blocked in your country.
◆ ungoogled-chromium : Chromium Web Browser without Google services.
◆ vechain : A browser that empowers DApps on VeChain.
◆ vesktop : Vesktop gives you the performance of web Discord.
◆ vieb : Vim Inspired Electron Browser.
◆ viper-browser : Fast and lightweight Qt web browser.
◆ vivaldi-snapshot : Advanced Web Browser (Testing Version).
◆ vivaldi-stable : Advanced Web Browser (Stable Version).
◆ watched : A media player and a browser for Excellent entertainment.
◆ waterfox : Browse the World Wide Web, current version.
◆ waterfox-classic-appimage : Browse the World Wide Web (legacy UI).
◆ waterfox-classic : Browse the World Wide Web (legacy UI).
◆ waterfox-g-appimage : Browse the World Wide Web (current version).
◆ wavebox : The next generation of web-desktop communication.
◆ webamp : Winamp Player 2.9 reimplementation in HTML5 and JS.
◆ webcamoid : A full featured and multiplatform webcam suite.
◆ webcord : A Discord and Fosscord client implemented without Discord API.
◆ webdesktop : WebDesktop make apps with just a text editor and nodejs.
◆ webitel-phone : Webitel Phone (Alpha).
◆ webkitty : Local web development IDE.
◆ webrecorder : A complete packaging of Webrecorder hosted service in Electron.
◆ wexond : Extensible, fast and innovative web browser with material UI.
◆ whiteboard : Activity-based slideshow for coding webinars and presentations.
◆ wrapbox : An Electron wrapper for web pages.
◆ wsocks : A light websocket based proxy.
◆ xcloud-desktop-appimage : An unoffical desktop app for the XCloud web beta.
◆ xnviewmp : Graphic viewer, browser, converter.
◆ zapzap : WhatsApp desktop application written in Pyqt6 + PyQt6-WebEngine.
◆ zoom : Video Conferencing and Web Conferencing Service.
◆ zxinfo-file-browser : Organize and manage your emulator files for ZX Spectrum
```

**Comment by ivan-hc** [comment]
you should change something

**Comment by Samueru-sama** [comment]
> Nice edit... but if I write "web browser", this is what it shows
> 
> ```
> ivan@debian:~$ am -q web browser
> 

That's weird, the list isn't as long in my end: 

image

Do want to search for a package that contains a certain string? in that case something like this would need to be added: 

`am -q "web browser" | grep -i "web browser"` 

That would have to be a different function, the questions now is, what do you think the default behavior should be? 

That is does `grep -q` search for multiple packages or searches for a package with certain a string?

I'm on the camp that this should be the default behaviour, and you use the `--specific` flag for what I think you want to happen, let me know.

**Comment by ivan-hc** [comment]
@Samueru-sama I think that the old syntax was good
```
grep -i -E "$2" "$AMPATH/$arch-apps" | grep -i -E "$3" | grep -i -E "$4" | grep -i -E "$5" | grep -i -E "$6" | grep -i -E "$7" | grep -i -E "$8" | grep -i -E "$9" | _clean_lists_and_queries
```
to reach
```
ivan@debian:~$ am -q web browser

 SEARCH RESULTS FOR "WEB BROWSER":

◆ agregore : A minimal browser for the distributed web (Desktop version).
◆ beaker-ng : An experimental peer-to-peer Web browser.
◆ brave-appimage : Unofficial AppImage (Web Browser, Stable).
◆ brave : A privacy oriented Web Browser based on Chromium (Stable).
◆ brave-beta-appimage : Unofficial AppImage (Web Browser, Beta Edition).
◆ brave-beta : A privacy oriented Web Browser (Beta Edition).
◆ brave-nightly-appimage : Unofficial AppImage (Web Browser, Nightly Edition).
◆ brave-nightly : A privacy oriented Web Browser (Nightly Edition).
◆ catalyst : Catalyst web browser.
◆ chromium-latest : Web Browser (official unstable build).
◆ chromium : Web Browser. Open source base of Google Chrome, Edge and Brave.
◆ deskreen : Turns any device with a web browser into a secondary screen.
◆ dezor : The web browser including VPN and Adblocker.
◆ elzabrowser : Elza incognito web browser.
◆ fiery-maui : Web browser with integrated ad-blocker and split views.
◆ fifo : A modern web browser, built on top of modern web technologies.
◆ firedragon : Web Browser fork of Librewolf (Firefox) from Garuda Linux.
◆ firefox-appimage : Unofficial AppImage of the Web Browser (Stable).
◆ firefox-beta-appimage : Unofficial AppImage of the Web Browser (Beta).
◆ firefox-beta : Fast, powerful and extensible Web Browser (Beta Edition).
◆ firefox-devedition-appimage : Unofficial AppImage of the Web Browser (Dev).
◆ firefox-dev : Fast, powerful and extensible Web Browser (Developer Edition).
◆ firefox-esr-appimage : Unofficial AppImage of the Web Browser (ESR).
◆ firefox-esr : Fast, powerful and extensible Web Browser (ESR Edition).
◆ firefox : Fast, powerful and extensible Web Browser (Stable).
◆ firefox-nightly-appimage : Unofficial AppImage of the Web Browser (Nightly).
◆ firefox-nightly : Fast, powerful and extensible Web Browser (Nightly Edition)
◆ galacteek : IPFS Multi-platform browser for the distributed web.
◆ google-chrome-beta : Web Browser (Beta version, Unofficial AppImage).
◆ google-chrome-dev : Web Browser (Unstable version, Unofficial AppImage).
◆ google-chrome : Web Browser (Stable version, Unofficial AppImage).
◆ librewolf : Firefox-based Web Browser focused on privacy, security, freedom.
◆ microsoft-edge-beta : Web Browser provided by Microsoft (Beta Edition).
◆ microsoft-edge-dev : Web Browser provided by Microsoft (Developer Edition).
◆ microsoft-edge : Web Browser provided by Microsoft (Stable Edition).
◆ ncsa-mosaic : One of the first graphical web browsers.
◆ opera-beta : Fast and secure web browser (Beta version).
◆ opera-dev : Fast and secure web browser (Developer version).
◆ opera : Fast and secure web browser (Stable version).
◆ palemoon : Web browser, a Firefox fork with a classic UI and modern APIs.
◆ polypane : Browser for web developers.
◆ promethium : Extensible and innovative web browser with built-in AdBlock.
◆ responsively : A browser for developing responsive web apps.
◆ theweb : Web Browser.
◆ thorium-sse3 : Web Browser, Chromium fork with Widevine and FFmpeg support.
◆ thorium : Web Browser, a Chromium fork including Widevine and FFmpeg support.
◆ tor-browser : Privacy-oriented Web Browser for sites blocked in your country.
◆ ungoogled-chromium : Chromium Web Browser without Google services.
◆ viper-browser : Fast and lightweight Qt web browser.
◆ vivaldi-snapshot : Advanced Web Browser (Testing Version).
◆ vivaldi-stable : Advanced Web Browser (Stable Version).
◆ wexond : Extensible, fast and innovative web browser with material UI.
```

**Comment by Samueru-sama** [comment]
@ivan-hc Don't worry I will update this. The questions is which should be the default behaviour.

**Comment by ivan-hc** [comment]
@Samueru-sama it must find exactly the lines containing all the required words. If you search for "web browser/web browser" or "video editor/video editor", you are looking for exactly that.

So the syntax he used (which I also admit was strange), is certainly the one that works best in this regard.

**Comment by Samueru-sama** [comment]
> @Samueru-sama it must find exactly the lines containing all the required words. If you search for "web browser/browser web" or "video editor/editor video", you are looking for exactly that.
> 
> So the syntax he used until now (which I also admit was strange), is certainly the one that works best in this regard.

Alright I changed it. I guess appman has to be also updated to indicate that this new flag exists: 

image

By default it behaves like it did before.

**Comment by ivan-hc** [comment]
????

```
ivan@debian:~$ am -q web browser

 SEARCH RESULTS FOR "WEB BROWSER":

◆ beaker-ng : An experimental peer-to-peer Web browser.
◆ brave-appimage : Unofficial AppImage (Web Browser, Stable).
◆ brave : A privacy oriented Web Browser based on Chromium (Stable).
◆ brave-beta-appimage : Unofficial AppImage (Web Browser, Beta Edition).
◆ brave-beta : A privacy oriented Web Browser (Beta Edition).
◆ brave-nightly-appimage : Unofficial AppImage (Web Browser, Nightly Edition).
◆ brave-nightly : A privacy oriented Web Browser (Nightly Edition).
◆ catalyst : Catalyst web browser.
◆ chromium-latest : Web Browser (official unstable build).
◆ chromium : Web Browser. Open source base of Google Chrome, Edge and Brave.
◆ deskreen : Turns any device with a web browser into a secondary screen.
◆ dezor : The web browser including VPN and Adblocker.
◆ elzabrowser : Elza incognito web browser.
◆ fiery-maui : Web browser with integrated ad-blocker and split views.
◆ fifo : A modern web browser, built on top of modern web technologies.
◆ firedragon : Web Browser fork of Librewolf (Firefox) from Garuda Linux.
◆ firefox-appimage : Unofficial AppImage of the Web Browser (Stable).
◆ firefox-beta-appimage : Unofficial AppImage of the Web Browser (Beta).
◆ firefox-beta : Fast, powerful and extensible Web Browser (Beta Edition).
◆ firefox-devedition-appimage : Unofficial AppImage of the Web Browser (Dev).
◆ firefox-dev : Fast, powerful and extensible Web Browser (Developer Edition).
◆ firefox-esr-appimage : Unofficial AppImage of the Web Browser (ESR).
◆ firefox-esr : Fast, powerful and extensible Web Browser (ESR Edition).
◆ firefox : Fast, powerful and extensible Web Browser (Stable).
◆ firefox-nightly-appimage : Unofficial AppImage of the Web Browser (Nightly).
◆ firefox-nightly : Fast, powerful and extensible Web Browser (Nightly Edition)
◆ google-chrome-beta : Web Browser (Beta version, Unofficial AppImage).
◆ google-chrome-dev : Web Browser (Unstable version, Unofficial AppImage).
◆ google-chrome : Web Browser (Stable version, Unofficial AppImage).
◆ librewolf : Firefox-based Web Browser focused on privacy, security, freedom.
◆ microsoft-edge-beta : Web Browser provided by Microsoft (Beta Edition).
◆ microsoft-edge-dev : Web Browser provided by Microsoft (Developer Edition).
◆ microsoft-edge : Web Browser provided by Microsoft (Stable Edition).
◆ ncsa-mosaic : One of the first graphical web browsers.
◆ opera-beta : Fast and secure web browser (Beta version).
◆ opera-dev : Fast and secure web browser (Developer version).
◆ opera : Fast and secure web browser (Stable version).
◆ palemoon : Web browser, a Firefox fork with a classic UI and modern APIs.
◆ promethium : Extensible and innovative web browser with built-in AdBlock.
◆ theweb : Web Browser.
◆ thorium-sse3 : Web Browser, Chromium fork with Widevine and FFmpeg support.
◆ thorium : Web Browser, a Chromium fork including Widevine and FFmpeg support.
◆ tor-browser : Privacy-oriented Web Browser for sites blocked in your country.
◆ ungoogled-chromium : Chromium Web Browser without Google services.
◆ viper-browser : Fast and lightweight Qt web browser.
◆ vivaldi-snapshot : Advanced Web Browser (Testing Version).
◆ vivaldi-stable : Advanced Web Browser (Stable Version).
◆ wexond : Extensible, fast and innovative web browser with material UI.

ivan@debian:~$ am -q browser web

 SEARCH RESULTS FOR "BROWSER WEB":


ivan@debian:~$
```
@Samueru-sama

**Comment by ivan-hc** [comment]
You really don't like my syntax, do you?

```
	'-q'|'query')
		case $2 in
			'')
				echo " USAGE: $AMCLI $1 [ARGUMENT]"
				exit
				;;
		esac
		wget -q --tries=10 --timeout=20 --spider https://github.com && _completion_lists
		ARGS=$(echo "$@" | cut -f2- -d ' ')
		echo -e "\n Search results for \"$ARGS\":\n" | tr a-z A-Z
		grep -i -E "$2" "$AMPATH/$arch-apps" | grep -i -E "$3" | grep -i -E "$4" | grep -i -E "$5" | grep -i -E "$6" | grep -i -E "$7" | grep -i -E "$8" | grep -i -E "$9" | _clean_lists_and_queries
		grep -i -E "$2" "$AMPATH/libs-list" | grep -i -E "$3" | grep -i -E "$4" | grep -i -E "$5" | grep -i -E "$6" | grep -i -E "$7" | grep -i -E "$8" | grep -i -E "$9" | _clean_lists_and_queries
		echo ""
		exit 0
		;;
```

**Comment by Samueru-sama** [comment]
@ivan-hc I admire the fact that you noticed that browser web will not match. 

However the multiple greps being chained really doesn't look nice, you can replace lines `167 168` for the older method if you want to match `browser web` or wait for me to come up with a solution that doesn't involve 8 pipes and a limited number of search terms 😅 (I have to go to sleep soon so I will continue this tomorrow).

**Comment by Samueru-sama** [comment]
💪

image

**Comment by ivan-hc** [comment]
oops.... sorry :\

prease, do a PR again

**Comment by ivan-hc** [comment]
EDIT: I was not aware I could reopen the PRs :smile:

**Comment by Samueru-sama** [comment]
> EDIT: I was not aware I could reopen the PRs 😄

Alright. I'm going to hit the bed, let me know if anything is missing.

**Comment by ivan-hc** [comment]
@Samueru-sama lucky you that you can sleep. If you are in Venezuela, we have 6 hours difference. So if it's 10pm at your place, it's 4am at my place.

**Comment by Samueru-sama** [comment]
> @Samueru-sama lucky you that you can sleep. If you are in Venezuela, we have 6 hours difference. So if it's 10pm at your place, it's 4am at my place.

I normally go to sleep much later as well, but a few days ago I went to bed so late that I basically turned the clock around and that's why I went at 10 pm.

Hey the PR has been ready since before I went to bed (I added what was needed for the search to not care about the order of words here), however I just noticed that something slip thru lol. 

I wanted to add the `--color` flag to grep to highlight the matches, but it doesn't work because it gets piped again.

**Pull request merged**
