### PR TITLE
Update template.am: eperimental support for sourceforge

### PR DESCRIPTION
**Pull request by ivan-hc**

### CODE REVIEW

**Comment by Samueru-sama** [comment]
Btw @ivan-hc I'm working on a newer template for archives and appimages that hopefully has a 80%+ success rate. 

It will even automatically filter aarch64 or x86_64.

**Comment by ivan-hc** [comment]
OK, in the meantime I'm converting all sourceforge-based installation scripts

**Comment by ivan-hc** [comment]
@Samueru-sama you've said that you have a faster internet connection, can you test these https://github.com/ivan-hc/AM/pull/727/commits/33437fae20fb3bf926a80bbc39063ee80d7814d3 ?

These are only the old scripts now converted, all those based on sourceforge... eccept speed-dreams.

**Comment by Samueru-sama** [comment]
discord

**Comment by ivan-hc** [comment]
All the new template.am does is to recognize if the given URL contains the work "sourceforge", and then it prompts to know:
- if the project name is the same (if yes, leave blank and press ENTER)
- the description of the app (it may be taken automatically in future, I've not figured out how to have it from the project's page)
- then cheks and shows the download URL... but if it does not exists, asks you to manually check it with a command
- for appimages, the two references to "*mage" will be removed, since files downloaded from sourceforge are named "download"

**Comment by Samueru-sama** [comment]
Hey I didn't test apps and they got merged to main?

**Comment by ivan-hc** [comment]
its all OK, don't worry, I've tested some of them. My only doubt was the tgz file (sweethome3d)

Download URLs are almost the same, you can try them.

The only one that remains the same in terms of download is speed-dreams

But now are all updated to the new template... and all of them are updatable (some of them had not an AM-updater before)!

**Pull request merged**
