### PR TITLE
Merge pull request #649 from ivan-hc/dev

### PR DESCRIPTION
**Pull request by ivan-hc**
Fix new AppImage template

### CODE REVIEW

**Comment by Samueru-sama** [comment]
Btw what do you mean by integrity checks? (I just read the release notes). 

The new template already sends a notify-send when zsync fails to update the appimage. And that gets tested when a new template is made, I think that's enough of a integrity check, if zsync fails to update the appimage we disable the zsync download.

**Comment by ivan-hc** [comment]
This only happens with newer scripts... but what about the older ones?

This is why we need an integrity chek. It must be included in -u or -s.... or at least we should convert all the installation scripts to this new template.

**Comment by ivan-hc** [comment]
or maybe included in `-i`

**Comment by ivan-hc** [comment]
we need a plan for this change

**Comment by Samueru-sama** [comment]
> or at least we should convert all the installation scripts to this new template.

They have to be converted because a lot of them have broken checks to use zsync already.

**Comment by Samueru-sama** [comment]
This whole new template ended up being something that sidetracked me, because I was actually working on optimizing and converting the modules to use `sh`, and I noticed you were updating apps to the existing template and I thought you were doing it to get the check for empty url that wasnt in the template back then 😅

**Comment by Samueru-sama** [comment]
The only thing is that I think all the recent appimages that I've added don't have the zsync check, because I have no plans on adding zsync to my appimages. Those don't need to be updated.

**Comment by Samueru-sama** [comment]
FInally @ivan-hc if you want to start fixing the scripts, I think you have to start with the biggest apps first, as those are the ones where it makes sense to use zsync.

**Comment by ivan-hc** [comment]
> and I noticed you were updating apps to the previous template and I thought you were doing it to get the check for empty url that wasnt in the template back then 😅

???

Nope, new --rolback also supports new templates.

All it does is to clone AM-updater as AM-rollback, and then:
- made $version0 unusable;
- temporarily rename the .zsync files as .old not to made them detected
- replace all lines containing the "wget" command with the "wget" command created with the function

so the comparison action can act to replace the installed app with what you've choose

**Comment by ivan-hc** [comment]
> FInally @ivan-hc if you want to start fixing the scripts, I think you have to start with the biggest apps first, as those are the ones where it makes sense to use zsync.

A big work has been already done in the years, and all bug fixes have been made after user's feedback.

I'd like to keep have these scripts for now, and to change them just in case. I can't focus my whole life on "AM".

**Comment by Samueru-sama** [comment]
> ???

I updated the template because remember the issue that I had that I hit the API limit? 

The issue cause the `AM-updater` to always update, because turns out that if `version` is empty it also updates the app lol. 

I already had a pseudo new template that I was using in the apps that I was adding that had the check for empty `version` but it wasn't in the template. 

After I mentioned that I saw that you updated the wine appimages, and I thought you did it to get that check for empty `version` which that wasn't the reason you did it 😅

**Comment by ivan-hc** [comment]
> After I mentioned that I saw that you updated the wine appimages, and I thought you did it to get that check for empty `version` which that wasn't the reason you did it 😅

I'm sorry I broke your heart :rofl:  . It wasn't for you that I made that change.

**Pull request merged**
