### PR TITLE
Update more apps

### PR DESCRIPTION
**Pull request by Samueru-sama**
Do not merge to merge to main yet as I will test 20 or so apps first. 

Also what is the difference between `orcaslicer` and `orcarslicer-any`? both produce the same link. 

I also updated every app to use the new parsing method with sed, minus one of the redundant orcaslicers as that one I think will need to be removed.

### CODE REVIEW

**Comment by ivan-hc** [comment]
There are four:
```
orcaslicer, orcaslicer-any, orcaslicer-beta, orcaslicer-rc
```
"any" may redirect to one of the other three, and if now it is the same as `orcaslicer`, the next time it may be `orcaslicer-beta` or `orcaslicer-rc`

in brief, it is a generic "releases"

**Comment by ivan-hc** [comment]
if you though that its better to remove it, so do it, and also remove the voice from the x86_64-apps list

Sorry if I'm not much here latelly, you see, I'm trying to fix issues in other appimages I develop.

Thanks for taking care of this, its exactly what I wanted to do soon or later

**Comment by Samueru-sama** [comment]
Oh, I read the first reply and updated it lol, I'm ok leaving it as is.

**Comment by ivan-hc** [comment]
Once you have finished I can work on a workflow run to check only the urls from all "version=" reverences.

I think I should open a new repo to test the installation scripts.

**Comment by Samueru-sama** [comment]
Ok Ivan I tested a bunch of the apps, they work: 

image

however for some reason I can't install `thorium-avx2` 🤔

I can install `thorium` but not the avx2 one, and the link isn't broken. I get this error: 

image

If I check inside appman cache, the script gets turned into this wtf: 

```
#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=thorium-avx2
SITE="Alex313031/thorium"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/home/samuel/Applications/$APP/tmp" "/home/samuel/Applications/$APP/icons" && cd "/home/samuel/Applications/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /home/samuel/.local/bin/$APP\nrm -R -f /home/samuel/Applications/$APP" > ../remove
printf '\n%s' "rm -f /home/samuel/.local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/Alex313031/thorium/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*$APP.*avx2.appimage$" | head -1)
wget -q --no-verbose --show-progress --progress=bar "$version" || exit 1
#wget -q --no-verbose --show-progress --progress=bar "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/home/samuel/Applications/$APP/$APP" "/home/samuel/.local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=thorium-avx2
SITE="Alex313031/thorium"
version0=$(cat "/home/samuel/Applications/$APP/version")
version=$(curl -Ls https://api.github.com/repos/Alex313031/thorium/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*$APP.*avx2.appimage$" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ] || [ -e /home/samuel/Applications/"$APP"/*.zsync ]; then
	mkdir "/home/samuel/Applications/$APP/tmp" && cd "/home/samuel/Applications/$APP/tmp" || exit 1
	[ -e /home/samuel/Applications/"$APP"/*.zsync ] || notify-send "A new version of $APP is available, please wait"
	[ -e /home/samuel/Applications/"$APP"/*.zsync ] && wget -q --no-verbose --show-progress --progress=bar "$version.zsync" 2>/dev/null || { wget -q --no-verbose --show-progress --progress=bar "$version" || exit 1; }
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
	[ -e /home/samuel/Applications/"$APP"/*.zsync ] && { zsync "/home/samuel/Applications/$APP/$APP.zsync" || notify-send -u critical "zsync failed to update $APP"; }
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHER & ICON
./"$APP" --appimage-extract *.desktop 1>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv ./squashfs-root/*.desktop ./"$APP".desktop 2>&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
./"$APP" --appimage-extract .DirIcon 1>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv ./squashfs-root/.DirIcon ./DirIcon 2>&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./"$APP".desktop ]; then
		LINKPATH=$(readlink ./"$APP".desktop)
		./"$APP" --appimage-extract "$LINKPATH" | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop 2>&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
	fi
	if [ -L ./DirIcon ]; then
		LINKPATH=$(readlink ./DirIcon)
		./"$APP" --appimage-extract "$LINKPATH" | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv ./squashfs-root/"$LINKPATH" ./DirIcon 2>&1 | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
	fi
	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/home/samuel/Applications/$APP/icons/$APP#g" ./"$APP".desktop 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
mv ./"$APP".desktop /home/samuel/.local/share/applications/"$APP"-AM.desktop | grep -v "squashfs-root" | grep -v ":" | grep -v "help"; mv ./DirIcon ./icons/"$APP" 1>/dev/null 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
rm -R -f ./squashfs-root 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"
```

image

kekw

**Comment by ivan-hc** [comment]
can you help me with this function?

```
        wget -q https://github.com/ivan-hc/AM/archive/refs/heads/dev.zip
        unzip -qq ./dev.zip
        cd AM-dev/programs/x86_64 || exit 1
        for f in *; do
        if grep -q "^APP=" "$f" 2> /dev/null; then eval echo "$(grep -i '^APP=' "$f" | head -1)"; fi
        if grep -q "^REPO=" "$f" 2> /dev/null; then eval echo "$(grep -i '^REPO=' "$f" | head -1)"; fi
        if grep -q "^SITE=" "$f" 2> /dev/null; then eval echo "$(grep -i '^SITE=' "$f" | head -1)"; fi
        if grep -q "^d=" "$f" 2> /dev/null; then eval echo "$(grep -i '^d=' "$f" | head -1)"; fi
        if grep -q "^dl=" "$f" 2> /dev/null; then eval echo "$(grep -i '^dl=' "$f" | head -1)"; fi
        if grep -q "^rel=" "$f" 2> /dev/null; then eval echo "$(grep -i '^rel=' "$f" | head -1)"; fi
        if grep -q "^tag=" "$f" 2> /dev/null; then eval echo "$(grep -i '^tag=' "$f" | head -1)"; fi
        if grep -q "^v=" "$f" 2> /dev/null; then eval echo "$(grep -i '^v=' "$f" | head -1)"; fi
        if grep -q "^ver=" "$f" 2> /dev/null; then eval echo "$(grep -i '^ver=' "$f" | head -1)"; fi
        if grep -q "^version=" "$f" 2> /dev/null; then eval echo "$(grep -i '^version=' "$f" | head -1)"; fi
        echo '-----------------------------------------------------------------'
        done
```
I need to extract all these variables from installation scripts and expand them

I receive many empty outputs in the first workflow I run from this new repo https://github.com/ivan-hc/AMcheck/actions/runs/9747711685/job/26901036045

**Comment by Samueru-sama** [comment]
@ivan-hc I can tell you that all the links I modified should work, because I tested each one as there was a lot of old `grep browser_download` that I had to convert to the new sed trick, and that meant testing for the url manually with each one. 

The bug I ran into with `thorium-avx2` is that for some reason appman is converting this:

`mv ./tmp/*mage ./"$APP"`

into this which makes no sense

`mv ./tmp/*mage ./"$APP" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help" 2>/dev/null | grep -v "squashfs-root" | grep -v ":" | grep -v "help"`

**Comment by ivan-hc** [comment]
@Samueru-sama I reached https://github.com/ivan-hc/AMcheck/actions/runs/9748153234/job/26902519516

but as you can see, github apis stop giving a version after a dozeen of checks

**Comment by Samueru-sama** [comment]
Oh nvm I found the issue with thorium. Which actually didn't have to do with the mv at all lol.

**Pull request merged**
