### PR TITLE
remove `-d` flag from `strings`

### PR DESCRIPTION
**Pull request by Samueru-sama**
Related to #1199

Using `grep -m 1` reduced the time it takes for `am -f` to complete over what was done before with `strings -d`:

Test (2nd result being with the change): 

image

@xplshn if you know something that could speed this up even more, this feature of am has always been slow in first try without the cached files (+4 seconds).

### CODE REVIEW

**Comment by ivan-hc** [comment]
also, you have 2 references in management.am and 1 in sandboxes.am

**Comment by Samueru-sama** [comment]
With the last commit now it takes less than 2 seconds to complete lol

image

**Comment by ivan-hc** [comment]
> With the last commit now it takes less than 2 seconds to complete lol

@Samueru-sama I don't think its a good idea of using that final `&`

Istantanea_2024-12-12_03-23-40

each program deserve its time for colletting info

**Comment by Samueru-sama** [comment]
> each program deserve its time for colletting info

mmmmm maybe I need to put some `wait` somewhere to still have the 2 second time save, but in the time being I will remove that from here then.

I can't replicate that issue btw, please make sure to clear the cache and try several times.

**Comment by ivan-hc** [comment]
@Samueru-sama put a `wait` in that function
```
_files_files() {
	cd "$APPSPATH" || exit 1
	INSTALLED_APPS=$(find . -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	if [ ! -f "$AMCACHEDIR"/version-args ]; then
		_check_version
	fi
	if [ ! -f "$AMCACHEDIR"/files-type ]; then
		for arg in $INSTALLED_APPS; do
			if [ -f ./"$arg"/remove 2>/dev/null ]; then
		 		_files_type &
			fi
		done
		wait
	fi
	rm -f "$AMCACHEDIR"/files-sizes "$AMCACHEDIR"/files-db
	for arg in $INSTALLED_APPS; do
		if test -f ./"$arg"/remove 2>/dev/null; then
			_files_sizes
			_files_db
		fi
	done
}
```

**Comment by ivan-hc** [comment]
> > each program deserve its time for colletting info
> 
> mmmmm maybe I need to put some `wait` somewhere to still have the 2 second time save, but in the time being I will remove that from here then.
> 
> I can't replicate that issue btw, please make sure to clear the cache and try several times.

you scare me, you read my mind

**Comment by Samueru-sama** [comment]
@ivan-hc can you try this and see if it fixes the issue?

image

put a wait after the for loop where `_files_type` is called.

**Comment by ivan-hc** [comment]
> put a wait after the for loop where `_files_type` is called.

better after the `done`, since that part is acting on single arguments if not listed

**Comment by ivan-hc** [comment]
I have seen that in `--launcher ` you check for `github.com/AppImage/AppImageKit/wiki/FUSE`, what if the AppImage is Type Thr.... ehm, a next generation one?

**Comment by Samueru-sama** [comment]
> I have seen that in `--launcher ` you check for `github.com/AppImage/AppImageKit/wiki/FUSE`, what if the AppImage is Type Thr.... ehm, a next generation one?

It should still work, `github.com/AppImage/AppImageKit/wiki/FUSE` is a common string on all appimage runtimes as far as I know. 

In fact the addition of `github.com/AppImage/AppImageKit/wiki/FUSE` was recent because it also recognizes the `uruntime` appimages while the older method did not.

--------------------

To determine if an AppImage is ~~type3~~ next-generation you just need to run `file` on it and `grep "static"`, which I also added since before we used strings for that as well.

**Comment by xplshn** [comment]
> Related to #1199
> 
> Using `grep -m 1` reduced the time it takes for `am -f` to complete over what was done before with `strings -d`:
> 
> Test (2nd result being with the change):
> 
> image
> 
> @xplshn if you know something that could speed this up even more, this feature of am has always been slow in first try without the cached files (+4 seconds).

Sorry, today I swapped distro, I had to compile 68 packages and then open my notebook  and swap the HDD drive I had prepared.

image

**Comment by xplshn** [comment]
`grep -Eao '[\t\r\n -~]{4,}'`, behaves the same way as `string`, works on busybox, and should work everywhere else too

**Comment by xplshn** [comment]
image
You can do both the `strings` and `grep` with a single `grep` line, but I used two grep commands for clarity

**Comment by xplshn** [comment]
in `pelf-sqfs`, an old edition of `pelf`, I also used a similar trick, but to calculate the offset until we find a certain marker of string, perhaps that's useful here too? For now, I think this is the best solution.

`grep` uses the [Boyer Moore String Search Algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string-search_algorithm), which gets increasingly faster as the file's size increases

**Pull request merged**
