### PR TITLE
Zen0bit refactoring

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by ivan-hc** [comment]
@zen0bit this kind of PR does not work, this also involves other files:

Istantanea_2024-05-12_19-18-48

not counting any other bugfixes I had to make to other files. They would conflict with main and dev

**Comment by ivan-hc** [comment]
Can I merge this and close the other two (https://github.com/ivan-hc/AM/pull/554 and https://github.com/ivan-hc/AM/pull/552)?

**Comment by ivan-hc** [comment]
I'll also merge this in "dev" for tests

**Comment by zen0bit** [comment]
> I'll also merge this in "dev" for tests

Sure, but I am not done yet...
Still a lot to do
So don't expect everything work yet...

**Comment by ivan-hc** [comment]
> Sure, but I am not done yet... Still a lot to do So don't expect everything work yet...

Take all the time you need.

**Comment by zen0bit** [comment]
No shellcheck errors or warnings anymore...
:muscle: 
Some are disabled for now...

**Comment by zen0bit** [comment]
Let's test what is broken...

**Comment by ivan-hc** [comment]
> Let's test what is broken...

Should I merge into https://github.com/ivan-hc/AM/tree/zen0bit-refactoring and after to https://github.com/ivan-hc/AM/tree/dev then?

**Comment by zen0bit** [comment]
> > Let's test what is broken...
> 
> @zen0bit Should I merge into [`zen0bit-refactoring`](https://github.com/ivan-hc/AM/tree/zen0bit-refactoring?rgh-link-date=2024-05-12T22%3A35%3A30Z) and after to [`dev`](https://github.com/ivan-hc/AM/tree/dev?rgh-link-date=2024-05-12T22%3A35%3A30Z) then?

I think history will need to clean again...
will see

**Comment by ivan-hc** [comment]
@zen0bit give me the OK when you're done

**Comment by zen0bit** [comment]
OK for now

**Pull request merged**
