### PR TITLE
Keepitsimple

### PR DESCRIPTION
**Pull request by Samueru-sama**
Moved `"$AMPATH"/.cache` to a proper location in defined in the new variable `$CACHEDIR` as this is needed for am to function when it is owned by root. 

You should be able to update programs without sudo provided you have the following in your `/etc/sudoers`:

```
username ALL=NOPASSWD: /opt/*/AM-updater
```

AM cannot updated itself yet without sudo as that is a whole different thing. 

Also yeah, cleaned up the installation scripts.

# TODO

* Make am be able to upgrade itself without sudo, this likely means that there will have to be a `/opt/am/APP-updater` for am. 

* And I think that is all lol

### CODE REVIEW

**Comment by zen0bit** [comment]
🤯 whooa thats big

Are you able to open `files changed` on github?
🤣

**Comment by Samueru-sama** [comment]
> 🤯 whooa thats big
> 
> Are you able to open `files changed` on github? 🤣

What's important is the first few files changed, the rest is just cleaning garbage that wasn't needed anymore (even before these changes).

**Comment by Samueru-sama** [comment]
Also I just noticed a bug, I can do `am -u application` and the app updates without issues. 

But I cannot do `am -u` alone, it doesn't update the applications this way.

**Comment by zen0bit** [comment]
You messed up

You merged dev in your changes
(rewrite what you done partialy)

you should REBASE ondev not MERGE!

**Comment by Samueru-sama** [comment]
> You messed up
> 
> You merged dev in your changes (rewrite what you done partialy)
> 
> you should REBASE ondev not MERGE!

This? https://github.com/ivan-hc/AM/pull/489/commits/32d3f541f0f55d5f25ee0a9f1c177e9adf692d99

It was a conflic that I had to solve. And yeah I intended that. Ivan added that function _no_sudo as a patch to the patch that warns users that AM belongs to the user that installed it.

**Comment by zen0bit** [comment]
> > You messed up
> > You merged dev in your changes (rewrite what you done partialy)
> > you should REBASE ondev not MERGE!
> 
> This? [32d3f54](https://github.com/ivan-hc/AM/commit/32d3f541f0f55d5f25ee0a9f1c177e9adf692d99)
> 
> It was a conflic that I had to solve. And yeah I intended that. Ivan added that function _no_sudo as a patch to the patch that warns users that AM belongs to the user that installed it.

You want add that commit to history. With same name. Not named Merged branch sev into...
so anyone will see instantly what really changed

**Comment by zen0bit** [comment]
Better but still not right

You don't want that mistake in history

Go back before merge dev in to your branch
there create new branch (offline only enough)
REBASE on ivan's dev
Finally rebase your current branch keepitsimple on that repaired branch

Now that wrong commit is gone...
Look if everything is right

**Comment by zen0bit** [comment]
Don't add more commits.

You have to rebase first

**Comment by Samueru-sama** [comment]
> Don't add more commits.
> 
> You have to rebase first

I just took the APP-MANAGER from dev and applied the changes manually (the new variable and removed what isn't needed), the diff still looks like before?

Will the rebase make the diff look any different now?

**Comment by zen0bit** [comment]
Better but still not right

You don't want that mistake in history

Go back before merge dev in to your branch
there create new branch (offline only enough)
REBASE on ivan's dev
Add missed commits again (you can copy them)
Finally rebase your current branch keepitsimple on that repaired branch

Now that wrong commit is gone...
Look if everything is right

**Comment by Samueru-sama** [comment]
> You don't want that mistake in history

Why? 

(Also I have some news about mistakes in history you don't want to hear lol).

**Comment by zen0bit** [comment]
Imagine project with history full of mistakes like that
Looks trust able?
You wanna hide that before potential users :wink:

If you keep histoy like that, nobody really know what changed in each commits
You have to open each a take look whats in
That's to much work and anyone sane who is checking script before running them, rather leave project even before trying...

**Comment by Samueru-sama** [comment]
> Imagine project with history full of mistakes like that Looks trust able? You wanna hide that before potential users 😉
> 
> If you keep histoy like that, nobody really know what changed in each commits You have to open each a take look whats in That's to much work and anyone sane who is checking script before running them, rather leave project even before trying...
> 
> But that's not not to much about hiding mistakes, like
> 
> ### keeping history clean
> Imagine that you wanna find cause of some hidden bug. If you have nice history without commits like "Merge from dev branch" It will be a lot better to find anything

I dont really understand what the problem is, but anyway once I get the /am/AM-updater working I will make a new branch with these changes, this is a draft after all.

**Comment by zen0bit** [comment]
Check newer lazygit video...
https://www.youtube.com/watch?v=_REmkoIyPW0

**Comment by ivan-hc** [comment]
@zen0bit I don't see where is the issue with the history, I myself have stuff that made me feel ashamed between commits and issues faced with these commits... but I justify myself because I'm not a developer, just someone that did all this for fun. @Samueru-sama have did a huge work on this, I've analyzed the installation scripts and him have done things that I would like to do too (i.e. remove the "currentuser" references and all final messages, not compatible with how AM works now).

I must only analyze the modules now.

@Samueru-sama why you're unable to update APP-MANAGER?

Also, are these changes compatible with AppMan?

**Comment by ivan-hc** [comment]
@Samueru-sama these are the strange things I've found:
- in update.am, line 42, `rm -R -f "$CACHEDIR"/* # Scary!`, please fix this, I did this in nolibfuse and worked as a `rm -Rf /`, maybe only in this case dn't use the new variable and use `rm -R -f $AMPATH/.cache/*`, that at least have a dot
- in update.am, line 61, `$SUDOCOMMAND ./AM-updater > /dev/null 2>&1 &&` this means that to update I need a password? This was not my goal (I'm lazy, I dont want to use it in "AM")... I see that its repeated at line 100

so you have to fix these two.

**Comment by ivan-hc** [comment]
@Samueru-sama is it necessary to remove _no_sudo? Also for "am -l", "am -f"... and similar? Also for AppMan users that (still) use "sudo" on every packakage manager they use?

**Comment by ivan-hc** [comment]
> @Samueru-sama these are the strange things I've found:
> 
>     * in update.am, line 42, `rm -R -f "$CACHEDIR"/* # Scary!`, please fix this, I did this mistake in nolibfuse and it worked as a `rm -Rf /`, maybe only in this case dn't use the new variable and use `rm -R -f $AMPATH/.cache/*`, that at least have a dot

do the same in sync.am, line 92
```
rm -R -f "$CACHEDIR"/* 1>/dev/null; cd "$CACHEDIR" || return
```

**Comment by ivan-hc** [comment]
About what I've said before, i.e.



> @Samueru-sama these are the strange things I've found:
> 
>     * in update.am, line 61, `$SUDOCOMMAND ./AM-updater > /dev/null 2>&1 &&` this means that to update I need a password? This was not my goal (I'm lazy, I dont want to use it in "AM")... I see that its repeated at line 100

I understand how you want to make it work, like a traditional package manager. But that's not what I want in "AM", that's not why I created it. I want to avoid using the password... also


> You should be able to update programs without sudo provided you have the following in your `/etc/sudoers`:
> 
> ```
> username ALL=NOPASSWD: /opt/*/AM-updater
> ```

this is wrong!

A tool like this was created purely for amateur purposes, it's already been adding files to /etc for bash completion... now it should also edit such an important file like "sudoers" as if it were any other file? This approach is completely wrong!

Let's not spread the responsibilities of "AM" too much, all it takes is a comma placed in the wrong place, and a mess happens!

I suggest keeping "AM" for one system administrator's use, and force promoting "AM" for all other users.

As for the problem regarding permissions in the "remove" files of the applications, I had already canceled a commit to give you the opportunity to work freely, i.e. this function I'd like to move in APP-MANAGER (and that was originally in install.am)
```
function _secure_remove() {
	# Add a security layer to scripts named "remove" of installed apps to prevent file removal by non-privileged users
	if [ $AMCLI == am ] 2>/dev/null; then
		for r in /opt/*/; do
			if test -f $r/remove; then
				if ! cat $r/remove | grep -F 'z "$SUDO_COMMAND"' 2> /dev/null; then
					sed -i '1 a if [ -z "$SUDO_COMMAND" ]; then exit 1; fi' $r/remove 2> /dev/null
				fi
			fi
		done
	fi
}

_secure_remove &> /dev/null
```
and this command to add in install.am
```
sed -i '1 a if [ -z "$SUDO_COMMAND" ]; then exit 1; fi' $APPSPATH/$(cd $APPSPATH && ls -td * | head -1)/remove 2> /dev/null
```
I had both in this commit I have reverted https://github.com/ivan-hc/AM/pull/486/commits/5264665b3305edaacaa8b12ef4791841c371a108

This is an additional patch, for use with "AM" only, and prevents the app from being uninstalled and removed if you do not have root privileges.
```
if [ -z "$SUDO_COMMAND" ]; then exit 1; fi
```
obviously, it cannot be added directly into the installation scripts as they are also used by AppMan

**Comment by ivan-hc** [comment]
@Samueru-sama could we just let users of sudo group have rw permissions of these files and directories?

To edit the sudoers file was not my goal, and I had not understand that you wanted to do so

**Comment by Samueru-sama** [comment]
> @Samueru-sama could we just let users of sudo group have rw permissions of these files and directories?
> 
> To edit the sudoers file was not my goal, and I had not understand that you wanted to do so

There are applications like feral gamemode that let users do stuff like change the cpu-scheduler without sudo, I think it creates a group that lets users do those operations.

Also I just noticed that AM updates itself in the update.am module by running `$AMCLIPATH -s`. 

I just quickly tested changing it to `$SUDOCOMMAND $AMCLIPATH -s` and it worked (did ask for the password as expected since it isn't in sudoers), and also destroyed the changes to the modules since it updated to the main branch here lol. 

But yeah it is very easy to make this right, the biggest change has been moving the APP-MANAGER `.cache` stuff to a proper location that doesn't need sudo for it to operate.

**Comment by ivan-hc** [comment]
OK, if you can assign a group to AM, so be it.

**Comment by Samueru-sama** [comment]
@ivan-hc I think I will make a new PR first changing all instances of '$AMPATH/.cache' to a proper XDG location, and once that is done it will be easier for me to add the group and no sudo changes. As right now there is a lot of changing from dev that I need to keep track of. 

Also can you merge the commits that get rid of the chown and message in each installation script? as those are not needed anymore even in the current version of AM.

**Comment by ivan-hc** [comment]
ok

**Comment by ivan-hc** [comment]
we should also redirect the download of modules in sync.am from
```
MODULES=$(wget -q $HeaderAuthWithGITPAT https://api.github.com/repos/ivan-hc/AM/contents/modules -O - | grep download_url | cut -d '"' -f 4)
```
to a branch, if we hope to test new features

**Comment by ivan-hc** [comment]
@Samueru-sama use this
```
https://api.github.com/repos/ivan-hc/AM/contents/modules?ref=main
```
for our tests we will manually rename it as 
```
https://api.github.com/repos/ivan-hc/AM/contents/modules?ref=dev
```

about other files, it will be enough to repage "main" from APP-MANAGER in "$AMREPO"

I'm waiting for your feedback.

**Comment by ivan-hc** [comment]
@Samueru-sama please, change this in sync.am
```
MODULES=$(wget -q $HeaderAuthWithGITPAT https://api.github.com/repos/ivan-hc/AM/contents/modules -O - | grep download_url | cut -d '"' -f 4)
```
with this
```
MODULES=$(wget -q $HeaderAuthWithGITPAT https://api.github.com/repos/ivan-hc/AM/contents/modules?ref="$AMBRANCH" -O - | grep download_url | cut -d '"' -f 4)
```

also replace this in APP-MANAGER
```
	function _am_newrepo_check() {
		# Determine if the CLI uses the "main" branch of https://github.com/ivan-hc/AM or an alternative one
		if [[ -f "$AMPATH"/new-repo.txt ]]; then
			AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
			APPSDB="$AMREPO/programs/$arch"
			APPSLISTDB="$AMREPO/programs/$arch-apps"
			LIBSLISTDB="$AMREPO/programs/libs-list"
			if [[ "$@" != "newrepo off" ]]; then
				echo '--------------------------------------------------------------------------'
				echo " Source: $AMREPO"
				echo '--------------------------------------------------------------------------'
			fi
		else
			AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
			APPSDB="$AMREPO/programs/$arch"
			APPSLISTDB="$AMREPO/programs/$arch-apps"
			LIBSLISTDB="$AMREPO/programs/libs-list"
		fi
	}
```
with this
```
	function _am_newrepo_check() {
		# Determine if the CLI uses the "main" branch of https://github.com/ivan-hc/AM or an alternative one
		if [[ -f "$AMPATH"/new-repo.txt ]]; then
			AMREPO=$(<"$AMPATH/new-repo.txt") # Utilizing command substitution with < for more efficient file reading
			AMBRANCH=$(basename "$AMREPO")
			APPSDB="$AMREPO/programs/$arch"
			APPSLISTDB="$AMREPO/programs/$arch-apps"
			LIBSLISTDB="$AMREPO/programs/libs-list"
			if [[ "$@" != "newrepo off" ]]; then
				echo '--------------------------------------------------------------------------'
				echo " Source: $AMREPO"
				echo '--------------------------------------------------------------------------'
			fi
		else
			AMREPO="https://raw.githubusercontent.com/IVAN-HC/AM/main" # Consolidating variable assignments for clarity and brevity
			AMBRANCH=$(basename "$AMREPO")
			APPSDB="$AMREPO/programs/$arch"
			APPSLISTDB="$AMREPO/programs/$arch-apps"
			LIBSLISTDB="$AMREPO/programs/libs-list"
		fi
	}
```
I have added this
```
AMBRANCH=$(basename "$AMREPO")
```
to get the name of branch

**Comment by Samueru-sama** [comment]
@ivan-hc Uh oh. Do I need to do that here? https://github.com/ivan-hc/AM/pull/492

**Comment by ivan-hc** [comment]
@Samueru-sama would you prefer that I solve the conflicts by myself in this PR?

If you want, I can upload all modules and remove the function to prevent the use of AM manually.

**Comment by ivan-hc** [comment]
in the meantime I started commits https://github.com/ivan-hc/AM/commits/dev/

**Comment by Samueru-sama** [comment]
> @Samueru-sama would you prefer that I solve the conflicts by myself in this PR?

Here? I don't think this will be merged now. Actually I changed the entire way `$CACHEDIR` works, `$CACHEDIR` used to be defined a `XDG_CACHE_HOME/am` but now it is just `XDG_CACHE_HOME` and the `am` dir is created in the places where `$CACHEDIR` is used

That way the scary rm -rf isn't as scary lol. 

The only thing is I dont know if you can merge the apps scripts commits where I removed the message and chown part.

**Comment by ivan-hc** [comment]
sure, I can upload the changes from dev to your branch

**Comment by ivan-hc** [comment]
ok, just remove that .zip file

**Comment by Samueru-sama** [comment]
> ok, just remove that .zip file

Done and also added the modules. (Mind that APP-MANAGER is still different)

Omg zeno must be cringing really hard right now xd.

**Comment by ivan-hc** [comment]
It seems to be all OK now, any questions aboit APP-MANAGER and INSTALL?

**Comment by Samueru-sama** [comment]
> It seems to be all OK now, any questions about APP-MANAGER and INSTALL?

Yeah seems ok, are you going to merge this?! (I didn't notice you were editing this)

This might be ready today, we just need to do this trick to allow the user to use `$SUDOCOMMAND` without password for the updates: 

`echo "username ALL=NOPASSWD: /opt/*/AM-updater" | sudo tee -a /etc/sudoers`

**Comment by ivan-hc** [comment]
in the meantime we must test this into a VM

**Comment by Samueru-sama** [comment]
Zeno I'm sorry Ivan gave me 50 euro.

**Comment by Samueru-sama** [comment]
> in the meantime we must test this into a VM

I need to know how do you plan on solving the lack of an AM-updater for am itself?

**Comment by ivan-hc** [comment]
> > in the meantime we must test this into a VM
> 
> @ivan-hc I need to know how do you plan on solving the lack of an AM-updater for am itself?

this worked https://github.com/ivan-hc/AM/commit/255b3f94742cc704cc24cf4ad1614566e7efdcc3

**Comment by ivan-hc** [comment]
@Samueru-sama I still receive an error with `cat: /opt/am/options` that does not exists, can you investigate?

**Comment by Samueru-sama** [comment]
> @Samueru-sama I still receive an error with `cat: /opt/am/options` that does not exists, can you investigate?
> 
> In the meantime Im' doing tests

That's weird because this should make options be in $CACHEDIR: 

image

**Pull request merged**
