### PR TITLE
Shows the total size of installed apps

### PR DESCRIPTION
**Pull request by ivan-hc**

### CODE REVIEW

**Comment by ivan-hc** [comment]
@Samueru-sama I've found an issue, I've installed two apps, then I've renamed the "remove" file, and also if this app is not listed, total sizes are including the app "not managed by AppMan/AM"

**Comment by Samueru-sama** [comment]
> @Samueru-sama I've found an issue, I've installed two apps, then I've renamed the "remove" file, and also if this app is not listed, total sizes are including the app "not managed by AppMan/AM"

Sorry Ivan but I did not understand what you wanted to say here.

Is this a problem that wasn't happening before?

**Comment by ivan-hc** [comment]
@Samueru-sama for testing purposes, I renamed/removed the "remove" file to not list the application, so it wouldn't appear to be managed by "AM", or "AppMan". The overall dimensions did not change.

Try renaming/moving the "remove" file of some large app, and see if the total size changes. At present they will not change.

However, I have already made up for it. I had to replace:
```
echo -e "\n TOTAL SIZE: $(du -sh "$APPSPATH" | awk '{print $1}' | sed 's/.$/ &/; s/$/iB/') of disk space in use\n"
```
with:
```
echo -e "\n TOTAL SIZE: $(du -ch $(find -name 'remove' -printf "%h\n" 2>/dev/null) 2>/dev/null | tail -1 | awk '{print $1}' | sed 's/.$/ &/; s/$/iB/') of disk space in use\n"
```

do you remember the video of DistroTube? The review of "AM"? It always shows a ./containerd directory. It was not managed by "AM". Since then I've done this fix.

**Comment by Samueru-sama** [comment]
> @Samueru-sama for testing purposes, I renamed/removed the "remove" file to not list the application, so it wouldn't appear to be managed by "AM", or "AppMan". The overall dimensions did not change.
> 
> Try renaming/moving the "remove" file of some large app, and see if the total size changes. At present they will not change.
> 
> However, I have already made up for it. I had to replace:
> 
> ```
> echo -e "\n TOTAL SIZE: $(du -sh "$APPSPATH" | awk '{print $1}' | sed 's/.$/ &/; s/$/iB/') of disk space in use\n"
> ```
> 
> with:
> 
> ```
> echo -e "\n TOTAL SIZE: $(du -ch $(find -name 'remove' -printf "%h\n" 2>/dev/null) 2>/dev/null | tail -1 | awk '{print $1}' | sed 's/.$/ &/; s/$/iB/') of disk space in use\n"
> ```
> 
> do you remember the video of DistroTube? The review of "AM"? It always shows a ./containerd directory. It was not managed by "AM". Since then I've done this fix.

Oh, you meant that `"$APPSPATH"` can contain other programs that weren't installed by appman. 

Tbh I would have changed the wording to `TOTAL SIZE: of disk space in use in "$APPSPATH"` in that case 😅 but you found a solution? so that's great!

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/assets/88724353/a95e6998-11f3-4dc5-8566-c7c4794bc23b

**Comment by ivan-hc** [comment]
Solved!

**Pull request merged**
