### PR TITLE
commit-am2plasite-remove-icons-from-table

### PR DESCRIPTION
**Pull request by hotlittlewhitedog**
modified:   tools/am2pla-site

Hi all 😄👍  

In this commit, I removed completely the icon field from the tables.   
I think it's the way to go because we can't just hide the icons in client side!  
It will be more efficient to do like this.  

Next step would be to create sub files from A to Z for AppImages category but first we have to check if it's quick enough.   

Here is a screenshot of current commit: 
  
Screenshot 2024-10-31 at 22 42 42

### CODE REVIEW

**Comment by hotlittlewhitedog** [comment]
Ref: https://github.com/ivan-hc/AM/issues/1055

**Comment by ivan-hc** [comment]
hi, I already know that that is how the site appears without icons... it was like this before I added the icons.

So nope, to remove the icons like this is not the way to go... alternativelly can be created more pages for a mobile view... or a JS to hide the icons.

I added the icons because someone asked me, time ago, I can't step back. Sorry.

**Comment by ivan-hc** [comment]
I'd better reopen the issue and move it to the dedicated repository.

I think we need help on the JS/CSS/HTML level rather than a SHELL intervention.

**Comment by hotlittlewhitedog** [comment]
This kind of thing as to be done server side because on client side, it's too late. If you don't want to remove the icons, the only way is to divide the big categories for example in sections A-Z (by name) and the section by pages of maybe 20 items. But again, the subdivisions have to be done server side. // On client side, you have poor controls, it's just esthetic.

**Comment by ivan-hc** [comment]
hi @hotlittlewhitedog , this is how I solved https://github.com/ivan-hc/AM/commit/183f0e31193cfe09391e85b8ecaf919dfb047398

**Pull request closed without merging**
