### PR TITLE
continuation...

### PR DESCRIPTION
**Pull request by zen0bit**
Refactoring

### CODE REVIEW

**Comment by ivan-hc** [comment]
@zen0bit I think that the "dev" branch right now is a mess... can you upload here INSTALL, APP-MANAGER and modules (without the apps)? This way we should also be able to check differences between main and dev from the webui

**Comment by ivan-hc** [comment]
@zen0bit I don't think you'll solve much if you leave everything to github actions. You should use AM daily and test it module by module, command by command, to see where you went wrong.

**Comment by Samueru-sama** [comment]
Why are you making an am directory in `/usr/local/bin`? 

image

**Comment by ivan-hc** [comment]
> Why are you making an am directory in `/usr/local/bin`?
> 
> image

:man_facepalming:

**Comment by zen0bit** [comment]
> > Why are you making an am directory in `/usr/local/bin`?
> > image
> 
> 🤦‍♂️

Don't see your images...

**Comment by zen0bit** [comment]
> @zen0bit I don't think you'll solve much if you leave everything to github actions. You should use AM daily and test it module by module, command by command, to see where you went wrong.

I can do that But than I need repeat these steps everytime
This will work same just automated...
From now on to the future without any effort
So why not tried that?
(Not familiar with BATS)
bash testing platform

Anyone?

**Comment by ivan-hc** [comment]
why should you repeat th steps? Just download the zip file of the refactoring branch and push only the needed files.

In the meantime I'll remove the existing dev and create a new dev branch

**Comment by ivan-hc** [comment]
tell me when you're ready, I'll remove/create the dev branch

**Comment by zen0bit** [comment]
I just rebased my work on refactor branch

Don't need to copy anything
For me git is working...

**Comment by ivan-hc** [comment]
so I'm going close that PR and resync dev with main

**Comment by ivan-hc** [comment]
the new "dev" is ready, PR whenever you want

**Comment by Samueru-sama** [comment]
> I can't implement this jet for multiple branches, I must wait you finish with the refactoring first

Do I need to refactor anything?

**Comment by zen0bit** [comment]
?

you can hunt where are missed arguments and create PR to my branch?

https://github.com/oSoWoSo/AM/tree/dev-refactor

**Comment by zen0bit** [comment]
Anyone have experience with github codespace sharing?
Maybe we could try that...
That way we can work on same file together (I think is posible...)
hm...?
@Samueru-sama I offer you invitation to my organization..

**Comment by Samueru-sama** [comment]
> @Samueru-sama I offer you invitation to my organization.. Heart this if you want send invitation..

Yes I also want 50 euro 👀

**Comment by zen0bit** [comment]
Little bit frustrate me that in list of available apps are shown also installed app.

Looks strange to me..

Can I remove it?

**Comment by ivan-hc** [comment]
> Little bit frustrate me that in list of available apps are shown also installed app.
> 
> Looks strange to me..

You asked me to implement it https://github.com/ivan-hc/AM/issues/411

> Can I remove it?
> 
> PS: Looking for easiest way to pick 1 random app from all available..

feel free doing whatever you want

**Comment by zen0bit** [comment]
@ivan-hc can you cancel this workflow run please?
https://github.com/ivan-hc/AM/pull/552/checks
i can' t...

**Comment by ivan-hc** [comment]
@zen0bit I had to solve a bug with the option/suboption "--force-latest" in "update.am" and "install.am"

https://github.com/ivan-hc/AM/pull/557/files

please update the related modules in your fork

**Comment by zen0bit** [comment]
@ivan-hc Can you look at checks `update.am`..

## Something we want fix..
PS: Looks like you can already push commits directly to my branch as @Samueru-sama did 👍 (thank you)
So we don't need PR. We can work together in my repo...

## I will look more in that codespace thing..

Can be used to worktogether in realtime with chat etc... looks pretty powerfull. And will solve Ivan 's git problem. Since you will work through webui (just better one)

# Take a look by use the code button above..
codespace name AM refactor

**Comment by ivan-hc** [comment]
where are the other modules?

**Comment by ivan-hc** [comment]
I need that you upload all other modules in this PR and that you redirect it to "dev"

It will be easier for me to test if this code work as it should

**Comment by zen0bit** [comment]
> I need that you upload all other modules in this PR and that you redirect it to "dev"
> 
> It will be easier for me to test if this code work as it should

discord?

**Comment by zen0bit** [comment]
I will look into that

Problems are caused due to unclean history...
Then can't be easily reabased/merged etc..

I cleaned up history in main branch
# Look here:
https://github.com/oSoWoSo/AM/tree/main-clean
Files are exactly the same, Same commits...
Just 1207 commits less (Because there isn't any MR commits (totaly usefull)) just summary of included commits...
I will do that also for `dev` branch.

But must be kept like that, or this effort will be useless

**Comment by zen0bit** [comment]
> I need that you upload all other modules in this PR and that you redirect it to "dev"
> 
> It will be easier for me to test if this code work as it should

I can't really work with your repo due to Merge Commits everywhere.

But found solution...

Issue opened...
PS: I think I deleted modules here together with ivan commit...

I solved in cleaned branch.

If you clean your history, I can make PR. Then will look like this:
https://github.com/oSoWoSo/AM/pull/7
(But clean first)

**Comment by ivan-hc** [comment]
Sorry, always happens that something must be crrected in main, now in template, for option 0 (the one for appimages)

https://github.com/ivan-hc/AM/commit/2dd86c632b941a0656b15f14fdcb74dcde6fb59e

due to new template for AppImages, I had a wrong AM-updater when the apps are not hosted on github.

Please fix it in your fork.

**Comment by zen0bit** [comment]
continue in #565

**Pull request closed without merging**
