### PR TITLE
"AM" 9.1.3, full support for AppBundleHUB

### PR DESCRIPTION
**Pull request by ivan-hc**
fix https://github.com/ivan-hc/AM/issues/1157

### CODE REVIEW

**Comment by ivan-hc** [comment]
This is what I have done in the latest commit https://github.com/ivan-hc/AM/pull/1160/commits/6e0ced3d5baaae0d1417b1a9ca82dec4b7782c18

Istantanea_2024-11-27_16-26-30

I suggest the package name, since the flag --toolpac does not work for AppBundles in `-i`

@xplshn

**Comment by ivan-hc** [comment]
It is better to suggest the package name whether it is installed or not

Istantanea_2024-11-27_16-54-46

...so now don't say that people will think they are not yours, oh! u.u

**Comment by ivan-hc** [comment]
@xplshn you just need to give me a unique term to use in `-f` to list your apps as something other than a common `posix-script`, as I asked at https://github.com/ivan-hc/AM/issues/1157#issuecomment-2503823385

**Comment by ivan-hc** [comment]
@xplshn this commit https://github.com/ivan-hc/AM/pull/1160/commits/fd882e72312c212201a898c821a1228a72dad7fe allows the inclusion of AppBundles in normal `query`, no flag is needed

Istantanea_2024-11-27_17-16-41

However, in `-l` I keep my list with apps from my database only, yours will be shown with `--toolpack` and `--all`...precisely because I'm "picky" u.u

**Comment by ivan-hc** [comment]
@xplshn on the contrary, option `-i` will not install your apps if you don't write the whole package name

Istantanea_2024-11-27_17-22-20

...and they should make a saint of whoever invented `bash-completion` :pray:

**Comment by ivan-hc** [comment]
now all that's missing is the `-f` identifier and I'll be ready to merge the changes into the main branch

@xplshn tell me, are you happy now?

**Comment by ivan-hc** [comment]
@xplshn so as you said here https://github.com/ivan-hc/AM/issues/1157#issuecomment-2504326163 I added this check
```
	elif grep '__ARCHIVE_MARKER__' "${LINK:-$FILE}" >/dev/null 2>&1; then
		echo " ◆ $arg	|	dwarfs-appbundle" >> "$AMCACHEDIR"/files-type
```
and this is the result

Istantanea_2024-11-27_17-52-34

is it ok then?

**Comment by candrapersada** [comment]
how to use sandbox?

**Comment by Samueru-sama** [comment]
> how to use sandbox?

With AppBundles? Not possible since aisap only supports appimages.

**Pull request merged**
