### PR TITLE
reviewdog-suggester

### PR DESCRIPTION
**Pull request by zen0bit**
I am back 🤣 
What about Review 🐶 Suggester?

Just turn ON actions 😄

### CODE REVIEW

**Comment by ivan-hc** [comment]
What is this? xD

**Comment by zen0bit** [comment]
> What is this? xD

### Code suggestions (lint) for PRs

Right time, or I need wait a bit more? 😉

**Comment by zen0bit** [comment]
It's just add suggestion to code in PR. Nothing is automatically changed.
Here is preview [PR](https://github.com/quickemu-project/quickemu/pull/980/files) in quickemu repo

**Comment by ivan-hc** [comment]
I put the dog to sleep, when I need him I'll call him https://github.com/ivan-hc/AM/commit/c7dba5bff029b1566178f4bb88e7870911f135e6

Thanks again, I still find it very useful... but for this PR I didn't have the... croquettes.

**Pull request merged**
