### PR TITLE
cat << EOF instead

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by ivan-hc** [comment]
-_-
```
sudo '/home/ivan/Scrivania/INSTALL' 
mkdir: opzione non valida -- "r"
Try 'mkdir --help' for more information.
/home/ivan/Scrivania/INSTALL: 5: cd: can't cd to /opt/am
Something goes wrong!
chmod: impossibile accedere a '/opt/am/APP-MANAGER': File o directory non esistente
/home/ivan/Scrivania/INSTALL: 16: cannot create /opt/am/remove: Directory nonexistent
chmod: impossibile accedere a '/opt/am/remove': File o directory non esistente
/home/ivan/Scrivania/INSTALL: 28: cannot create /opt/am/am-completion.sh: Directory nonexistent
/home/ivan/Scrivania/INSTALL: 28: cannot create /opt/am/am-completion.sh: Directory nonexistent
chmod: impossibile accedere a '/opt/am/am-completion.sh': File o directory non esistente
/home/ivan/Scrivania/INSTALL: 30: cannot create /opt/am/remove: Directory nonexistent
/home/ivan/Scrivania/INSTALL: 31: cannot create /opt/am/remove: Directory nonexistent
chmod: impossibile accedere a '/opt/am/remove': File o directory non esistente
mv: impossibile eseguire stat di '/opt/am/am-completion.sh': File o directory non esistente

               _____                    _____ 
              /\    \                  /\    \		   A	   A
             /::\    \                /::\____\		    P	    M
            /::::\    \              /::::|   |		     P
           /::::::\    \            /:::::|   |		      M	      &
          /:::/\:::\    \          /::::::|   |		       A
         /:::/__\:::\    \        /:::/|::|   |		        N
        /::::\   \:::\    \      /:::/ |::|   |
       /::::::\   \:::\    \    /:::/  |::|___|______
      /:::/\:::\   \:::\    \  /:::/   |::::::::\    \
     /:::/  \:::\   \:::\____\/:::/    |:::::::::\____\
     \::/    \:::\  /:::/    /\::/    / ~~~~~/:::/    /
      \/____/ \:::\/:::/    /  \/____/      /:::/    /
               \::::::/    /               /:::/    /
                \::::/    /               /:::/    /
                /:::/    /               /:::/    /╔═╗╔╗╔┌─┐┌─┐┌─┐┬─┐
               /:::/    /               /:::/    / ╠═╣║║║├─┤│ ┬├┤ ├┬┘
              /:::/    /               /:::/    /  ╩ ╩╝╚╝┴ ┴└─┘└─┘┴└─
             /:::/    /╔═╗╔═╗┬  ┬┌─┐┌─┐┌┬┐┬┌─┐┌┐┌
             \::/    / ╠═╝╠═╝│  ││  ├─┤ │ ││ ││││
              \/____/  ╩  ╩  ┴─┘┴└─┘┴ ┴ ┴ ┴└─┘┘└┘	by Ivan Alex HC
							
  >> 𝘋𝘢𝘵𝘢𝘣𝘢𝘴𝘦 & 𝘴𝘰𝘭𝘶𝘵𝘪𝘰𝘯𝘴 𝘧𝘰𝘳 𝘢𝘭𝘭 𝘈𝘱𝘱𝘐𝘮𝘢𝘨𝘦𝘴 𝘢𝘯𝘥 𝘱𝘰𝘳𝘵𝘢𝘣𝘭𝘦 𝘢𝘱𝘱𝘴 𝘧𝘰𝘳 𝘎𝘕𝘜/𝘓𝘪𝘯𝘶𝘹 << 
  
 ##########################################################################
 __________________________________________________________________________
 
 SITE: https://portable-linux-apps.github.io
 
 REPOSITORY: https://github.com/ivan-hc/am-application-manager
 __________________________________________________________________________

 ##########################################################################

             Run "am -h" to see the list of the options
 
 ##########################################################################
```

**Comment by zen0bit** [comment]
What you mention isn't in this PR...

**Comment by zen0bit** [comment]
> -_-
> 
> ```
> sudo '/home/ivan/Scrivania/INSTALL' 
> mkdir: opzione non valida -- "r"
> Try 'mkdir --help' for more information.
> /home/ivan/Scrivania/INSTALL: 5: cd: can't cd to /opt/am
> Something goes wrong!
> chmod: impossibile accedere a '/opt/am/APP-MANAGER': File o directory non esistente
> /home/ivan/Scrivania/INSTALL: 16: cannot create /opt/am/remove: Directory nonexistent
> chmod: impossibile accedere a '/opt/am/remove': File o directory non esistente
> /home/ivan/Scrivania/INSTALL: 28: cannot create /opt/am/am-completion.sh: Directory nonexistent
> /home/ivan/Scrivania/INSTALL: 28: cannot create /opt/am/am-completion.sh: Directory nonexistent
> chmod: impossibile accedere a '/opt/am/am-completion.sh': File o directory non esistente
> /home/ivan/Scrivania/INSTALL: 30: cannot create /opt/am/remove: Directory nonexistent
> /home/ivan/Scrivania/INSTALL: 31: cannot create /opt/am/remove: Directory nonexistent
> chmod: impossibile accedere a '/opt/am/remove': File o directory non esistente
> mv: impossibile eseguire stat di '/opt/am/am-completion.sh': File o directory non esistente
> 
>                _____                    _____ 
>               /\    \                  /\    \		   A	   A
>              /::\    \                /::\____\		    P	    M
>             /::::\    \              /::::|   |		     P
>            /::::::\    \            /:::::|   |		      M	      &
>           /:::/\:::\    \          /::::::|   |		       A
>          /:::/__\:::\    \        /:::/|::|   |		        N
>         /::::\   \:::\    \      /:::/ |::|   |
>        /::::::\   \:::\    \    /:::/  |::|___|______
>       /:::/\:::\   \:::\    \  /:::/   |::::::::\    \
>      /:::/  \:::\   \:::\____\/:::/    |:::::::::\____\
>      \::/    \:::\  /:::/    /\::/    / ~~~~~/:::/    /
>       \/____/ \:::\/:::/    /  \/____/      /:::/    /
>                \::::::/    /               /:::/    /
>                 \::::/    /               /:::/    /
>                 /:::/    /               /:::/    /╔═╗╔╗╔┌─┐┌─┐┌─┐┬─┐
>                /:::/    /               /:::/    / ╠═╣║║║├─┤│ ┬├┤ ├┬┘
>               /:::/    /               /:::/    /  ╩ ╩╝╚╝┴ ┴└─┘└─┘┴└─
>              /:::/    /╔═╗╔═╗┬  ┬┌─┐┌─┐┌┬┐┬┌─┐┌┐┌
>              \::/    / ╠═╝╠═╝│  ││  ├─┤ │ ││ ││││
>               \/____/  ╩  ╩  ┴─┘┴└─┘┴ ┴ ┴ ┴└─┘┘└┘	by Ivan Alex HC
> 							
>   >> 𝘋𝘢𝘵𝘢𝘣𝘢𝘴𝘦 & 𝘴𝘰𝘭𝘶𝘵𝘪𝘰𝘯𝘴 𝘧𝘰𝘳 𝘢𝘭𝘭 𝘈𝘱𝘱𝘐𝘮𝘢𝘨𝘦𝘴 𝘢𝘯𝘥 𝘱𝘰𝘳𝘵𝘢𝘣𝘭𝘦 𝘢𝘱𝘱𝘴 𝘧𝘰𝘳 𝘎𝘕𝘜/𝘓𝘪𝘯𝘶𝘹 << 
>   
>  ##########################################################################
>  __________________________________________________________________________
>  
>  SITE: https://portable-linux-apps.github.io
>  
>  REPOSITORY: https://github.com/ivan-hc/am-application-manager
>  __________________________________________________________________________
> 
>  ##########################################################################
> 
>              Run "am -h" to see the list of the options
>  
>  ##########################################################################
> ```

What you mention isn't in this PR...

**Comment by ivan-hc** [comment]
I was unable to execute /opt/am/remove, without it I cannot remove AM

**Pull request merged**
