### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ivan-hc**

### CODE REVIEW

**Comment by ivan-hc** [comment]
@zen0bit @nazdridoy 

Today I started to convert multiple blank lines that appear in pages like the one of Bottles, that have 4 screenshots, to one line.

The only issue here I've faced was that the same pages were downloaded several times and was merged several times.

In my tests before the last commit I've found the same page several times in the "about" directory.

The only solution was to remove that directory that @nazdridoy had renamed "$cache_dir", so I added this solution in the last commit.

That's what I was saying, your coding style will also be easy to read for other developers who are involved in the trade... but what about me? You must understand that after 24 hours of trying to get Bottles AppImage to work on Debian Stable and arguing with a Debian developer about how useless certain packages in the Debian repositories are (they're so patched that they've lost their identity... I'm talking about " python3-pycurl"), after learning to compile packages with Python PIP (to no avail, since they work on the machine you're using, not in a Github Actions workflow)... and after all this, could I ever be lucid enough to apply myself to understand a BASH script written in a different way than I'm used to?

So, sorry for the inconvenience. I hope you forgive my attitude.

**Comment by zen0bit** [comment]
Do you know that you can modify any default linter to your style and THEN share that style? Maybe in lint github action on PRs so anyone comply to same linting?

**Comment by ivan-hc** [comment]
My rules are... nothing. Just simple script like those that a newbie can write by itself. Many simple scripts merged together, I don't use many environment variables, as you can see... and I admit that sometime my scripts are redoundant.

**Comment by nazdridoy** [comment]
@ivan-hc  Does [this](https://github.com/ivan-hc/AM/compare/40b4e4b..e3c1a12#diff-f3da95c6dbb4f4f17959f28ed9812958bf051383b69d361bc884ae0eb4548514) really justify a full revert and the throwaway work of others that they have put hours into, without even asking them to address the new issue which almost certainly has nothing to do with their "changes" and has been caused by another part of the script? (Refer to your recent changes on how AM handles /opt/AM/.cache).



> The only solution was to remove that directory that @nazdridoy had renamed "$cache_dir", so I added this solution in the last commit.

i haven't renamed anything. i have just use a temporary local variable to store cache_dir instead of hard codding it.

Instead of throwing dirt at each other, we should have worked together to solve new issues as they arise. That's how a project grows, or else people ignore and forget about it, leading to forks and the community moving elsewhere.

**Comment by ivan-hc** [comment]
@nazdridoy you're right, I acted too impulsively. Sorry

**Pull request merged**
