### PR TITLE
added apps

### PR DESCRIPTION
**Pull request by Sush-ruta**
[aisap.md](https://github.com/user-attachments/files/17356414/aisap.md)
[aretext.md](https://github.com/user-attachments/files/17356415/aretext.md)
[binfinder.md](https://github.com/user-attachments/files/17356417/binfinder.md)
[boxxy.md](https://github.com/user-attachments/files/17356418/boxxy.md)
[brutespray.md](https://github.com/user-attachments/files/17356419/brutespray.md)
[cowitness.md](https://github.com/user-attachments/files/17356421/cowitness.md)
[dbin.md](https://github.com/user-attachments/files/17356422/dbin.md)
[gickup.md](https://github.com/user-attachments/files/17356423/gickup.md)
[git-cliff.md](https://github.com/user-attachments/files/17356424/git-cliff.md)
[gitleaks.md](https://github.com/user-attachments/files/17356425/gitleaks.md)
[gitql.md](https://github.com/user-attachments/files/17356426/gitql.md)
[godmode.md](https://github.com/user-attachments/files/17356427/godmode.md)
[gost-shred.md](https://github.com/user-attachments/files/17356428/gost-shred.md)
[himalaya.md](https://github.com/user-attachments/files/17356429/himalaya.md)
[iptracker.md](https://github.com/user-attachments/files/17356430/iptracker.md)
[keep.md](https://github.com/user-attachments/files/17356431/keep.md)
[leaflet.md](https://github.com/user-attachments/files/17356432/leaflet.md)
[pho.md](https://github.com/user-attachments/files/17356433/pho.md)
[rustypaste.md](https://github.com/user-attachments/files/17356434/rustypaste.md)
[sphia.md](https://github.com/user-attachments/files/17356435/sphia.md)
[stew.md](https://github.com/user-attachments/files/17356436/stew.md)
[vegeta.md](https://github.com/user-attachments/files/17356437/vegeta.md)
[volaris.md](https://github.com/user-attachments/files/17356438/volaris.md)
[wournal.md](https://github.com/user-attachments/files/17356439/wournal.md)
[yup.md](https://github.com/user-attachments/files/17356440/yup.md)

```
❯ cat list
◆ leaflet : 
◆ wournal : Simple \"digitial paper\" for note taking and PDF annotation. Heavily inspired by Xournal.
◆ volaris : 
◆ gost-shred : GOST R 50739-95 Data Sanitization Method (2 passes)
◆ sphia : Sphia - a Proxy Handling Intuitive Application
◆ iptracker : Desktop tool to keep track of your IP address and update you when it changes
◆ aisap : Tool to make sandboxing AppImages easy
◆ godmode : AI Chat Browser: Fast, Full webapp access to ChatGPT / Claude / Bard / Bing / Llama2! I use this 20 times a day.
◆ keep : Desktop app for Google Keep packaged with Electron
◆ yup : 
◆ pho : 
◆ stew : 🥘 An independent package manager for compiled binaries.
◆ binfinder : Find binary files not installed through package manager
◆ dbin : 📦 Poor man's package manager. +2930 statically linked binaries in the repos! The easy to use, easy to get, suckless software distribution system
◆ aretext : Minimalist text editor with vim-compatible key bindings.
◆ cowitness : CoWitness is a powerful web application testing tool that enhances the accuracy and efficiency of your testing efforts. It allows you to mimic an HTTP server and a DNS server, providing complete responses and valuable insights during your testing process.
◆ boxxy : boxxy puts bad Linux applications in a box with only their files.
◆ brutespray : Bruteforcing from various scanner output - Automatically attempts default creds on found services.
◆ vegeta : HTTP load testing tool and library. It's over 9000!
◆ rustypaste : A minimal file upload/pastebin service.
◆ himalaya : CLI to manage emails
◆ gickup : "description": null,
◆ gitleaks : Protect and discover secrets using Gitleaks 🔑
◆ git-cliff : A highly customizable Changelog Generator that follows Conventional Commit specifications ⛰️ 
◆ gitql : 💊 A git query language
```

### CODE REVIEW

**Comment by ivan-hc** [comment]
hi, "aisap" is already in the repo, we use it for sandbox appimages in `--sandbox`

**Comment by ivan-hc** [comment]
Sorry if i don't get to this right away, i have a problem with almost all my appimage packages that use Arch Linux as a base, and i need to fix it ASAP

| Istantanea_2024-10-13_18-51-24 png | Istantanea_2024-10-13_18-58-23 png |
| - | - |

It's all AppArmor's fault in the new Ubuntu builds used in the github workflows.

**Comment by Sush-ruta** [comment]
> "aisap" is already in the repo

Shit, sorry. I usually search with ctrl+F but this one must have slipped. Will take double care next time @ivan-hc

**Comment by ivan-hc** [comment]
don't worry, normally I check from the list if there are duplicated, using the one you provide

I hope to take are of this PR ASAP, Canonical/Ubuntu is a true shit.

**Comment by ivan-hc** [comment]
We are ready, thank you again @Sush-ruta

**Pull request merged**
