### PR TITLE
Add warp-terminal

### PR DESCRIPTION
**Pull request by nazdridoy**
Warp is the terminal reimagined with AI and collaborative tools for better productivity.

https://www.warp.dev

### CODE REVIEW

**Comment by ivan-hc** [comment]
@nazdridoy are you another follower of TheLinuxExperiment YT channel?

https://youtu.be/8ZrNRk9OUGA?feature=shared&t=382

Just wieving the video... its sad that in the previous block have mentioned "Snap and Flatpak" but not "AM" for centralized distribution method of software :(

**Comment by ivan-hc** [comment]
Go on YouTube and search "appimage" or "appimages", none apart DistroTube knows "AM", and those that know it, still pretend that this tool does not exist. Also those that hate appimages say that they would be fantastic if them work out of the box, can be managed and updated like any other normal package. Why everyone ignore "AM" or Appman? I perform this search every week on YouTube. I know who knows, but I can't explain why we are still gosts.

**Comment by nazdridoy** [comment]
> DistroTube knows "AM".

Yes, because of him, I've found AM.

> Why does everyone ignore "AM" or Appman?

It's sad, and I wish more people knew about AM. Have you tried reaching out to any Linux channels? Maybe they really don't know about AM?

> Why does everyone ignore "AM" or Appman?

Some, like BrodieRobertson, probably hate AppImage because they dislike ProbonoPD. In my humble opinion, AppImage is not perfect, but it does have the potential to be the most user-friendly package format of all, and definitely deserves more attention.

**Comment by ivan-hc** [comment]
> probably hate AppImage because they dislike ProbonoPD

this, I want you see this piece of poadcast of two years ago https://www.youtube.com/watch?v=o8X6AbVgcqI&t=2284s

Here they are talking about a earlier release of AppMan

**Comment by ivan-hc** [comment]
I developed AppMan first, it was installing apps into a /opt/bin directory at system level... for me it was wrong, so I abandoned it to create something that manages apps by following the Linux Standard Base. I've called it "AM" because AppMan was already taken. Then I decided to rewrite AppMan to satisfy the needings of non-privileged users. The rest is story.

**Comment by nazdridoy** [comment]
> this, I want you see this piece of poadcast of two years ago https://www.youtube.com/watch?v=o8X6AbVgcqI&t=2284s

I generally steer clear of online drama, but I've noticed that some of the things ProbonoPD says and the way he portrays AppImage seems to do more harm than good for AppImages.

**Comment by nazdridoy** [comment]
>The rest is story.

dude, don't get discouraged. If AppImage is a good and user-friendly format (which it is), it'll probably catch on. What you've done is awesome.
I, like many others (ProbonoPD may think otherwise), avoided AppImages because the distribution system seemed unreliable. No central repository and downloading from the website (sounds dumb, i mean Windows). I was writing an app manager (for and by myself) using Python and Lua. I implemented some basic functionalities, but in the end, most of the repositories that I added as sources seemed dead and full of outdated and "unofficial" AppImages. I ditched the idea of using AppImages and chose Flatpak (I'd never use Snap, not even for a million dollars. Not because I have canonical but because I think it's objectively the worst format). Permission issues (you can't do this, that) outweigh any benefits that come with sandboxing. Then DT released his video about AM, and now here I am, doing what I can to improve AM, because I genuinely like the project and think that rather than making a fork and rewriting in another language, I should try to improve this. AM is now my daily driver along with Pacman, Paru, Distrobox, and Flatpak.

**Pull request merged**
