### PR TITLE
More optimizations

### PR DESCRIPTION
**Pull request by Samueru-sama**
Ok several things changed here: 

* First change: https://i.redd.it/4ai705yurikb1.jpg

* Use one `mkdir` to make all nested directories. tested and works without problems.

* Made the remover safer since we only need to use `rm -R -f` for the `$APP` directory. tested it and works without issues.

* New way of getting the icon by extracting `.DirIcon`. I also tested when `./DirIcon` is a symlink with the tesseract appimage where this happens, and it worked like it should, it used the path in the symlink to get the right icon with --appimage-extract. 🎉

* Combined the sed commands into one, it works without issues as well. 

* Added quotations to several paths for safety™

* first pkgversion attempt, @zen0bit I also want your input on how pkgversion should be done.

### CODE REVIEW

**Comment by ivan-hc** [comment]
Is `exit 0` in the AM-updater ok to prevent it exits if updating all apps in bulk?

**Comment by ivan-hc** [comment]
and why you have put these lines 16 and 17? :laughing:

**Comment by Samueru-sama** [comment]
> Is `exit 0` in the AM-updater ok to prevent it exits if updating all apps in bulk?

I just tested adding a exit 0 to the `AM-updater` of one of my apps and then update the rest of the system, it continued checking the rest of apps for updates. 

>and why you have put these lines 16 and 17? 😆

You wanted version in line 19 didn't you xd.

**Comment by ivan-hc** [comment]
ad as a title
```
# CHECK VERSION AND DOWNLOAD THE APP
# ALSO MADE IT EXECUTABLE...
```
not exactly these messages, but a message done this way is in line with the rest of messages

**Comment by ivan-hc** [comment]
NOTE, do you know why I added spaces before the two `cd ..` commands? Because sometime an AppImage is stored into an archive, so we have to add a command that extract it

**Comment by Samueru-sama** [comment]
Ok the title done thing is done

> NOTE, do you know why I added spaces before the two `cd ..` commands? Because sometime an AppImage is stored into an archive, so we have to add a command that extract it

Do you want me to put a comment there like `# Replace this tar commands in case the APP needs to be extracted` ?

**Comment by ivan-hc** [comment]
> Ok the title done thing is done
> 
> > NOTE, do you know why I added spaces before the two `cd ..` commands? Because sometime an AppImage is stored into an archive, so we have to add a command that extract it
> 
> Do you want me to put a comment there like `# Replace this tar commands in case the APP needs to be extracted` ?

No, its not needed... I think. Would it be intuitive for you?

**Comment by ivan-hc** [comment]
Are you sure that your ./DirIcon thing is OK?

I have a patch in the [install.am](https://github.com/ivan-hc/AM/blob/main/modules/install.am) module to check if the /opt/$APP/icons directory is empty, and if so it downloads the icon from portable-linux-apps.github.io , at line 157 of the module

**Comment by Samueru-sama** [comment]
>No, its not needed... I think. Would it be intuitive for you?

I added something anyway. 

>Are you sure that your ./DirIcon thing is OK?

Yes:

* It works when `.DirIcon` is an image. (Tested with librewolf and dolphin-emu).
* Also works when `*DirIcon` is a symlink (Tested with tesseract). 

>I have a patch in the [install.am](https://github.com/ivan-hc/AM/blob/main/modules/install.am) module to check if the /opt/$APP/icons directory is empty, and if so it downloads the icon from portable-linux-apps.github.io , at line 157 of the module

The only case this might be needed is if the appimage icon is a dummy file. if anything this new method makes it less likely because now it at  least checks if the icon is a symlink and fixes it.

**Comment by ivan-hc** [comment]
its good this new pkgversion function you added, maibe iI should truncate the output in case its too long, to fit it into a 80 characters wide in the table of `-f`

**Comment by Samueru-sama** [comment]
> its good this new pkgversion function you added, maibe iI should truncate the output in case its too long, to fit it into a 80 characters wide in the table of `-f`

How can I do that 🙃

I just googled for a solution and what I saw is more complex than the DirIcon thing lol. There has to be a better way lol.

**Comment by ivan-hc** [comment]
> > its good this new pkgversion function you added, maibe iI should truncate the output in case its too long, to fit it into a 80 characters wide in the table of `-f`
> 
> How can I do that 🙃
> 
> I just googled for a solution and what I saw is more complex than the DirIcon thing lol. There has to be a better way lol.

this will be my task, I'll use the same solution I use in `-l` and `-q` there

Anyway, I'm still of the opinion that to show that fourth column is anti aesthetic. Maybe I'll add a sub-option for that (we already have `--less`, maibe it will be `--more`)

**Comment by Samueru-sama** [comment]
> > > its good this new pkgversion function you added, maibe iI should truncate the output in case its too long, to fit it into a 80 characters wide in the table of `-f`
> > 
> > 
> > How can I do that 🙃
> > I just googled for a solution and what I saw is more complex than the DirIcon thing lol. There has to be a better way lol.
> 
> this will be my task, I'll use the same solution I use in `-l` and `-q` there
> 
> Anyway, I'm still of the opinion that to show that fourth column is anti aesthetic. Maybe I'll add a sub-option for that (we already have `--less`, maybe it will be `--more`)

What about this? 

pkgversion=$(echo "$version" | awk -F / '{print $(NF-1)}' | cut -c1-10)

Just tested it and it works.

**Comment by ivan-hc** [comment]
instead of
```
cd "/opt/$APP/tmp" || exit 1
```
why not
```
cd "/opt/$APP/tmp" || return
```
?

is this to allow install.am deleting what has been installed if ./tmp is still there?

sorry for my ignorance, you're much more advanced than me in scripting :smile:

**Comment by Samueru-sama** [comment]
> instead of
> 
> ```
> cd "/opt/$APP/tmp" || exit 1
> ```
> 
> why not
> 
> ```
> cd "/opt/$APP/tmp" || return
> ```
> 
> in the AM-updater?
> 
> why not to include this in normal installation to allow install.am deleting what has been installed if ./tmp is still there?

I just tested changing the cd path in my librewolf AM-updater to a broken path and tested adding a `|| exit 1` and a `|| return` and in both cases the tmp dir doesn't get deleted. 

And I mean that is the intended behavior, you don't want rm -rf running if something that should not fail like the simple cd does fail.

**Comment by ivan-hc** [comment]
Is this script OK or you think we need to add something else?

**Comment by Samueru-sama** [comment]
> Is this script OK or you think we need to add something else?

I'm waiting for @zen0bit to say something lol. But yeah looks good to me as it is.

**Comment by ivan-hc** [comment]
@Samueru-sama NOTE, the pkgversion file should be edited also in the AM-updater, to keep it updated in case a new version has been changed... this should be done at the end of the function, when the file is updated.

**Comment by ivan-hc** [comment]
@Samueru-sama @zen0bit I've added a sub-option `--version` to files.am in this branch:

https://github.com/ivan-hc/AM/blob/dev/modules/files.am

This is the code:
```
function _files_version(){
	rm -f $AMPATH/.cache/files-args
	cd $APPSPATH &&
	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
	echo "- ------- | -------" >> $AMPATH/.cache/files-args
	for arg in $INSTALLED_APPS; do
		if test -f ./$arg/remove 2>/dev/null; then
			if test -f ./$arg/version 2>/dev/null; then
				VERSION=$(cat $APPSPATH/$arg/version | head -1 | sed 's:.*/::' | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}")
				if [ -z "$VERSION" ]; then
					VERSION="unknown"
				fi
			elif test -f ./$arg/pkgversion; then
				VERSION=$(cat $APPSPATH/$arg/pkgversion | head -1)
			elif [ "$arg" == "$AMCLI" ]; then
				VERSION=$($AMCLIPATH -v)
			else
				VERSION="unknown"
			fi
			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
		fi
	done
	cat $AMPATH/.cache/files-args | column -t
	echo ""
}
```
this is how it is called:
```
if [ "$2" = "--less" ]; then
	cd "$APPSPATH" &&
	find . -type f -name 'remove' 2>/dev/null | sed -r 's|/[^/]+$||' | sort | uniq | wc -l
	exit 0
elif [ "$2" = "--version" ]; then
	_files_header
	_files_version
else
	_files_header
	_files
fi
```
and this is the result on my system:

Istantanea_2024-04-17_14-10-46

**Comment by ivan-hc** [comment]
And I can keep improve it

**Comment by ivan-hc** [comment]
> And I can keep improve it

for example, add `elif` to check if a .zsync file is available (in my case, I have Libreoffice that uses it):
```
function _files_version(){
	rm -f $AMPATH/.cache/files-args
	cd $APPSPATH &&
	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
	echo "- ------- | -------" >> $AMPATH/.cache/files-args
	for arg in $INSTALLED_APPS; do
		if test -f ./$arg/remove 2>/dev/null; then
			if test -f ./$arg/version 2>/dev/null; then
				VERSION=$(cat $APPSPATH/$arg/version | head -1 | sed 's:.*/::' | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}")
				if [ -z "$VERSION" ]; then
					if test -f ./$arg/*.zsync 2>/dev/null; then
						VERSION="continuous"
					else
						VERSION="unknown"
					fi
				fi
			elif test -f ./$arg/pkgversion; then
				VERSION=$(cat $APPSPATH/$arg/pkgversion | head -1)
			elif [ "$arg" == "$AMCLI" ]; then
				VERSION=$($AMCLIPATH -v)
			else
				VERSION="unknown"
			fi
			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
		fi
	done
	cat $AMPATH/.cache/files-args | column -t
	echo ""
}
```
this is the result:

Istantanea_2024-04-17_14-18-52

**Comment by ivan-hc** [comment]
For now I'll not add this commit, I'll keep it on my PC waiting for your answer

**Comment by ivan-hc** [comment]
Also, consider that if an AppImage has a .zsync file, the "version" file is not in use at all, so you'll keep have the version of the first time you've installed the app, for example in `firefox-appimage`

**Comment by ivan-hc** [comment]
> Also, consider that if an AppImage has a .zsync file, the "version" file is not in use at all, so you'll keep have the version of the first time you've installed the app, for example in `firefox-appimage`

in this case, to test if a .zsync file is a priority, so the function changes like this
```
function _files_version(){
	rm -f $AMPATH/.cache/files-args
	cd $APPSPATH &&
	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
	echo "- ------- | -------" >> $AMPATH/.cache/files-args
	for arg in $INSTALLED_APPS; do
		if test -f ./$arg/remove 2>/dev/null; then
			if test -f ./$arg/*.zsync 2>/dev/null; then
				VERSION="continuous"
			elif test -f ./$arg/version 2>/dev/null; then
				VERSION=$(cat $APPSPATH/$arg/version | head -1 | sed 's:.*/::' | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}")
				if [ -z "$VERSION" ]; then
					VERSION="unknown"
				fi
			elif test -f ./$arg/pkgversion; then
				VERSION=$(cat $APPSPATH/$arg/pkgversion | head -1)
			elif [ "$arg" == "$AMCLI" ]; then
				VERSION=$($AMCLIPATH -v)
			else
				VERSION="unknown"
			fi
			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
		fi
	done
	cat $AMPATH/.cache/files-args | column -t
	echo ""
}
```

**Comment by ivan-hc** [comment]
Hey guys, I'm really really sorry

I've experimented this on even more apps and this is the result:

Istantanea_2024-04-17_14-59-43

and Telegram is not an Appimage.

NOTE, all versions are the correct ones!

**Comment by ivan-hc** [comment]
Funny, "olive-0.1" is a fixed version and "olive" is a continuous build, this is what happens:

Istantanea_2024-04-17_15-11-43

**Comment by zen0bit** [comment]
Closed as "not planned" 🤣

**Comment by ivan-hc** [comment]
> Closed as "not planned" 🤣
> 
> I like that just add version also to bigger one.
> 
> `APPNAME VERSION TYPE SIZE` would be perfect
> 
> arguments are up to you, to fit best
> 
> PS: Or problem with "80"? No longer problem for me 😇 (Not speaking about less) Please `less` in help optional (could by by default)

the real problem is that I don't like it

**Comment by Samueru-sama** [comment]
Ok @ivan-hc Ivan, I go away for two hours and now I'm lost lol

**Comment by Samueru-sama** [comment]
> @Samueru-sama please, replace `else` at line 51, with:
> 
> ```
> 	if [ "$version" != "$version0" ]; then
> 		rm -f /opt/$APP/version
> 		echo "$version" >> /opt/$APP/version
> 	fi
> else
> ```
> 
> its a TAB space.
> 
> In this way we are sure that the latest version is always in the "version" file and we don't need to prioritize the check for .zsync files

Are you sure that last fi is needed?

**Comment by Samueru-sama** [comment]
> > > @Samueru-sama please, replace `else` at line 51, with:
> > > ```
> > > 	if [ "$version" != "$version0" ]; then
> > > 		rm -f /opt/$APP/version
> > > 		echo "$version" >> /opt/$APP/version
> > > 	fi
> > > else
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > its a TAB space.
> > > In this way we are sure that the latest version is always in the "version" file and we don't need to prioritize the check for .zsync files
> > 
> > 
> > Are you sure that last fi is needed?
> > I changed it but I didn't add the fi before the else because that breaks the script.
> 
> if you need I can copy/paste the whole script I've tested

Ok go ahead. I checked what I changed with shellcheck and it is ok.

**Comment by ivan-hc** [comment]
Hey guys, this is the new function:
```
function _files_version(){
	rm -f $AMPATH/.cache/files-args
	cd $APPSPATH &&
	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
	echo "- ------- | -------" >> $AMPATH/.cache/files-args
	for arg in $INSTALLED_APPS; do
		if test -f ./$arg/remove 2>/dev/null; then
			if test -f ./$arg/version 2>/dev/null; then
				VERSION=$(cat $APPSPATH/$arg/version | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
				if [ -z "$VERSION" ]; then
					if test -f ./$arg/*.zsync 2>/dev/null; then
						VERSION=$(strings -d ./$arg/*.zsync | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
						if [ -z "$VERSION" ]; then
							VERSION="continuous"
						fi
					else
						VERSION=$(cat $APPSPATH/$arg/version | sed 's:.*/::' | tr '-' '\n' | grep -vi "appimage\|$arg\|$arch" | grep "[0-9]" | head -1)
					fi
				fi
			elif test -f ./$arg/pkgversion; then
				VERSION=$(cat $APPSPATH/$arg/pkgversion | head -1)
			elif [ "$arg" == "$AMCLI" ]; then
				VERSION=$($AMCLIPATH -v)
			else
				VERSION="unknown"
			fi
			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
		fi
	done
	cat $AMPATH/.cache/files-args | column -t
	echo ""
}
```
and this is the result

Istantanea_2024-04-17_16-19-24

I don't know if we still need that pkgversion file at this point, @Samueru-sama

**Comment by Samueru-sama** [comment]
> Hey guys, this is the new function:
> 
> ```
> function _files_version(){
> 	rm -f $AMPATH/.cache/files-args
> 	cd $APPSPATH &&
> 	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
> 	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
> 	echo "- ------- | -------" >> $AMPATH/.cache/files-args
> 	for arg in $INSTALLED_APPS; do
> 		if test -f ./$arg/remove 2>/dev/null; then
> 			if test -f ./$arg/version 2>/dev/null; then
> 				VERSION=$(cat $APPSPATH/$arg/version | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
> 				if [ -z "$VERSION" ]; then
> 					if test -f ./$arg/*.zsync 2>/dev/null; then
> 						VERSION=$(strings -d ./$arg/*.zsync | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
> 						if [ -z "$VERSION" ]; then
> 							VERSION="continuous"
> 						fi
> 					else
> 						VERSION=$(cat $APPSPATH/$arg/version | sed 's:.*/::' | tr '-' '\n' | grep -vi "appimage\|$arg\|$arch" | grep "[0-9]" | head -1)
> 					fi
> 				fi
> 			elif test -f ./$arg/pkgversion; then
> 				VERSION=$(cat $APPSPATH/$arg/pkgversion | head -1)
> 			elif [ "$arg" == "$AMCLI" ]; then
> 				VERSION=$($AMCLIPATH -v)
> 			else
> 				VERSION="unknown"
> 			fi
> 			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
> 		fi
> 	done
> 	cat $AMPATH/.cache/files-args | column -t
> 	echo ""
> }
> ```
> 
> and this is the result
> 
> Istantanea_2024-04-17_16-19-24
> 
> I don't know if we still need that pkgversion file at this point, @Samueru-sama

what are you doing?  running `appimage -v` to get the version? That's ok but it may be too slow. What do you think about using pkgversion is used to store the output of `appimage -v` instead when an app is updated/installed?

**Comment by ivan-hc** [comment]
@Samueru-sama nope, `appimage -v` is useless and doesn't work. Try to run any option with Avidemux and see yourself

**Comment by Samueru-sama** [comment]
> @Samueru-sama nope, `appimage -v` is useless and doesn't work. Try to run any option with Avidemux and see yourself

Ok then, but how fast is what you are doing? because that entire function will be run every time `am -f --version` is used for every application. 

What you are doing to get the actual version can then be piped into pkgversion, and then function can check for pkgversion first, that way it is much faster.

**Comment by ivan-hc** [comment]
All I did was to check the version, in order:
- from the file "version"
- using `strings -d ./$arg/*.zsync` to find this in the .zsync file
- find the version directly from a part of the URL stored in "version"

that's all.

The pkgversion reference is there as well, but at this point the apps that need this are really less.


In that list I have many AppImages and also a binary/executable file.

Some apps, like olive-0.1 and the two "coreapps" are without a way to be updated.

Now, the only two left are firefox and wine....

**Comment by ivan-hc** [comment]
- Firefox is the official version from upstream, it updates itself, and its not an Appimage
- WINE is an AppImage, but uses "appimageupdatetool" to do so... maybe I should replace it with the .zsync file

**Comment by ivan-hc** [comment]
Also, the problem would appear if we install standalone scripts, for example my "archimage-cli" or "appimagen", or maybe a Firefox webapp

**Comment by ivan-hc** [comment]
apart all these, the issue is totally covered (and @zen0bit have to gave me 50€ ahahahh :rofl: ... I jocke)

**Comment by ivan-hc** [comment]
Oh my bad, both wine and firefox have a file near them named "updater" but they are different, the one I added for WINE is an AppImage (i.e. "appimageupdatetool", renamed) the other one not... so using this function I made it slower:
```
function _files_version(){
	rm -f $AMPATH/.cache/files-args
	cd $APPSPATH &&
	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
	echo "- ------- | -------" >> $AMPATH/.cache/files-args
	for arg in $INSTALLED_APPS; do
		if test -f ./$arg/remove 2>/dev/null; then
			if test -f ./$arg/version 2>/dev/null; then
				VERSION=$(cat $APPSPATH/$arg/version | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
				if [ -z "$VERSION" ]; then
					if test -f ./$arg/*.zsync 2>/dev/null; then
						VERSION=$(strings -d ./$arg/*.zsync | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
						if [ -z "$VERSION" ]; then
							VERSION="continuous"
						fi
					else
						VERSION=$(cat $APPSPATH/$arg/version | sed 's:.*/::' | tr '-' '\n' | grep -vi "appimage\|$arg\|$arch" | grep "[0-9]" | head -1)
					fi
				fi
			elif test -f ./$arg/updater 2>/dev/null; then
				VERSION=$($APPSPATH/$arg/updater -d $APPSPATH/$arg/$arg 2>/dev/null | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
				if [ -z "$VERSION" ]; then
					VERSION="continuous"
				fi
			elif test -f ./$arg/pkgversion; then
				VERSION=$(cat $APPSPATH/$arg/pkgversion | head -1)
			elif [ "$arg" == "$AMCLI" ]; then
				VERSION=$($AMCLIPATH -v)
			else
				VERSION="unknown"
			fi
			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
		fi
	done
	cat $AMPATH/.cache/files-args | column -t
	echo ""
}
```
and the result is this

Istantanea_2024-04-17_16-53-03

**Comment by Samueru-sama** [comment]
@ivan-hc do I need to change anything else in the pr btw?

**Comment by Samueru-sama** [comment]
> > @ivan-hc do I need to change anything else in the pr btw?
> 
> at this point the pkgversion file is no more needed, sorry for the stressfully request, I was not aware that it was "so easy" to get a version from these packages.
> 
> Now the problem is to find a way to check the version in other kind of files, and this issue will come up with the time.
> 
> In this moment I'm trying to find a way to get the version of WINE without using appimageupdatetool... and the easier way here is to replace that with the .zsync file

pkgversion is not very different than what you are doing, you are using the files module do to the functions from the version to get the actual version while in my case my idea was to use the version with different functions in the package script to get the actual version and pipe it to pkgversion.

I still think that the actual version should be its own file because you are going to run into a case where you can't get it from the version url. but you are the boss so it is your call. 

Do I remove all instances of pkgversion in the pr?

**Comment by ivan-hc** [comment]
> I still think that the actual version should be its own file because you are going to run into a case where you can't get it from the version url. but you are the boss so it is your call.

Come on, don't say that, you make me sound like a tyrant or something

What I'm saying is that objectively we discovered a good system for listing application versions, and we already had it under our noses! So, from this point of view, there would be no need to add additional files to those already provided in the installation scripts.

So yes, I think that we don't need this anymore. I'm really sorry. I know you've spent your time for this. Me too (this is why @zen0bit must give us 50€ per head :money_mouth_face:  )

**Comment by Samueru-sama** [comment]
> > I still think that the actual version should be its own file because you are going to run into a case where you can't get it from the version url. but you are the boss so it is your call.
> 
> Come on, don't say that, you make me sound like a tyrant or something
> 
> What I'm saying is that objectively we discovered a good system for listing application versions, and we already had it under our noses! So, from this point of view, there would be no need to add additional files to those already provided in the installation scripts.
> 
> So yes, I think that we don't need this anymore. I'm really sorry. I know you've spent your time for this. Me too (this is why @zen0bit must give us 50€ per head 🤑 )

I really didn't spend time on the pkgversion, where I spent time was in optimizing the way we get the icon from the appimage, the pkgversion is using the same trick I came up with back when the issue was made lol.

**Comment by ivan-hc** [comment]
I've difficult in put the result of
```
grep -i "version=" ./* 2>/dev/null | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1
```
as version of Firefox

**Comment by zen0bit** [comment]
> So yes, I think that we don't need this anymore. I'm really sorry. I know you've spent your time for this. Me too (this is why @zen0bit must give us 50€ per head 🤑 )

Then you 100€ to me, for advice services and that I just don't let it be...

**Comment by ivan-hc** [comment]
I have fixed the issue with Firefox and also added version for the scripts, function:
```
function _files_version(){
	rm -f $AMPATH/.cache/files-args
	cd $APPSPATH &&
	INSTALLED_APPS=$(find -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2> /dev/null | sort -rh | sed 's@.*	@@')
	echo "- APPNAME | VERSION " >> $AMPATH/.cache/files-args
	echo "- ------- | -------" >> $AMPATH/.cache/files-args
	for arg in $INSTALLED_APPS; do
		if test -f ./$arg/remove 2>/dev/null; then
			if test -f ./$arg/version 2>/dev/null; then
				VERSION=$(cat $APPSPATH/$arg/version | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
				if [ -z "$VERSION" ]; then
					if test -f ./$arg/*.zsync 2>/dev/null; then
						VERSION=$(strings -d ./$arg/*.zsync | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
					else
						VERSION=$(cat $APPSPATH/$arg/version | sed 's:.*/::' | tr '-' '\n' | grep -vi "appimage\|$arg\|$arch" | grep "[0-9]" | head -1)
					fi
				fi
			elif test -f ./$arg/updater 2>/dev/null; then
				VERSION=$($APPSPATH/$arg/updater -d $APPSPATH/$arg/$arg 2>/dev/null | grep -i $arg | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
				if [ -z "$VERSION" ]; then
					VERSION=$(grep -i "version=" $APPSPATH/$arg/* 2>/dev/null | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
				fi
			elif [ "$arg" == "$AMCLI" ]; then
				VERSION=$($AMCLIPATH -v)
			elif grep -qi "version=" ./$arg/* 2>/dev/null; then
				VERSION=$(grep -i "version=" $APPSPATH/$arg/* 2>/dev/null | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}" | head -1)
			elif echo "$arg" | grep -q "ffwa-"; then
				VERSION="WebApp"
			else
				VERSION="unknown"
			fi
			if [ -z "$VERSION" ]; then
				VERSION="unknown"
			fi
			echo " ◆ $arg	|	$VERSION" >> $AMPATH/.cache/files-args
		fi
	done
	cat $AMPATH/.cache/files-args | column -t
	echo ""
}
```
and result:

Istantanea_2024-04-17_18-30-18

nothing has been left behind.

Just point me what version a WebApp should have?

**Comment by zen0bit** [comment]
What that webapp are? Just page packed with chrome/electron?

**Comment by ivan-hc** [comment]
Here we go!!!!!

**Comment by zen0bit** [comment]
Then
- AppImage3
- bin/exec
- AppImage2
- script
- launcher

AI typ 3 - is funny but to much...
# ?

**Comment by Samueru-sama** [comment]
> Here we go!!!!!

Btw I did not remove the change you told me to change in line 51 about version in the app updater, besides that the rest of changes are purely optimizations and don't change the behavior of the template.

**Comment by ivan-hc** [comment]
> > Here we go!!!!!
> 
> Btw I did not remove the change you told me to change in line 51 about version in the app updater, besides that the rest of changes are purely optimizations and don't change the behavior of the template.

Are you jocke? Your review has made the script more little and easier to rad, also in the approach to extract launcher and icon from the Appimage. I think that if this have success, we must implement it also in the option --launcher

**Comment by Samueru-sama** [comment]
> > > Here we go!!!!!
> > 
> > 
> > Btw I did not remove the change you told me to change in line 51 about version in the app updater, besides that the rest of changes are purely optimizations and don't change the behavior of the template.
> 
> Are you joking? Your review has made the script more little and easier to rad, also in the approach to extract launcher and icon from the Appimage. I think that if this have success, we must implement it also in the option --launcher

Btw I converted my appimages to the new template and I ran into a weird bug that only happens with appman. the linking with the `" "` is broken: 

```
# LINK
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
```

Removing the `" "` from `/usr/local/bin/$APP` fixes the issue, but that is weird, I think it is the patching function of the other day that you mentioned had an space but I don't know.

**Comment by ivan-hc** [comment]
This is why I don't use so many times "quotes", sometime is useless

**Comment by Samueru-sama** [comment]
> This is why I don't use so many times "quotes", sometime is useless
> 
> EDIT: I'll fix your template directly, in the current PR I'm working on https://github.com/ivan-hc/AM/tree/dev

hey, you know very darn well that is not the right way of fixing it 🙃

**Comment by ivan-hc** [comment]
> > This is why I don't use so many times "quotes", sometime is useless
> > EDIT: I'll fix your template directly, in the current PR I'm working on https://github.com/ivan-hc/AM/tree/dev
> 
> hey, you know very darn well that is not the right way of fixing it 🙃
> 
> You can also just change it to `/usr/local/bin/"$APP"` if the issue is a leading white space.

let me see...

**Comment by ivan-hc** [comment]
@Samueru-sama is it OK?

https://github.com/ivan-hc/AM/commit/e6038966ddfb277a069550b7c0c9bd031bf26e9a

https://github.com/ivan-hc/AM/commit/6e32054fb9431e056ddd729cae2a4f238061092f

**Comment by Samueru-sama** [comment]
> @Samueru-sama is it OK?
> 
> [e603896](https://github.com/ivan-hc/AM/commit/e6038966ddfb277a069550b7c0c9bd031bf26e9a)
> 
> [6e32054](https://github.com/ivan-hc/AM/commit/6e32054fb9431e056ddd729cae2a4f238061092f)

I don't understand something though. 

How does a sed that changes the path fo the .desktop file break a symlink to `/usr/local/bin/$APP`? 🤔

The issue was with the symlink in `$HOME/.local/bin` when using appman, the .desktop file was installed without issues.

**Comment by ivan-hc** [comment]
See here

https://github.com/ivan-hc/AM/blob/6e32054fb9431e056ddd729cae2a4f238061092f/modules/install.am#L149

**Comment by Samueru-sama** [comment]
> See here
> 
> https://github.com/ivan-hc/AM/blob/6e32054fb9431e056ddd729cae2a4f238061092f/modules/install.am#L149

That makes sense now. thank you.  (I assume this is what needs to able check for `"/usr` btw).

**Comment by ivan-hc** [comment]
done

**Comment by Samueru-sama** [comment]
> done

Also I wonder, if AM always makes a symlink to `/usr/local/bin` why is the .desktop file installed in either `/usr/share/applications` or `/usr/local/share/applications`? Why isn't it always in the later instead?

**Comment by ivan-hc** [comment]
> > done
> 
> Also I wonder, if AM always makes a symlink to `/usr/local/bin` why is the .desktop file installed in either `/usr/share/applications` or `/usr/local/share/applications`? Why isn't it always in the later instead like how the symlink is always in `/usr/local/bin`?

I've not understand the question

**Comment by Samueru-sama** [comment]
> > > done
> > 
> > 
> > Also I wonder, if AM always makes a symlink to `/usr/local/bin` why is the .desktop file installed in either `/usr/share/applications` or `/usr/local/share/applications`? Why isn't it always in the later instead like how the symlink is always in `/usr/local/bin`?
> 
> I've not understand the question

Why is the symlink always in `/usr/local/bin` while the .desktop can be at either `/usr/share/applications` or `/usr/local/share/applications`? Why isn't it always `/usr/local/share/applications` like in the case of `/usr/local/bin`?

**Pull request merged**
