### PR TITLE
finalizing (for now) am_about madule

### PR DESCRIPTION
**Pull request by nazdridoy**
please sync dev branch with main then review this PR if everything seem ok, marge.

### CODE REVIEW

**Comment by ivan-hc** [comment]
I get this error
```
/opt/am/modules/about.am: riga 81: return: è possibile eseguire "return" solo da una funzione o da uno script chiamato
```

**Comment by nazdridoy** [comment]
i don't understand this language

**Comment by ivan-hc** [comment]
this is an error related the command `return`, it says that works only into a function or a called script

However, I've tested it by removing `return` and three arguments, works without errors. I suggest to remove that command... also if I don't know why it is there. For what you use it?

**Comment by nazdridoy** [comment]
already https://github.com/ivan-hc/AM/pull/146

**Pull request closed without merging**
