### PR TITLE
Add "$REALDIR" variable to "APP-MANAGER" and "install.am" to keep the shell in the current directory

### PR DESCRIPTION
**Pull request by ivan-hc**
Fix https://github.com/ivan-hc/AM/issues/653

### CODE REVIEW

**Comment by Samueru-sama** [comment]
I think `REALDIR=$(pwd)` can just be `REALDIR=$PWD` 

Because as far as I know the shell already sets the `$PWD` env variable, so maybe it is not needed to be calling pwd to know that?

I haven't tested it though.

**Comment by ivan-hc** [comment]
> I think `REALDIR=$(pwd)` can just be `REALDIR=$PWD`
> 
> Because as far as I know the shell already sets the `$PWD` env variable, so maybe it is not needed to be calling pwd to know that?
> 
> I haven't tested it though.

tested, and worked

**Comment by ivan-hc** [comment]
we have another issue now: priority!

see what happens if in the PWD directory exists a file with the name of an argument

Istantanea_2024-07-18_16-10-05

**Comment by ivan-hc** [comment]
by inverting the priority order, the module will check hosted arguments before the local ones
```
					if test -f "$AMPATH/neodb"; then
						_install_from_third_party_repo
					elif curl --output /dev/null --silent --head --fail "$APPSDB"/"$arg"  1>/dev/null; then
						_install_normally
					elif test -f "$arg" 2> /dev/null; then
						_install_local_script
					else
						echo " 💀 ERROR: \"$arg\" does NOT exist in the database, see \"$AMCLI -l\""
					fi
```

Istantanea_2024-07-18_16-14-00

**Comment by ivan-hc** [comment]
this will conflict with our style of tests: I should rename my scripts to .sh as you do

its not the way I wanted to made this to work for

**Comment by ivan-hc** [comment]
the last commit solves all issues

her I added an `echo "$arg"` to show the name of the argument

Istantanea_2024-07-18_17-16-12

**Comment by ivan-hc** [comment]
and to be sure that "chromium" is not installed using other cases, I disabled tadabases in this test and this is the result

Istantanea_2024-07-18_17-19-15

**Comment by ivan-hc** [comment]
the last commit adds a message in case of missing file

Istantanea_2024-07-18_17-56-07 png

**Comment by ivan-hc** [comment]
Just tested on Fedora and works.

**Pull request merged**
